---
title: "02/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## two sample t test 


### use R package `pwr`

```{r, echo=T}
library(pwr)
# set effect size d=0.3
pwr.t.test(n=10, d = 10, sig.level = 0.05, alternative = "greater")
```

### Use R package `power.t.test`

[power.t.test](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/power.t.test.html)


```{r, echo=T}
d=0.3; SD=0.2
power.t.test(power = .80, delta = d, alternative = "one.sided", sig.level=0.05, sd=SD)
```

```{r, echo=T}
library(ggplot2)
d=seq(0.1, 1, by=0.1); SD=0.2
sample_size=numeric()
for (i in 1:length(d))
{
  test=power.t.test(power = .80, delta = d[i], alternative = "one.sided", sig.level=0.05, sd=SD)
  sample_size[i]=round(test$n)
}
ggplot(data=data.frame(d, sample_size), aes(x=d, y=sample_size, group=1)) +
  geom_line(color="red")+
  geom_hline(yintercept=0.8, linetype="dashed", color = "blue")+
  geom_point()+
  xlab("d:mean difference")+
  ylab("n:sample size")+
  ggtitle("power=0.8; SD=0.2")

```

```{r, echo=T}
d=0.1; SD=seq(0.1, 1, by=0.1)
sample_size=numeric()
for (i in 1:length(SD))
{
  test=power.t.test(power = .80, delta = d, alternative = "one.sided", sig.level=0.05, sd=SD[i])
  sample_size[i]=round(test$n)
}
ggplot(data=data.frame(SD, sample_size), aes(x=SD, y=sample_size, group=1)) +
  geom_line(color="red")+
  geom_hline(yintercept=0.8, linetype="dashed", color = "blue")+
  geom_point()+
  xlab("SD:standard deviation")+
  ylab("n:sample size")+
  ggtitle("power=0.8; mean diffrence d=0.1")
```


### use formular 

use formular in [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3826013/)

$sample-size=2*SD^2(1.96+0.842)^2/d^2$

```{r, echo=T}
d=0.3; SD=0.2
n=2*SD^2*(1.96+0.842)^2/d^2
n
```

### manual calculation 

```{r, echo=T}
mean=1.65; p_a=0.3; sample_size=7; SD=0.2

power=1-pnorm(1.65-p_a/(SD/sqrt(5)))
power
```