---
title: "2/24/2022"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
library(ggpubr)
set.seed(123)
```

```{r, echo=F, message=F, warning=F}
data=as_tibble(read.csv("C:\\Shengtong\\Research\\AllCollaboration\\2022\\202202\\Mohamed\\D3_ENDO_Clicker_Survey_(Responses)_coded.csv", header=T))

```

## section 1

```{r, echo=F, message=F, warning=F}
questions_index=c(1,3)
questions=colnames(data)[questions_index]
figures=list()
for (i in 1:length(questions))
{
  response=data[,c(questions_index[i], questions_index[i]+1)] 
  colnames(response)=c("response_cate", "coded_response") # rename col names 
  
  response_by_group=response %>% count(response=coded_response) %>% mutate(prop=n/nrow(data)) # group response 
 
  response_cate_number=sort(unique(response$coded_response)); response_cate=numeric() 
  for (j in 1:length(response_cate_number))
    response_cate[j]=unique(response$response_cate[response$coded_response==response_cate_number[j]])
  response_by_group=response_by_group %>% mutate(response_cate=response_cate)
   
  figures[[i]]=
    g1=ggplot(response_by_group, aes(x=response_cate, y=prop, fill=response_cate)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(response_by_group, aes(x=response_cate, y=n, fill=response_cate)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("")+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
figures[[i]]=ggarrange(g1, g2,
                   # labels = c("A", "B", "C"),
                    ncol = 2, nrow = 1)
}
annotate_figure(figures[[1]], top = text_grob(paste(questions[1])))

annotate_figure(figures[[2]], top = text_grob(paste(questions[2])))
```


## section 2

```{r, echo=F, message=F, warning=F}
questions_index=c(5,7, 9,11,13,15)
questions=colnames(data)[questions_index]
figures=list()
for (i in 1:length(questions))
{
  response=data[,c(questions_index[i], questions_index[i]+1)] 
  colnames(response)=c("response_cate", "coded_response") # rename col names 
  
  response_by_group=response %>% count(response=coded_response) %>% mutate(prop=n/nrow(data)) # group response 
 
  response_cate_number=sort(unique(response$coded_response)); response_cate=numeric() 
  for (j in 1:length(response_cate_number))
    response_cate[j]=unique(response$response_cate[response$coded_response==response_cate_number[j]])
  response_by_group=response_by_group %>% mutate(response_cate=response_cate)
   
if (i<=4)
  {   g1=ggplot(response_by_group, aes(x=response_cate, y=prop, fill=response_cate)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars

  g2=ggplot(response_by_group, aes(x=response_cate, y=n, fill=response_cate)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("")+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars
}
  if (i>4)
  {
    g1=ggplot(response_by_group, aes(x=response_cate, y=prop, fill=response_cate)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 60, vjust = 0.5, size=12))+
  ylab("")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars

  g2=ggplot(response_by_group, aes(x=response_cate, y=n, fill=response_cate)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 60, vjust = 0.5, size=12))+
  ylab("")+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars
    
  }
  
  figures[[i]]=ggarrange(g1, g2,
                   # labels = c("A", "B", "C"),
                    ncol = 2, nrow = 1)
}
annotate_figure(figures[[1]], top = text_grob(paste(questions[1])))
annotate_figure(figures[[2]], top = text_grob(paste(questions[2])))
annotate_figure(figures[[3]], top = text_grob(paste(questions[3])))
annotate_figure(figures[[4]], top = text_grob(paste(questions[4])))
annotate_figure(figures[[5]], top = text_grob(paste(questions[5])))
annotate_figure(figures[[6]], top = text_grob(paste(questions[6])))
```



## section 3

```{r, echo=F, message=F, warning=F}
questions_index=c(17,19, 21,23,25)
questions=colnames(data)[questions_index]
figures=list()
for (i in 1:length(questions))
{
  response=data[,c(questions_index[i], questions_index[i]+1)] 
  colnames(response)=c("response_cate", "coded_response") # rename col names 
  
  response_by_group=response %>% count(response=coded_response) %>% mutate(prop=n/nrow(data)) # group response 
 
  response_cate_number=sort(unique(response$coded_response)); response_cate=numeric() 
  for (j in 1:length(response_cate_number))
    response_cate[j]=unique(response$response_cate[response$coded_response==response_cate_number[j]])
  response_by_group=response_by_group %>% mutate(response_cate=response_cate)
   
    g1=ggplot(response_by_group, aes(x=response_cate, y=prop, fill=response_cate)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25)  # add numbers over bars
   
 g2=ggplot(response_by_group, aes(x=response_cate, y=n, fill=response_cate)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("")+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars
  
 figures[[i]]=ggarrange(g1, g2,
                   # labels = c("A", "B", "C"),
                    ncol = 2, nrow = 1)
 
}
annotate_figure(figures[[1]], top = text_grob(paste(questions[1])))
annotate_figure(figures[[2]], top = text_grob(paste(questions[2])))
annotate_figure(figures[[3]], top = text_grob(paste(questions[3])))
annotate_figure(figures[[4]], top = text_grob(paste(questions[4])))
annotate_figure(figures[[5]], top = text_grob(paste(questions[5])))
```

## section 4

```{r, echo=F, message=F, warning=F}
questions_index=c(27,29, 31,33, 35)
questions=colnames(data)[questions_index]
figures=list()
for (i in 1:length(questions))
{
  response=data[,c(questions_index[i], questions_index[i]+1)] 
  colnames(response)=c("response_cate", "coded_response") # rename col names 
  
  response_by_group=response %>% count(response=coded_response) %>% mutate(prop=n/nrow(data)) # group response 
 
  response_cate_number=sort(unique(response$coded_response)); response_cate=numeric() 
  for (j in 1:length(response_cate_number))
    response_cate[j]=unique(response$response_cate[response$coded_response==response_cate_number[j]])
  response_by_group=response_by_group %>% mutate(response_cate=response_cate)
   
  g1=ggplot(response_by_group, aes(x=response_cate, y=prop, fill=response_cate)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25)  # add numbers over bars
  
  g2=ggplot(response_by_group, aes(x=response_cate, y=n, fill=response_cate)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("")+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars
  
 figures[[i]]=ggarrange(g1, g2,
                   # labels = c("A", "B", "C"),
                    ncol = 2, nrow = 1)
}
annotate_figure(figures[[1]], top = text_grob(paste(questions[1])))
annotate_figure(figures[[2]], top = text_grob(paste(questions[2])))
annotate_figure(figures[[3]], top = text_grob(paste(questions[3])))
annotate_figure(figures[[4]], top = text_grob(paste(questions[4])))
annotate_figure(figures[[5]], top = text_grob(paste(questions[5])))
```


## statistical software 

```{r, echo=F}
R.version
```