---
title: "12/15/2022"
output: html_document
date: '2022-12-15'
---


```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
library(ggpubr)
library(gridExtra)
library(rstatix) # use anova_test function 
library(DT)
set.seed(123)
```


```{r, echo=F, warning=F, message=F}
pvalue_adjust=function(p_value)
{
  p_value_adjust=numeric()
for (i in 1:length(p_value))
{
  if (is.na(p_value[i])==T)
    p_value_adjust[i]=p_value[i]
  if (is.na(p_value[i])==F & p_value[i]<0.0001)
    p_value_adjust[i]="<0.0001"
  if (is.na(p_value[i])==F & p_value[i]>0.0001)
    p_value_adjust[i]=round(p_value[i],4)
}
  return(p_value_adjust)
}
```



```{r, echo=F, message=F, warning=F}
data_raw=as_tibble(read.csv("C:\\Shengtong\\Research\\AllCollaboration\\2022\\202212\\Kelley\\Results-2023-01-25 - Deidentified.csv", header=T))

data=as_tibble(read.csv("C:\\Shengtong\\Research\\AllCollaboration\\2022\\202212\\Kelley\\Copy of Results-2023-01-25 - Deidentified - working data - 2023-2-15 - on ext.csv", header=T))
```



## v1: Extraction, Upper TSALD, and Lower TSALD


```{r, echo=F, message=F, warning=F}
sub_data=data%>%select(Ext, Upper.TSALD, Lower.TSALD) %>% drop_na() %>% filter(Ext==0 | Ext==1) %>% filter(Lower.TSALD!="N/A")
sub_data %>% datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

sub_data$Lower.TSALD=as.numeric(sub_data$Lower.TSALD)

#Upper.TSALD.group=numeric()   ## group into 3 groups 
#Upper.TSALD.group=data3$Upper.TSALD
#Upper.TSALD.group[which(abs(data3$Upper.TSALD)<4)]=1
#Upper.TSALD.group[which(abs(data3$Upper.TSALD)>=4 & abs(data3$Upper.TSALD)<8)]=2
#Upper.TSALD.group[which(abs(data3$Upper.TSALD)>8)]=3

```


```{r, echo=F, message=F, warning=F}
#sub_data$Ext=as.vector(sub_data$Ext)
sub_data=data%>%select(Ext, Upper.TSALD, Lower.TSALD) %>% drop_na() %>% filter(Ext==0 | Ext==1) %>% filter(Lower.TSALD!="N/A")
ggplot(sub_data %>% dplyr::count(Ext), aes(x=Ext, y=n, fill=as.character(Ext))) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)+  # add numbers over bars
  ggtitle("")+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title 
#
ggplot(sub_data, aes(x=Upper.TSALD)) + 
  geom_histogram(color="blue", fill="blue")+
geom_vline(aes(xintercept=mean(Upper.TSALD)),
            color="red", linetype="dashed", size=1)

sub_data$Lower.TSALD=as.numeric(sub_data$Lower.TSALD)
ggplot(sub_data, aes(x=Lower.TSALD)) + 
  geom_histogram(color="blue", fill="blue")+
geom_vline(aes(xintercept=mean(Lower.TSALD)),
            color="red", linetype="dashed", size=1)
```


```{r, echo=F, message=F, warning=F}
glm_fit=glm(as.factor(Ext)~Upper.TSALD+Lower.TSALD, data = sub_data, family = "binomial") # response variable need to be factor 
cbind(exp(cbind(OR = coef(glm_fit), confint(glm_fit))), p_value=coef(summary(glm_fit))[,4])




############### visualize odds ratio # https://rpubs.com/mbounthavong/forest_plots_r 
no_cova=2
dat=data.frame( 
  Index=seq(1,no_cova),
  label=c("Upper.TSALD", "Lower.TSALD"),
  Mean_Ratio=exp(round(coef(glm_fit)[2:3],4)),
  #Mean_Ratio=c("1.12(0)", "1.02(0.004)", "0.84(0)", "0.95(0)", "1.08(0)", "1.25(0)", "0.94(0.001)", "1.20(0)"),
  LL=exp(round(confint(glm_fit)[2:3,1],2)),
  UL=exp(round(confint(glm_fit)[2:3,2],2)),
  CI=c("0.768, 0.952", "0.682, 0.836"),
  p_value=round(coef(summary(glm_fit))[2:3,4],3)
)

plot1 <- ggplot(dat, aes(y = Index, x = Mean_Ratio)) +
  geom_point(shape = 18, size = 3) +  
  geom_errorbarh(aes(xmin = LL, xmax = UL), height = 0.25) +
  geom_vline(xintercept = 1, color = "red", linetype = "dashed", cex = 1, alpha = 0.5) +
  scale_y_continuous(name = "", breaks=1:no_cova, labels = dat$label, trans = "reverse") +
  xlab("Odds Ratio (95% CI)") + 
  ylab(" ") + 
  theme_bw() +
  theme(panel.border = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text.y = element_text(size = 12, colour = "black"),
        axis.text.x.bottom = element_text(size = 12, colour = "black"),
        axis.title.x = element_text(size = 12, colour = "black"))

## Create the table-base pallete
table_base <- ggplot(dat, aes(y=label)) +
  ylab(NULL) + xlab("  ") + 
  theme(plot.title = element_text(hjust = 0.5, size=12), 
        axis.text.x = element_text(color="white", hjust = -3, size = 25), ## This is used to help with alignment
        axis.line = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks = element_blank(),
        axis.title.y = element_blank(), 
        legend.position = "none",
        panel.background = element_blank(), 
        panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        plot.background = element_blank())

## OR point estimate table
tab1 <- table_base + 
  labs(title = "space") +
  geom_text(aes(y = rev(Index), x = 1, label = sprintf("%0.1f", round(Mean_Ratio, digits = 4))), size = 4) + ## decimal places
  ggtitle("Odds Ratio")

## 95% CI table
tab2 <- table_base +
  geom_text(aes(y = rev(Index), x = 1, label = CI), size = 4) + 
  ggtitle("95% CI")

## p value 
tab3 <- table_base +
  geom_text(aes(y = rev(Index), x = 1, label = p_value), size = 4) + 
  ggtitle("p value")


#lay <-  matrix(c(1,1,1,1,1,1,1,1,1,1,2,3,3), nrow = 1)
#grid.arrange(plot1, tab1, tab2, layout_matrix = lay)


lay <-  matrix(c(1,1,1,1,1,1,1,1,1,1,2,3,3), nrow = 1)
grid.arrange(plot1, tab1, tab2, layout_matrix = lay)
```



```{r, echo=F, message=F, warning=F, eval=F}
glm_fit=glm(as.factor(Ext)~as.factor(Upper.TSALD.group)+Lower.TSALD, data = sub_data, family = "binomial") # response variable need to be factor 
cbind(exp(cbind(OR = coef(glm_fit), confint(glm_fit))), p_value=coef(summary(glm_fit))[,4])


```



## v2:




```{r, echo=F, message=F, warning=F}
sub_data=data%>%select(Ext, Upper.TSALD, Lower.TSALD, Skeletal.AP, Upper.lip...E.line, Lower.lip...E.line, Age, Sex) %>% filter(Ext==0 | Ext==1) %>% filter(Lower.TSALD!="N/A") %>% filter(Upper.lip...E.line!="N/A" & Lower.lip...E.line!="N/A" & Skeletal.AP!="N/A") %>% drop_na()
sub_data %>% datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
####### be careful about filter for RACE 
```



```{r, echo=F, message=F, warning=F}
colnames(sub_data)[5:6]=c("Upper_lip", "Lower_lip")
HISP=as.character()
sub_data$Lower.TSALD=as.numeric(sub_data$Lower.TSALD)
sub_data$Upper_lip=as.numeric(sub_data$Upper_lip)
sub_data$Lower_lip=as.numeric(sub_data$Lower_lip)

glm_fit=glm(as.factor(Ext)~Upper.TSALD+Lower.TSALD+Skeletal.AP+Upper_lip+Lower_lip+Age+Sex, data = sub_data, family = "binomial") # response variable need to be factor 
cbind(exp(cbind(OR = coef(glm_fit), confint(glm_fit))), p_value=coef(summary(glm_fit))[,4])



############### visualize odds ratio # https://rpubs.com/mbounthavong/forest_plots_r 
no_cova=8
dat=data.frame( 
  Index=seq(1,no_cova),
  label=c("Upper.TSALD", "Lower.TSALD", "Skeletal.APClass II", "Skeletal.APClass III", "Upper_lip", "Lower_lip", "Age", "Sex"),
  Mean_Ratio=exp(round(coef(glm_fit)[2:(1+no_cova)],4)),
  #Mean_Ratio=c("1.12(0)", "1.02(0.004)", "0.84(0)", "0.95(0)", "1.08(0)", "1.25(0)", "0.94(0.001)", "1.20(0)"),
  LL=exp(round(confint(glm_fit)[2:(1+no_cova),1],2)),
  UL=exp(round(confint(glm_fit)[2:(1+no_cova),2],2)),
  CI=c("0.673, 0.925", "0.630, 0.867", "0.602, 5.715", "0.649, 15.782", "0.864, 1.306", "0.964, 1.417", "0.986, 1.116", "0.323, 2.244"),
  p_value=round(coef(summary(glm_fit))[2:(1+no_cova),4],3)
)

plot1 <- ggplot(dat, aes(y = Index, x = Mean_Ratio)) +
  geom_point(shape = 18, size = 3) +  
  geom_errorbarh(aes(xmin = LL, xmax = UL), height = 0.25) +
  geom_vline(xintercept = 1, color = "red", linetype = "dashed", cex = 1, alpha = 0.5) +
  scale_y_continuous(name = "", breaks=1:no_cova, labels = dat$label, trans = "reverse") +
  xlab("Odds Ratio (95% CI)") + 
  ylab(" ") + 
  theme_bw() +
  theme(panel.border = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text.y = element_text(size = 12, colour = "black"),
        axis.text.x.bottom = element_text(size = 12, colour = "black"),
        axis.title.x = element_text(size = 12, colour = "black"))

## Create the table-base pallete
table_base <- ggplot(dat, aes(y=label)) +
  ylab(NULL) + xlab("  ") + 
  theme(plot.title = element_text(hjust = 0.5, size=12), 
        axis.text.x = element_text(color="white", hjust = -3, size = 25), ## This is used to help with alignment
        axis.line = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks = element_blank(),
        axis.title.y = element_blank(), 
        legend.position = "none",
        panel.background = element_blank(), 
        panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        plot.background = element_blank())

## OR point estimate table
tab1 <- table_base + 
  labs(title = "space") +
  geom_text(aes(y = rev(Index), x = 1, label = sprintf("%0.001f", round(Mean_Ratio, digits = 4))), size = 4) + ## decimal places
  ggtitle("Odds Ratio")

## 95% CI table
tab2 <- table_base +
  geom_text(aes(y = rev(Index), x = 1, label = CI), size = 4) + 
  ggtitle("95% CI")

## p value 
tab3 <- table_base +
  geom_text(aes(y = rev(Index), x = 1, label = p_value), size = 4) + 
  ggtitle("p value")


#lay <-  matrix(c(1,1,1,1,1,1,1,1,1,1,2,3,3), nrow = 1)
#grid.arrange(plot1, tab1, tab2, layout_matrix = lay)


lay <-  matrix(c(1,1,1,1,1,1,1,1,1,1,2,3,3), nrow = 1)
grid.arrange(plot1, tab1, tab2, layout_matrix = lay)

#######################
cor(sub_data[,c(2,3,5,6)])

```


## v3: Extraction, Upper TSALD, Lower TSALD, and others 


```{r, echo=F, message=F, warning=F}
sub_data=data%>%select(Ext, Upper.TSALD, Lower.TSALD, Skeletal.AP, Upper.lip...E.line, Lower.lip...E.line, Age, Sex, RACE) %>% filter(Ext==0 | Ext==1) %>% filter(Lower.TSALD!="N/A") %>% filter(RACE=="HISP  " | RACE=="AFRAM " |  RACE=="CAUC  " |  RACE=="OTHER " |  RACE=="UNKN  " |  RACE=="ASIAN ") %>% filter(Upper.lip...E.line!="N/A" & Lower.lip...E.line!="N/A" & Skeletal.AP!="N/A") %>% drop_na()
sub_data %>% datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
####### be careful about filter for RACE 
```


```{r, echo=F, message=F, warning=F}
colnames(sub_data)[5:6]=c("Upper_lip", "Lower_lip")
HISP=as.character()
HISP[which(sub_data$RACE=="HISP  ")]="Yes"; HISP[which(sub_data$RACE!="HISP  ")]="No"
sub_data=sub_data%>% mutate(HISP=HISP)
sub_data$Lower.TSALD=as.numeric(sub_data$Lower.TSALD)
sub_data$Upper_lip=as.numeric(sub_data$Upper_lip)
sub_data$Lower_lip=as.numeric(sub_data$Lower_lip)

glm_fit=glm(as.factor(Ext)~Upper.TSALD+Lower.TSALD+Skeletal.AP+Upper_lip+Lower_lip+Age+Sex+HISP, data = sub_data, family = "binomial") # response variable need to be factor 
cbind(exp(cbind(OR = coef(glm_fit), confint(glm_fit))), p_value=coef(summary(glm_fit))[,4])



############### visualize odds ratio # https://rpubs.com/mbounthavong/forest_plots_r 
no_cova=9
dat=data.frame( 
  Index=seq(1,no_cova),
  label=c("Upper.TSALD", "Lower.TSALD", "Skeletal.APClass II", "Skeletal.APClass III", "Upper_lip", "Lower_lip", "Age", "Sex", "HISPYes"),
  Mean_Ratio=exp(round(coef(glm_fit)[2:(1+no_cova)],4)),
  #Mean_Ratio=c("1.12(0)", "1.02(0.004)", "0.84(0)", "0.95(0)", "1.08(0)", "1.25(0)", "0.94(0.001)", "1.20(0)"),
  LL=exp(round(confint(glm_fit)[2:(1+no_cova),1],2)),
  UL=exp(round(confint(glm_fit)[2:(1+no_cova),2],2)),
  CI=c("0.673, 0.925", "0.630, 0.867", "0.602, 5.715", "0.649, 15.782", "0.864, 1.306", "0.964, 1.417", "0.986, 1.116", "0.323, 2.244", "0.254, 1.865"),
  p_value=round(coef(summary(glm_fit))[2:(1+no_cova),4],3)
)

plot1 <- ggplot(dat, aes(y = Index, x = Mean_Ratio)) +
  geom_point(shape = 18, size = 3) +  
  geom_errorbarh(aes(xmin = LL, xmax = UL), height = 0.25) +
  geom_vline(xintercept = 1, color = "red", linetype = "dashed", cex = 1, alpha = 0.5) +
  scale_y_continuous(name = "", breaks=1:no_cova, labels = dat$label, trans = "reverse") +
  xlab("Odds Ratio (95% CI)") + 
  ylab(" ") + 
  theme_bw() +
  theme(panel.border = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text.y = element_text(size = 12, colour = "black"),
        axis.text.x.bottom = element_text(size = 12, colour = "black"),
        axis.title.x = element_text(size = 12, colour = "black"))

## Create the table-base pallete
table_base <- ggplot(dat, aes(y=label)) +
  ylab(NULL) + xlab("  ") + 
  theme(plot.title = element_text(hjust = 0.5, size=12), 
        axis.text.x = element_text(color="white", hjust = -3, size = 25), ## This is used to help with alignment
        axis.line = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks = element_blank(),
        axis.title.y = element_blank(), 
        legend.position = "none",
        panel.background = element_blank(), 
        panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        plot.background = element_blank())

## OR point estimate table
tab1 <- table_base + 
  labs(title = "space") +
  geom_text(aes(y = rev(Index), x = 1, label = sprintf("%0.001f", round(Mean_Ratio, digits = 4))), size = 4) + ## decimal places
  ggtitle("Odds Ratio")

## 95% CI table
tab2 <- table_base +
  geom_text(aes(y = rev(Index), x = 1, label = CI), size = 4) + 
  ggtitle("95% CI")

## p value 
tab3 <- table_base +
  geom_text(aes(y = rev(Index), x = 1, label = p_value), size = 4) + 
  ggtitle("p value")


#lay <-  matrix(c(1,1,1,1,1,1,1,1,1,1,2,3,3), nrow = 1)
#grid.arrange(plot1, tab1, tab2, layout_matrix = lay)


lay <-  matrix(c(1,1,1,1,1,1,1,1,1,1,2,3,3), nrow = 1)
grid.arrange(plot1, tab1, tab2, layout_matrix = lay)

#######################
cor(sub_data[,c(2,3,5,6)])

```


## descriptive analysis 


### raw data 

```{r, echo=F, message=F, warning=F, eval=T}
###########
g1=ggplot(data_raw %>% dplyr::count(Extraction) %>%mutate(prop=n/nrow(data)), aes(x=Extraction, y=n, fill=as.character(Extraction))) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)+  # add numbers over bars
  ggtitle("")+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title 
#########
g2=ggplot(data, aes(x=Age)) + 
  geom_histogram(color="blue", fill="blue")+
  geom_vline(aes(xintercept=mean(Age)),
            color="red", linetype="dashed", size=1)

###########
g3=ggplot(data_raw %>% dplyr::count(Sex) %>%mutate(prop=n/nrow(data)), aes(x=Sex, y=n, fill=as.character(Sex))) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=15))+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)+  # add numbers over bars
  ggtitle("")+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title 

###########
g4=ggplot(data_raw %>% dplyr::count(CustomCode1) %>%mutate(prop=n/nrow(data)), aes(x=CustomCode1, y=n, fill=as.character(CustomCode1))) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)+  # add numbers over bars
  ggtitle("")+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title 


#figure=ggarrange(g1, g2, g3, g4, nrow=2)
#figure
g1
g2
g3
g4
```

### data without missing values 


```{r, echo=F, message=F, warning=F, eval=T}
data1=data_raw%>%select(Extraction, Age, Sex,CustomCode1, Problem.List...Skeletal...Vertical, Model.Analysis...Maxillary.TSALD.in.mm, Model.Analysis...Mandibular.TSALD.in.mm, Problem.List...Soft.Tissues...A.P.Upper.lip.to.E.line, Problem.List...Soft.Tissues...A.P.Lower.lip.to.E.line) %>% drop_na() %>% filter(Extraction==0 | Extraction==1) %>% filter(Sex==1 | Sex==2) %>% filter(CustomCode1!="      ") %>% filter(Problem.List...Skeletal...Vertical!="N/A" & Model.Analysis...Maxillary.TSALD.in.mm!="N/A" & Model.Analysis...Mandibular.TSALD.in.mm!="N/A" & Problem.List...Soft.Tissues...A.P.Upper.lip.to.E.line!="N/A" & Problem.List...Soft.Tissues...A.P.Lower.lip.to.E.line!="N/A")
data1 %>% datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```




```{r, echo=F, message=F, warning=F, eval=T}
###########
ggplot(data1 %>% dplyr::count(Extraction), aes(x=Extraction, y=n, fill=as.character(Extraction))) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)+  # add numbers over bars
  ggtitle("")+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title 
#########
p<-ggplot(data1, aes(x=Age)) + 
  geom_histogram(color="blue", fill="blue")
p+geom_vline(aes(xintercept=mean(Age)),
            color="red", linetype="dashed", size=1)

###########
ggplot(data1 %>% dplyr::count(Sex), aes(x=Sex, y=n, fill=as.character(Sex))) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=15))+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)+  # add numbers over bars
  ggtitle("")+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title 

###########
ggplot(data1 %>% dplyr::count(CustomCode1), aes(x=CustomCode1, y=n, fill=as.character(CustomCode1))) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)+  # add numbers over bars
  ggtitle("")+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title 

```



## logistic regression 



```{r, echo=F, message=F, warning=F, eval=T}
glm_fit=glm(as.factor(Extraction)~Age+ Sex, data = data_raw, family = "binomial") # response variable need to be factor 
cbind(exp(cbind(OR = coef(glm_fit), confint(glm_fit))), p_value=coef(summary(glm_fit))[,4])
```

* covariate group with smallest number as the reference group. 

```{r, echo=F, message=F, warning=F,eval=F}
glm_fit=glm(as.factor(Extraction)~Age+ Sex+Problem.List...Skeletal...AP+Model.Analysis...Maxillary.TSALD.in.mm, data = data, family = "binomial") # response variable need to be factor 
cbind(exp(cbind(OR = coef(glm_fit), confint(glm_fit))), p_value=coef(summary(glm_fit))[,4])
```

