---
title: "10/4/2022"
output: html_document
date: '2022-10-04'
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
library(ggpubr)
library(rstatix) # use anova_test function 
library(DT)
set.seed(123)
```


```{r, echo=F, warning=F, message=F}
pvalue_adjust=function(p_value)
{
  p_value_adjust=numeric()
for (i in 1:length(p_value))
{
  if (is.na(p_value[i])==T)
    p_value_adjust[i]=p_value[i]
  if (is.na(p_value[i])==F & p_value[i]<0.0001)
    p_value_adjust[i]="<0.0001"
  if (is.na(p_value[i])==F & p_value[i]>0.0001)
    p_value_adjust[i]=round(p_value[i],4)
}
  return(p_value_adjust)
}
```


```{r, echo=F, message=F, warning=F}
Grades_Results_old=as_tibble(read.csv("C:\\Shengtong\\Research\\AllCollaboration\\2022\\202209\\Chloe\\Grades - Results .csv", header=T)[,-5])
Grades_Results=as_tibble(read.csv("C:\\Shengtong\\Research\\AllCollaboration\\2022\\202209\\Chloe\\GRADES 3456.csv", header=T))
```

## grades-pairwise comparisons 


```{r, echo=F, message=F, warning=F}
music_type=colnames(Grades_Results)[2:5]
control=Grades_Results %>% select(music_type[1])%>%pull %>% as.numeric()
classical=Grades_Results %>% select(music_type[2])%>%pull %>% as.numeric()
hip_hop=Grades_Results %>% select(music_type[3])%>%pull %>% as.numeric()
student_playlist=Grades_Results %>% select(music_type[4])%>%pull %>% as.numeric()


pvalue=numeric();CI_low=numeric(); CI_upper=numeric(); mean_difference=numeric()
t_test=t.test(classical, control, paired=T)
pvalue[1]=t_test$p.value
CI_low[1]=t_test$conf.int[1]
CI_upper[1]=t_test$conf.int[2]
mean_difference[1]=t_test$estimate


t_test=t.test(hip_hop, control, paired=T)
pvalue[2]=t_test$p.value
CI_low[2]=t_test$conf.int[1]
CI_upper[2]=t_test$conf.int[2]
mean_difference[2]=t_test$estimate


t_test=t.test(student_playlist, control, paired=T)
pvalue[3]=t_test$p.value
CI_low[3]=t_test$conf.int[1]
CI_upper[3]=t_test$conf.int[2]
mean_difference[3]=t_test$estimate

data.frame(group1=c("classical", "hip hop", "student playlist"), group2=c("control-no music", "---", "---"), mean_difference=round(mean_difference,4),  CI_low=round(CI_low,4),  CI_upper=round(CI_upper,4), p_value= pvalue_adjust(pvalue))%>%
datatable(extensions = 'Buttons',
          caption="music type vs control",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```


* use paired two sample t tests 



```{r, echo=F, message=F, warning=F}


pvalue=numeric();CI_low=numeric(); CI_upper=numeric(); mean_difference=numeric()
t_test=t.test(classical, hip_hop, paired=T)
pvalue[1]=t_test$p.value
CI_low[1]=t_test$conf.int[1]
CI_upper[1]=t_test$conf.int[2]
mean_difference[1]=t_test$estimate


t_test=t.test(classical, student_playlist, paired=T)
pvalue[2]=t_test$p.value
CI_low[2]=t_test$conf.int[1]
CI_upper[2]=t_test$conf.int[2]
mean_difference[2]=t_test$estimate


t_test=t.test(hip_hop, student_playlist, paired=T)
pvalue[3]=t_test$p.value
CI_low[3]=t_test$conf.int[1]
CI_upper[3]=t_test$conf.int[2]
mean_difference[3]=t_test$estimate

data.frame(group1=c("classical", "classical", "hip hop"), group2=c("hip hop", "student playlist", "student playlist"), mean_difference=round(mean_difference,4),  CI_low=round(CI_low,4),  CI_upper=round(CI_upper,4), p_value= pvalue_adjust(pvalue))%>%
datatable(extensions = 'Buttons',
          caption="comaprison among music types",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```


## Questionnaire given after each of the 4 sessions were completed  


```{r, echo=F, message=F, warning=F}
no_music=as_tibble(read.csv("C:\\Shengtong\\Research\\AllCollaboration\\2022\\202209\\Chloe\\No Music (Control).csv", header=T))
questions=colnames(no_music)[6:9]

no_music_plot1=no_music %>% count(by=How.did.2t.having.music.impact.your.energy.level.during.class.)%>% mutate(prop=n/nrow(no_music))
no_music_plot2=no_music %>% count(by=How.easy.was.it.to.focus.during.class.periods.without.music.)%>% mutate(prop=n/nrow(no_music))
no_music_plot3=no_music %>% count(by=How.did.2t.having.music.played.during.previous.sessions.impact.your.concentration.when.performing.root.canal.treatments.of..9.and.or..4.)%>% mutate(prop=n/nrow(no_music))
no_music_plot4=no_music %>% count(by=Did.2t.having.music.played.interfere.with.your.ability.to.complete.the.root.canal.treatment.on..9.and.or..4.)%>% mutate(prop=n/nrow(no_music))

```

```{r, echo=F, message=F, warning=F, eval=T}
################### question 1
no_music_plot=no_music %>% count(by=How.did.2t.having.music.impact.your.energy.level.during.class.)%>% mutate(prop=n/nrow(no_music))

g1=ggplot(no_music_plot, aes(x=by, y=prop, fill=as.character(by))) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(no_music_plot, aes(x=by, y=n, fill=as.character(by))) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("count")+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars
questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="right") 
annotate_figure(figure,
                top = text_grob("", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)
```

```{r, echo=F, message=F, warning=F, eval=T}

################### question 2
no_music_plot2=no_music %>% count(by=How.easy.was.it.to.focus.during.class.periods.without.music.)%>% mutate(prop=n/nrow(no_music))
g1=ggplot(no_music_plot, aes(x=by, y=prop, fill=as.character(by))) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(no_music_plot, aes(x=by, y=n, fill=as.character(by))) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("count")+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars
questions[2]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="right") 
annotate_figure(figure,
                top = text_grob("", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)
```


```{r, echo=F, message=F, warning=F}
################### question 3
no_music_plot3=no_music %>% count(by=How.did.2t.having.music.played.during.previous.sessions.impact.your.concentration.when.performing.root.canal.treatments.of..9.and.or..4.)%>% mutate(prop=n/nrow(no_music))
g1=ggplot(no_music_plot, aes(x=by, y=prop, fill=as.character(by))) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(no_music_plot, aes(x=by, y=n, fill=as.character(by))) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("count")+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars
questions[3]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="right") 
annotate_figure(figure,
                top = text_grob("", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)
```

```{r, echo=F, message=F, warning=F}
################### question 4
no_music_plot4=no_music %>% count(by=Did.2t.having.music.played.interfere.with.your.ability.to.complete.the.root.canal.treatment.on..9.and.or..4.)%>% mutate(prop=n/nrow(no_music))
g1=ggplot(no_music_plot, aes(x=by, y=prop, fill=as.character(by))) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(no_music_plot, aes(x=by, y=n, fill=as.character(by))) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("count")+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars

questions[4]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="right") 
annotate_figure(figure,
                top = text_grob(questions[4], color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

```


```{r, echo=F, message=F, warning=F}
classical_music=as_tibble(read.csv("C:\\Shengtong\\Research\\AllCollaboration\\2022\\202209\\Chloe\\Variable1-Classical Music.csv", header=T))
#questions=colnames(classical_music)[6:9]
questions=c("How did the music impact your energy level during class?", "How easy was it to focus during this class period?", "How did the music played during today’s session impact your concentration when performing root canal treatments of #9 and/or #4?", "Did the music selection today interfere with your ability to complete the root canal treatment on #9 and/or #4?")
################### question 1
classical_music_plot1=classical_music %>% count(by=Q1)%>% mutate(prop=n/nrow(classical_music))
################### question 2
classical_music_plot2=classical_music %>% count(by=Q2)%>% mutate(prop=n/nrow(classical_music))
################### question 3
classical_music_plot3=classical_music %>% count(by=Q3)%>% mutate(prop=n/nrow(classical_music))

################### question 4
classical_music_plot4=classical_music %>% count(by=Q4)%>% mutate(prop=n/nrow(classical_music))


```




```{r, echo=F, message=F, warning=F}
hip_hop_music=as_tibble(read.csv("C:\\Shengtong\\Research\\AllCollaboration\\2022\\202209\\Chloe\\Variable 2 - Hip-hop.csv", header=T))
#questions=colnames(hip_hop_music)[6:9]
questions=c("How did the music impact your energy level during class?", "How easy was it to focus during this class period?
",  "How did the music played during today’s session impact your concentration when performing root canal treatments of #9 and/or #4?", "Did the music selection today interfere with your ability to complete the root canal treatment on #9 and/or #4?")
################### question 1
hip_hop_music_plot1=hip_hop_music %>% count(by=Q1)%>% mutate(prop=n/nrow(no_music))
################### question 2
hip_hop_music_plot2=hip_hop_music %>% count(by=Q2)%>% mutate(prop=n/nrow(hip_hop_music))  # should add one row 
hip_hop_music_plot2=hip_hop_music_plot2 %>%add_row(by= 4, n= 0, prop=0)
################### question 3
hip_hop_music_plot3=hip_hop_music %>% count(by=Q3)%>% mutate(prop=n/nrow(hip_hop_music))

################### question 4
hip_hop_music_plot4=hip_hop_music %>% count(by=Q4)%>% mutate(prop=n/nrow(hip_hop_music))

########################
```



```{r, echo=F, message=F, warning=F}
student_playlist_music=as_tibble(read.csv("C:\\Shengtong\\Research\\AllCollaboration\\2022\\202209\\Chloe\\Variable 3 - Student Playlist.csv", header=T))
#questions=colnames(student_playlist_music)[6:9]
questions=c("How did the music impact your energy level during class?
", "How easy was it to focus during this class period?", "How.did.the.music.played.during.today.s.session.impact.your.concentration.when.performing.root.canal.treatments.of..9.and.or..4.", "Did.the.music.selection.today.interfere.with.your.ability.to.complete.the.root.canal.treatment.on..9.and.or..4.")
################### question 1
student_playlist_music_plot1=hip_hop_music %>% count(by=Q1)%>% mutate(prop=n/nrow(no_music))
################### question 2
student_playlist_music_plot2=student_playlist_music %>% count(by=Q2)%>% mutate(prop=n/nrow(hip_hop_music))  # should add one row 
student_playlist_music_plot2=student_playlist_music_plot2 %>%add_row(by= 4, n= 0, prop=0)
################### question 3
student_playlist_music_plot3=student_playlist_music %>% count(by=Q3)%>% mutate(prop=n/nrow(hip_hop_music))

################### question 4
student_playlist_music_plot4=student_playlist_music %>% count(by=Q4)%>% mutate(prop=n/nrow(hip_hop_music))

########################
```


```{r, echo=F, message=F, warning=F}
# combine all questions 
combine=data.frame(response=c(no_music_plot1$by, no_music_plot2$by, no_music_plot3$by, no_music_plot4$by, classical_music_plot1$by, classical_music_plot2$by, classical_music_plot3$by, classical_music_plot4$by, hip_hop_music_plot1$by,hip_hop_music_plot2$by, hip_hop_music_plot3$by, hip_hop_music_plot4$by, student_playlist_music_plot1$by,student_playlist_music_plot2$by, student_playlist_music_plot3$by, student_playlist_music_plot4$by), 
                   question=rep(c(rep("Q1", nrow(no_music_plot1)), rep("Q2", nrow(no_music_plot2)), rep("Q3", nrow(no_music_plot3)), rep("Q4", nrow(no_music_plot4))), 4), music_type=rep(c("no_music", "classical music", "hip hop", "student playlist"), each=12), 
                   count=c(no_music_plot1$n, no_music_plot2$n, no_music_plot3$n, no_music_plot4$n, classical_music_plot1$n, classical_music_plot2$n, classical_music_plot3$n, classical_music_plot4$n, hip_hop_music_plot1$n,hip_hop_music_plot2$n, hip_hop_music_plot3$n, hip_hop_music_plot4$n, student_playlist_music_plot1$n,student_playlist_music_plot2$n, student_playlist_music_plot3$n, student_playlist_music_plot4$n), 
                   prop=c(no_music_plot1$prop, no_music_plot2$prop, no_music_plot3$prop, no_music_plot4$prop, classical_music_plot1$prop, classical_music_plot2$prop, classical_music_plot3$prop, classical_music_plot4$prop, hip_hop_music_plot1$prop,hip_hop_music_plot2$prop, hip_hop_music_plot3$prop, hip_hop_music_plot4$prop, student_playlist_music_plot1$prop,student_playlist_music_plot2$prop, student_playlist_music_plot3$prop, student_playlist_music_plot4$prop))
```

```{r, echo=F, message=F, warning=F}
g1=ggplot(combine %>% filter(question=="Q1"), aes(x=as.character(response), y=count, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("count")+
   ylim(c(0,110))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=count), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
  theme(legend.title=element_blank())+
 facet_wrap(~music_type)

g2=ggplot(combine %>% filter(question=="Q1"), aes(x=as.character(response), y=prop, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("proportion (%)")+
   ylim(c(0,1))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=round(prop,3)*100), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
  guides(color = guide_legend(title = "Response"))+
 facet_wrap(~music_type)

figure=ggarrange(g1, g2, common.legend = TRUE, legend="right") 
annotate_figure(figure,
                top = text_grob("Q1", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Datasource: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)


```

```
1.	How did not having music impact your energy level during class?
 a.	It kept my energy level up and refreshed.
 b.	It did not impact my energy level.
 c.	It drained and ran down my energy level.

```


```{r, echo=F, message=F, warning=F}
g1=ggplot(combine %>% filter(question=="Q2"), aes(x=as.character(response), y=count, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("count")+
   ylim(c(0,110))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=count), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
  theme(legend.title=element_blank())+
 facet_wrap(~music_type)
g2=ggplot(combine %>% filter(question=="Q2"), aes(x=as.character(response), y=prop, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("proportion (%)")+
   ylim(c(0,1))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=round(prop,3)*100), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
 facet_wrap(~music_type)

figure=ggarrange(g1, g2, common.legend = TRUE, legend="right") 
annotate_figure(figure,
                top = text_grob("Q2", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Datasource: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)


```

```
2.	How easy was it to focus during class periods without music?
a.	Very easy 
b.	Somewhat easy 
c.	Somewhat difficult 
d.	Very difficult 


```



```{r, echo=F, message=F, warning=F}
g1=ggplot(combine %>% filter(question=="Q3"), aes(x=as.character(response), y=count, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("count")+
   ylim(c(0,110))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=count), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
  theme(legend.title=element_blank())+
 facet_wrap(~music_type)
g2=ggplot(combine %>% filter(question=="Q3"), aes(x=as.character(response), y=prop, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("proportion (%)")+
   ylim(c(0,1))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=round(prop,3)*100), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
 facet_wrap(~music_type)

figure=ggarrange(g1, g2, common.legend = TRUE, legend="right") 
annotate_figure(figure,
                top = text_grob("Q3", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Datasource: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)


```

```
3.	How did not having music played during today’s session impact your concentration when performing root canal treatments of #9 and/or #4?	
a.	The music increased my concentration in class.
b.	The music neither increased nor decreased my concentration in class.
c.	The music decreased my concentration in class.

```




```{r, echo=F, message=F, warning=F}
g1=ggplot(combine %>% filter(question=="Q4"), aes(x=as.character(response), y=count, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("count")+
   ylim(c(0,110))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=count), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
  theme(legend.title=element_blank())+
 facet_wrap(~music_type)
g2=ggplot(combine %>% filter(question=="Q4"), aes(x=as.character(response), y=prop, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("proportion (%)")+
   ylim(c(0,1))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=round(prop,3)*100), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
 facet_wrap(~music_type)

figure=ggarrange(g1, g2, common.legend = TRUE, legend="right") 
annotate_figure(figure,
                top = text_grob("Q4"
, color = "red", face = "bold", size = 14),
#                bottom = text_grob("Datasource: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)


```

```
4.	Did not having music today interfere with your ability to complete the root canal treatment on #9 and/or #4?
a.	Yes 
b.	No 


```


## Questionnaire given after 4 sessions have been completed (no music, classical, hip-hop, and student’s compilation)

```{r, echo=F, message=F, warning=F}
final_overall_survey=as_tibble(read.csv("C:\\Shengtong\\Research\\AllCollaboration\\2022\\202209\\Chloe\\Final - overall survey.csv", header=T))
```

### Q1 

```{r, echo=F, message=F, warning=F}
Q1=data.frame(count=final_overall_survey$Which.class.period.did.you.like.the.best.) %>% count(response=count) %>% mutate(prop=n/103)
Q1=Q1%>%add_row(response= 1, n= 0, prop=0)

g1=ggplot(Q1, aes(x=as.character(response), y=n, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("count")+
   ylim(c(0,110))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=n), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
  theme(legend.title=element_blank())

g2=ggplot(Q1, aes(x=as.character(response), y=prop, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("proportion (%)")+
   ylim(c(0,1))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=round(prop,3)*100), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title

figure=ggarrange(g1, g2, common.legend = TRUE, legend="right")
annotate_figure(figure,
                top = text_grob("Q1"
, color = "red", face = "bold", size = 14),
#                bottom = text_grob("Datasource: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)
```



```
1.	Which class period did you like the best?
a.	When no music was played
b.	When hip-hop music was played
c.	When classical music was played
d.	When our class’s compilation playlist was played.

```


### Q2 



```{r, echo=F, message=F, warning=F}
Q2=data.frame(count=final_overall_survey$During.which.class.period.were.you.able.to.concentrate.the.most.) %>% count(response=count) %>% mutate(prop=n/103)


g1=ggplot(Q2, aes(x=as.character(response), y=n, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("count")+
   ylim(c(0,110))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=n), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
  theme(legend.title=element_blank())

g2=ggplot(Q2, aes(x=as.character(response), y=prop, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("proportion (%)")+
   ylim(c(0,1))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=round(prop,3)*100), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title

figure=ggarrange(g1, g2, common.legend = TRUE, legend="right")
annotate_figure(figure,
                top = text_grob("Q2"
, color = "red", face = "bold", size = 14),
#                bottom = text_grob("Datasource: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)
```

```
2.	During which class period were you able to concentrate the most?
a.	When no music was played
b.	When hip-hop music was played
c.	When classical music was played
d.	When our class’s compilation playlist was played

```

### Q3



```{r, echo=F, message=F, warning=F}
Q3=data.frame(count=final_overall_survey$Were.you.distracted.due.to.the.music.played.during.a.class.period..If.so..which.one.) %>% count(response=count) %>% mutate(prop=n/103)


g1=ggplot(Q3, aes(x=as.character(response), y=n, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("count")+
   ylim(c(0,110))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=n), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
  theme(legend.title=element_blank())

g2=ggplot(Q3, aes(x=as.character(response), y=prop, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("proportion (%)")+
   ylim(c(0,1))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=round(prop,3)*100), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title

figure=ggarrange(g1, g2, common.legend = TRUE, legend="right")
annotate_figure(figure,
                top = text_grob("Q3"
, color = "red", face = "bold", size = 14),
#                bottom = text_grob("Datasource: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)
```


```
3.	Were you distracted due to the music played during a class period? If so, which one?
a.	No I was not distracted in any of the sessions when music played.
b.	Yes I was distracted in the session when hip-hop music played. 
c.	Yes I was distracted in the session when classical music played.
d.	Yes I was distracted in the session when the class’s playlist was played. 

```

### Q4



```{r, echo=F, message=F, warning=F}
Q4=data.frame(count=final_overall_survey$Would.you.like.music.to.be.played.during.the.final.exam.competencies.) %>% count(response=count) %>% mutate(prop=n/103)


g1=ggplot(Q4, aes(x=as.character(response), y=n, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("count")+
   ylim(c(0,110))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=n), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
  theme(legend.title=element_blank())

g2=ggplot(Q4, aes(x=as.character(response), y=prop, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("proportion (%)")+
   ylim(c(0,1))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=round(prop,3)*100), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title

figure=ggarrange(g1, g2, common.legend = TRUE, legend="right")
annotate_figure(figure,
                top = text_grob("Q4"
, color = "red", face = "bold", size = 14),
#                bottom = text_grob("Datasource: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)
```

```
4.	Would you like music to be played during the final exam competencies?
a.	Yes 
b.	No 

```


### Q5



```{r, echo=F, message=F, warning=F}
Q5=data.frame(count=final_overall_survey$If.you.would.like.music.to.be.played.during.the.final.exam.competencies..what.genre.of.music.would.you.prefer.) %>% count(response=count) %>% mutate(prop=n/103)


g1=ggplot(Q5, aes(x=as.character(response), y=n, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("count")+
   ylim(c(0,110))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=n), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
  theme(legend.title=element_blank())

g2=ggplot(Q5, aes(x=as.character(response), y=prop, fill=as.character(response)))+ 
geom_bar(position = "dodge",stat="identity")+
   xlab("")+ylab("proportion (%)")+
   ylim(c(0,1))+
   theme(axis.text.x = element_text(angle =0, vjust = 0.5, size=8))+
  # ggtitle("Response of Q1")+
   geom_text(aes(label=round(prop,3)*100), position=position_dodge(width=0.9), vjust=-0.25)+  # add numbers over bars 
   theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title

figure=ggarrange(g1, g2, common.legend = TRUE, legend="right")
annotate_figure(figure,
                top = text_grob("Q5"
, color = "red", face = "bold", size = 14),
#                bottom = text_grob("Datasource: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)
```

```
5.	If you would like music to be played during the final exam competencies, what genera of music would you prefer?
a.	Hip-hop 
b.	Classical 
c.	Student’s compilation playlist 

```