---
title: "9/28/2022"
output: html_document
date: '2022-09-28'
---


```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
library(ggpubr)
library(rstatix) # use anova_test function 
library(DT)
set.seed(123)
```

## mean and standard deviation

```{r, echo=F, message=F, warning=F}
data=as_tibble(read.csv("C:\\Shengtong\\Research\\AllCollaboration\\2022\\202209\\Vidya\\Vidya-saline stats.csv", header = T))
brands=unique(data$File)
mean_OCP=numeric(); SD_Icorr=numeric()
mean_Icorr=numeric(); SD_OCP=numeric()
for (i in 1:length(brands))
{
  sub_data=data %>% filter(File==brands[i])
  mean_OCP[i]=sub_data%>%summarise(mean=mean(OCP..mV..1.hr))%>% pull()
  SD_OCP[i]=sub_data%>%summarise(SD=sd(OCP..mV..1.hr)) %>% pull()
  
  mean_Icorr[i]=sub_data%>%summarise(mean=mean(Icorr..nA.))%>% pull()
  SD_Icorr[i]=sub_data%>%summarise(SD=sd(Icorr..nA.))%>% pull()
}

data.frame(File=brands, mean_OCP=round(mean_OCP,4),  SD_OCP=round(SD_OCP,4), mean_Icorr=round(mean_Icorr,4),  SD_Icorr=round(SD_Icorr,4))%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

#%>%
#  kbl() %>%
#  kable_styling()%>%
#scroll_box(height = "300px")
```


## pairwise comparisons 


### OCP 


```{r, echo=F, message=F, warning=F}
p_value=numeric(); mean_difference=numeric(); CI_lower=numeric(); CI_upper=numeric()
ii=0
brands=unique(data$File)
for (i in 1:length(brands))
 for (j in 1:length(brands))  
{
   ii=ii+1
  group1=data %>% filter(File==brands[i])%>% select(OCP..mV..1.hr) %>% pull
  group2=data %>% filter(File==brands[j])%>% select(OCP..mV..1.hr) %>% pull
  
  test=t.test(group1-group2) 
  mean_difference[ii]=test$estimate
  CI_lower[ii]=test$conf.int[1]
  CI_upper[ii]=test$conf.int[2]
  p_value[ii]=test$p.value
 }

result=data_frame(group1=rep(brands,each=10), group2=rep(brands,10), mean_difference=round(mean_difference,2),  CI_lower=round(CI_lower,2),  CI_upper=round(CI_upper,2), p_value=round(p_value,4)) 

result$group1[c(2:10, 12:20, 22:30, 32:40, 42:50)]="---"
result%>%
  kbl() %>%
  kable_styling()%>%
scroll_box(height = "500px")

```



### Icorr 


```{r, echo=F, message=F, warning=F}
p_value=numeric(); mean_difference=numeric(); CI_lower=numeric(); CI_upper=numeric()
ii=0
brands=unique(data$File)
for (i in 1:length(brands))
 for (j in 1:length(brands))  
{
   ii=ii+1
  group1=data %>% filter(File==brands[i])%>% select(Icorr..nA.) %>% pull
  group2=data %>% filter(File==brands[j])%>% select(Icorr..nA.) %>% pull
  
  test=t.test(group1-group2) 
  mean_difference[ii]=test$estimate
  CI_lower[ii]=test$conf.int[1]
  CI_upper[ii]=test$conf.int[2]
  p_value[ii]=test$p.value
 }

result=data_frame(group1=rep(brands,each=10), group2=rep(brands,10), mean_difference=round(mean_difference,2),  CI_lower=round(CI_lower,2),  CI_upper=round(CI_upper,2), p_value=round(p_value,4)) 

result$group1[c(2:10, 12:20, 22:30, 32:40, 42:50)]="---"
result%>%
  kbl() %>%
  kable_styling()%>%
scroll_box(height = "500px")

```