---
title: "10/30/2023"
output: html_document
date: "2023-10-30"
---



```{r setup, include=FALSE}
rm(list=ls())
library(tidyverse)
library(kableExtra)
library(ggpubr)
library(rstatix) # use anova_test function 
library(grid)
library(DT)
library(gridExtra)
library(matrixStats)
library(cowplot)
library(readxl)
set.seed(123)
```




```{r, echo=F, warning=F, message=F}
######## adjust p values 
pvalue_adjust=function(p_value)
{
  p_value_adjust=numeric()
for (i in 1:length(p_value))
{
  if (is.na(p_value[i])==T)
    p_value_adjust[i]=p_value[i]
  if (is.na(p_value[i])==F & p_value[i]<0.0001)
    p_value_adjust[i]="<0.0001"
  if (is.na(p_value[i])==F & p_value[i]>0.0001)
    p_value_adjust[i]=round(p_value[i],4)
}
  return(p_value_adjust)
}
############### summary statistics for continuous variable 
summary_statistics=function(data)
{  # each column is one variable, and row one subject 
  
variables=colnames(data)
num_sample=numeric()
Mean=numeric()
Median=numeric()
SD=numeric()
SE=numeric()
range_min=numeric()
range_max=numeric()
normality_pvalue=numeric()
per_25_quantile=numeric()
per_75_quantile=numeric()

for (i in 1:ncol(data))
{
  observation=data[,i]
  observation=observation[!is.na(observation)] # remove missing values 
  num_sample[i]=length(observation)
  Mean[i]=round(mean(observation),4)
  Median[i]=round(median(observation),4)
  SD[i]=round(sd(observation),4)
  SE[i]=round(SD[i]/sqrt(num_sample[i]),4)
  per_25_quantile[i]=round(quantile(observation, prob=0.25),4)
  per_75_quantile[i]=round(quantile(observation, prob=0.75),4)
  range_min[i]=round(min(observation),4)
  range_max[i]=round(max(observation),4)
  normality_pvalue[i]=round(shapiro.test(observation)$p.value,4)
}

summary_data=data.frame(variable=variables, num_sample=num_sample, Mean=Mean, Median=Median, SD=SD, SE=SE,per_25_quantile, per_75_quantile, Range_low=range_min, Range_upper=range_max, normality_pvalue=normality_pvalue)

summary_data%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
  
 return(summary_data) 
}

multiplesheets <- function(fname) {
   
  # getting info about all excel sheets
  sheets <- readxl::excel_sheets(fname)
  tibble <- lapply(sheets, function(x) readxl::read_excel(fname, sheet = x))
  data_frame <- lapply(tibble, as.data.frame)
    
  # assigning names to data frames
  names(data_frame) <- sheets
    
  # print data frame
  print(data_frame)
}


```




## power analysis for 3-way interaction 

```{r, echo=F, message=F, warning=F, eval=T}
# https://aaroncaldwell.us/SuperpowerBook/the-experimental-design.html
library(Superpower)


# From https://aaroncaldwell.us/SuperpowerBook/power-for-three-way-interactions.html
# With 2x2x2 designs, 
# the names for paired comparisons can become very long. 
# So here I abbreviate terms: 
#   Size, Color, and Cognitive Load, have values:
# b = big, s = small, g = green, 
# r = red, pres = present, abs = absent.  
labelnames <- c("Ceramics", "Feldspathic Porcelain
", "Lithium Disilicate", "Cement", "Resin Cement", "Flowable Composite", 
                "Surface", "Dull/Matt", "Glazed") #
design_result <- ANOVA_design(design = "2b*2b*2b", 
                              #sample size per group 
                              n = 10, 
                              #pattern of means
                              mu = c(15.01,3.96,16.19,6.47,23.57,2.32,35.82,3.63), 
                              sd = 12.59, #standard deviation for all conditions sd(data$ShearBondStrengthinMpa)
                              labelnames = labelnames) 
```

```{r, echo=F, message=F, warning=F}
simulation_result <- ANOVA_power(design_result, 
                                 alpha_level = Superpower_options("alpha_level"), 
                                 nsims = 1000,
                                 verbose = FALSE)
simulation_result


#exact_result <- ANOVA_exact(design_result,
#                            alpha_level = Superpower_options("alpha_level"),
#                            verbose = FALSE)
#exact_result
```




## two level 3 way interaction 


```{r, echo=F, message=F, warning=F, results=F}
data_raw=multiplesheets("C:\\Shengtong\\Research\\AllCollaboration\\2023\\202310\\Zaid\\SBS GC Stat.xlsx")
data=data_raw$Sheet1
```


### 3 way interaction 

```{r, echo=F, message=F, warning=F}
# https://www.statology.org/three-way-anova-in-r/

#perform three-way ANOVA
model <- aov(ShearBondStrengthinMpa~ Ceramic * Cement * Surface, data=data)

#view summary of three-way ANOVA
summary(model)
```