---
title: "07/25/2023"
output: html_document
date: "2023-07-25"
---


```{r setup, include=FALSE}
rm(list=ls())
library(tidyverse)
library(kableExtra)
library(ggpubr)
library(rstatix) # use anova_test function 
library(grid)
library(DT)
library(gridExtra)
library(matrixStats)
library(cowplot)
library(readxl)
set.seed(123)
```




```{r, echo=F, warning=F, message=F}
######## adjust p values 
pvalue_adjust=function(p_value)
{
  p_value_adjust=numeric()
for (i in 1:length(p_value))
{
  if (is.na(p_value[i])==T)
    p_value_adjust[i]=p_value[i]
  if (is.na(p_value[i])==F & p_value[i]<0.0001)
    p_value_adjust[i]="<0.0001"
  if (is.na(p_value[i])==F & p_value[i]>0.0001)
    p_value_adjust[i]=round(p_value[i],4)
}
  return(p_value_adjust)
}
############### summary statistics for continuous variable 
summary_statistics=function(data)
{  # each column is one variable, and row one subject 
  
variables=colnames(data)
num_sample=numeric()
Mean=numeric()
Median=numeric()
SD=numeric()
SE=numeric()
range_min=numeric()
range_max=numeric()
normality_pvalue=numeric()
per_25_quantile=numeric()
per_75_quantile=numeric()

for (i in 1:ncol(data))
{
  observation=data[,i]
  observation=observation[!is.na(observation)] # remove missing values 
  num_sample[i]=length(observation)
  Mean[i]=round(mean(observation),4)
  Median[i]=round(median(observation),4)
  SD[i]=round(sd(observation),4)
  SE[i]=round(SD[i]/sqrt(num_sample[i]),4)
  per_25_quantile[i]=round(quantile(observation, prob=0.25),4)
  per_75_quantile[i]=round(quantile(observation, prob=0.75),4)
  range_min[i]=round(min(observation),4)
  range_max[i]=round(max(observation),4)
  normality_pvalue[i]=round(shapiro.test(observation)$p.value,4)
}

summary_data=data.frame(variable=variables, num_sample=num_sample, Mean=Mean, Median=Median, SD=SD, SE=SE,per_25_quantile, per_75_quantile, Range_low=range_min, Range_upper=range_max, normality_pvalue=normality_pvalue)

summary_data%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
  
 return(summary_data) 
}

```



```{r, echo=F, message=F, warning=F}
data_2021=read_excel("C:\\Shengtong\\Research\\AllCollaboration\\2023\\202307\\Mohamed\\Endo Lab Learning Preference - 2021(1-102).xlsx")
data_2022A=read_excel("C:\\Shengtong\\Research\\AllCollaboration\\2023\\202307\\Mohamed\\Endo Lab Learning Preference - 2022 (A)(1-107).xlsx")
data_2022B=read_excel("C:\\Shengtong\\Research\\AllCollaboration\\2023\\202307\\Mohamed\\Endo Lab Learning Preference - 2022 (B)(1-106).xlsx")
data_2023=read_excel("C:\\Shengtong\\Research\\AllCollaboration\\2023\\202307\\Mohamed\\Endo Lab Learning Preference - 2023 (B)(1-94).xlsx")
```


## Q1: Please rank these methods of receiving information for lab projects from 1 to 4, with 1 being your most preferred delivery method and 4 being your least preferred

```{r, echo=F, message=F, warning=F}
colnames(data_2021)[6]="Q1"
data_2021_plot=data_2021 %>% dplyr::count(Q1)%>% mutate(prop=n/nrow(data_2021))

  
g1=ggplot(data_2021_plot, aes(x=Q1, y=prop, fill=Q1)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(data_2021_plot, aes(x=Q1, y=n, fill=Q1)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=12))+
  ylab("count")+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="right") 
annotate_figure(figure,
                top = text_grob("", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)
################
```


