---
title: "1/23/2023"
output: html_document
date: "2023-01-23"
---


```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
library(ggpubr)
library(rstatix) # use anova_test function 
library(DT)
set.seed(123)
```


```{r, echo=F, warning=F, message=F}
######## adjust p values 
pvalue_adjust=function(p_value)
{
  p_value_adjust=numeric()
for (i in 1:length(p_value))
{
  if (is.na(p_value[i])==T)
    p_value_adjust[i]=p_value[i]
  if (is.na(p_value[i])==F & p_value[i]<0.0001)
    p_value_adjust[i]="<0.0001"
  if (is.na(p_value[i])==F & p_value[i]>0.0001)
    p_value_adjust[i]=round(p_value[i],4)
}
  return(p_value_adjust)
}
############### summary statistics for continuous variable 
summary_statistics=function(data)
{  # each column is one variable, and row one subject 
  
  variables=colnames(data)
num_sample=numeric()
Mean=numeric()
SD=numeric()
SE=numeric()
range_min=numeric()
range_max=numeric()
for (i in 1:ncol(data))
{
  observation=data[,i]
  observation=observation[!is.na(observation)]
  num_sample[i]=length(observation)
  Mean[i]=round(mean(observation),4)
  SD[i]=round(sd(observation),4)
  SE[i]=round(SD[i]/sqrt(num_sample[i]),4)
  range_min[i]=round(min(observation),4)
  range_max[i]=round(max(observation),4)
}

summary_data=data.frame(materials=variables, num_sample=num_sample, Mean=Mean, SD=SD, SE=SE, Range_low=range_min, Range_upper=range_max)

summary_data%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
  
 return(summary_data) 
}

```


```{r, echo=F, message=F, warning=F}
data=read.csv("C:\\Shengtong\\Research\\AllCollaboration\\2023\\202301\\Steven\\Results_Final.csv", header=T)
```


## Summary statistics 

```{r, echo=F, message=F, warning=F}
data_summary=summary_statistics(data)
data_summary%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```


## anova test 

### 24 hours 

```{r, echo=F, message=F, warning=F}
sub_data=data.frame(MPA=c(data$Integrity.24.Hours, data$Crown.tec.24.hours, data$MFH.24.Hours), materials=rep(c("Integrity", "Crown.tec", "MPH"), each=nrow(data)))

f1=ggplot(sub_data, aes(x=materials, y=MPA, fill=materials)) +
  geom_boxplot()+
  theme(legend.position = "none")
f1
anova(lm(MPA~ materials, data=sub_data))

```

* p value of `< 2.2e-16` suggests 3 materials are not all equal 

### Thermocycling 

```{r, echo=F, message=F, warning=F}
sub_data=data.frame(MPA=c(data$Integrity.Thermocycling, data$Crowntec.Thermocycling, data$MFH.Thermocycling), materials=rep(c("Integrity", "Crown.tec", "MPH"), each=nrow(data)))

f1=ggplot(sub_data, aes(x=materials, y=MPA, fill=materials)) +
  geom_boxplot()+
  theme(legend.position = "none")
f1
anova(lm(MPA~ materials, data=sub_data))
```


* p value of `7.172e-16` suggests 3 materials are not all equal


### one month  

```{r, echo=F, message=F, warning=F}
sub_data=data.frame(MPA=c(data$Integrity.1.month, data$Crown.tec.1.month, data$MFH.1.Month), materials=rep(c("Integrity", "Crown.tec", "MPH"), each=nrow(data)))

f1=ggplot(sub_data, aes(x=materials, y=MPA, fill=materials)) +
  geom_boxplot()+
  theme(legend.position = "none")
f1
anova(lm(MPA~ materials, data=sub_data))
```

* p value of `< 2.2e-16` suggests 3 materials are not all equal 


## pairwise comparison 


### Integrity 


```{r, echo=F, message=F, warning=F}
#sub_data=data.frame(Integrity.24.Hours=data$Integrity.24.Hours, Integrity.1.month=data$Integrity.1.month, Integrity.Thermocycling=data$Integrity.Thermocycling)
p_value=numeric(); estimate=numeric(); CI_lower=numeric(); CI_upper=numeric()
group2=data$Integrity.24.Hours
group2<-group2[!is.na(group2)] # remove NA values 
for (i in 1:2)
{
  group1=data[,i+1]
  group1<-group1[!is.na(group1)]
  test=t.test(group1, group2)
  p_value[i]=test$p.value
  CI_lower[i]=test$conf.int[1]
  CI_upper[i]=test$conf.int[2]
  estimate[i]=mean(group1)-mean(group2)
  ##############
}


result=data_frame(group1=colnames(data)[2:3], group2=rep(colnames(data)[1], 2), mean_difference=round(estimate,2),  CI_lower=round(CI_lower,2),  CI_upper=round(CI_upper,2), p_value=pvalue_adjust(p_value)) 

result%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

sub_data=data.frame(
  MPA=c(
  mean(data$Integrity.24.Hours, na.rm=T), 
  mean(data$Integrity.1.month, na.rm=T), 
  mean(data$Integrity.Thermocycling, na.rm=T)), 
  sd=c(
    sd(data$Integrity.24.Hours, na.rm=T), 
    sd(data$Integrity.1.month, na.rm=T), 
    sd(data$Integrity.Thermocycling, na.rm=T)), 
  condition=colnames(data)[1:3])

y_position=max(sub_data$MPA+sub_data$sd)+5

ggplot(sub_data, aes(x=condition, y=MPA, fill=condition)) + 
  geom_bar(stat="identity", color="black", 
           position=position_dodge()) +
  geom_errorbar(aes(ymin=MPA-sd, ymax=MPA+sd), width=.2,
                 position=position_dodge(.9))+
  theme(legend.title=element_blank())+
  geom_text(aes(label=round(MPA,2)), position=position_dodge(width=0.8), vjust=-0.5, color="blue")+  # add numbers over bars; vjust: adjust the vertical position of numbers 
  ylab("MPA")+
  geom_signif(annotations ="p=0.569", y_position =y_position  ,xmin=1, xmax=1.9, size=1, vjust=-0.5, textsize=3, color="black")+
  geom_signif(annotations ="p=0.999", y_position =y_position  ,xmin=2.1, xmax=3, size=1, vjust=-0.5, textsize=3, color="black")
```



### Crown.tec


```{r, echo=F, message=F, warning=F}
p_value=numeric(); estimate=numeric(); CI_lower=numeric(); CI_upper=numeric()
group2=data$Crown.tec.24.hours
group2<-group2[!is.na(group2)] # remove NA values 
for (i in 1:2)
{
  group1=data[,i+4]
  group1<-group1[!is.na(group1)]
  test=t.test(group1, group2)
  p_value[i]=test$p.value
  CI_lower[i]=test$conf.int[1]
  CI_upper[i]=test$conf.int[2]
  estimate[i]=mean(group1)-mean(group2)
  ##############
}


result=data_frame(group1=colnames(data)[5:6], group2=rep(colnames(data)[4], 2), mean_difference=round(estimate,2),  CI_lower=round(CI_lower,2),  CI_upper=round(CI_upper,2), p_value=pvalue_adjust(p_value)) 

result%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

sub_data=data.frame(
  MPA=c(
  mean(data$Crown.tec.24.hours, na.rm=T), 
  mean(data$Crown.tec.1.month, na.rm=T), 
  mean(data$Crowntec.Thermocycling, na.rm=T)), 
  sd=c(
    sd(data$Crown.tec.24.hours, na.rm=T), 
    sd(data$Crown.tec.1.month, na.rm=T), 
    sd(data$Crowntec.Thermocycling, na.rm=T)), 
  condition=colnames(data)[4:6])

y_position=max(sub_data$MPA+sub_data$sd)+5

ggplot(sub_data, aes(x=condition, y=MPA, fill=condition)) + 
  geom_bar(stat="identity", color="black", 
           position=position_dodge()) +
  geom_errorbar(aes(ymin=MPA-sd, ymax=MPA+sd), width=.2,
                 position=position_dodge(.9))+
  theme(legend.title=element_blank())+
  geom_text(aes(label=round(MPA,2)), position=position_dodge(width=0.8), vjust=-0.5, color="blue")+  # add numbers over bars; vjust: adjust the vertical position of numbers 
  ylab("MPA")+
  geom_signif(annotations ="p=0.005", y_position =y_position  ,xmin=1, xmax=1.9, size=1, vjust=-0.5, textsize=3, color="red")+
  geom_signif(annotations ="p=0.750", y_position =y_position  ,xmin=2.1, xmax=3, size=1, vjust=-0.5, textsize=3, color="black")
```


### MPH


```{r, echo=F, message=F, warning=F}
p_value=numeric(); estimate=numeric(); CI_lower=numeric(); CI_upper=numeric()
group2=data$MFH.24.Hours
group2<-group2[!is.na(group2)] # remove NA values 
for (i in 1:2)
{
  group1=data[,i+7]
  group1<-group1[!is.na(group1)]
  test=t.test(group1, group2)
  p_value[i]=test$p.value
  CI_lower[i]=test$conf.int[1]
  CI_upper[i]=test$conf.int[2]
  estimate[i]=mean(group1)-mean(group2)
  ##############
}


result=data_frame(group1=colnames(data)[8:9], group2=rep(colnames(data)[7], 2), mean_difference=round(estimate,2),  CI_lower=round(CI_lower,2),  CI_upper=round(CI_upper,2), p_value=pvalue_adjust(p_value)) 

result%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

sub_data=data.frame(
  MPA=c(
  mean(data$MFH.24.Hours, na.rm=T), 
  mean(data$MFH.1.Month, na.rm=T), 
  mean(data$MFH.Thermocycling, na.rm=T)), 
  sd=c(
    sd(data$MFH.24.Hours, na.rm=T), 
    sd(data$MFH.1.Month, na.rm=T), 
    sd(data$MFH.Thermocycling, na.rm=T)), 
  condition=colnames(data)[7:9])

y_position=max(sub_data$MPA+sub_data$sd)+5

ggplot(sub_data, aes(x=condition, y=MPA, fill=condition)) + 
  geom_bar(stat="identity", color="black", 
           position=position_dodge()) +
  geom_errorbar(aes(ymin=MPA-sd, ymax=MPA+sd), width=.2,
                 position=position_dodge(.9))+
  theme(legend.title=element_blank())+
  geom_text(aes(label=round(MPA,2)), position=position_dodge(width=0.8), vjust=-0.5, color="blue")+  # add numbers over bars; vjust: adjust the vertical position of numbers 
  ylab("MPA")+
  geom_signif(annotations ="p=0.272", y_position =y_position  ,xmin=1, xmax=1.9, size=1, vjust=-0.5, textsize=3, color="black")+
  geom_signif(annotations ="p=0.681", y_position =y_position  ,xmin=2.1, xmax=3, size=1, vjust=-0.5, textsize=3, color="black")
```


## sample size calculation 



```{r, echo=F}
d=seq(5, 20, by=1); SD=16
sample_size=numeric()
for (i in 1:length(d))
{
  test=power.t.test(power = .80, delta = d[i], alternative = "two.sided", sig.level=0.05, sd=SD, type="two.sample") #  two sample t test 
  sample_size[i]=round(test$n)
}
ggplot(data=data.frame(d, sample_size), aes(x=d, y=sample_size, group=1)) +
  geom_line(color="red")+
  geom_vline(xintercept=16, colour="blue") +
  geom_text(aes(x=16, label="d=16", y=40), colour="blue", angle=0, vjust = 1.2)+  # here x, y are coordinate 
  geom_hline(yintercept=16.7, colour="blue") +
  geom_text(aes(x=10, label="n=16.7", y=16.7), colour="red", angle=0, vjust = 1.2)+  # here x, y are coordinate 
  geom_point()+
  xlab("d:mean difference")+
  ylab("n:sample size")+
  ggtitle("power=0.8; SD=16")+
  theme(plot.title = element_text(hjust = 0.5, size=15))

data.frame(mean_difference=d, sample_size=sample_size)%>%
datatable(extensions = 'Buttons',
          caption="power=0.8",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


```


```{r, echo=F, message=F, warning=F}
d=seq(5, 20, by=1); SD=16
sample_size=numeric()
for (i in 1:length(d))
{
  test=power.t.test(power = .90, delta = d[i], alternative = "two.sided", sig.level=0.05, sd=SD, type="two.sample") #  two sample t test 
  sample_size[i]=round(test$n)
}
ggplot(data=data.frame(d, sample_size), aes(x=d, y=sample_size, group=1)) +
  geom_line(color="red")+
  geom_vline(xintercept=16, colour="blue") +
  geom_text(aes(x=16, label="d=16", y=40), colour="blue", angle=0, vjust = 1.2)+  # here x, y are coordinate 
  geom_hline(yintercept=22.02, colour="blue") +
  geom_text(aes(x=10, label="n=22.02", y=22), colour="red", angle=0, vjust = 1.2)+  # here x, y are coordinate 
  geom_point()+
  xlab("d:mean difference")+
  ylab("n:sample size")+
  ggtitle("power=0.9; SD=16")+
  theme(plot.title = element_text(hjust = 0.5, size=15))

data.frame(mean_difference=d, sample_size=sample_size)%>%
datatable(extensions = 'Buttons',
          caption="power=0.8",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```
