---
title: "6/5/2023"
output: html_document
date: "2023-06-05"
---

```{r setup, include=FALSE}
rm(list=ls())
library(tidyverse)
library(kableExtra)
library(ggpubr)
library(rstatix) # use anova_test function 
library(grid)
library(DT)
library(gridExtra)
library(matrixStats)
library(cowplot)
set.seed(123)
```




```{r, echo=F, warning=F, message=F}
######## adjust p values 
pvalue_adjust=function(p_value)
{
  p_value_adjust=numeric()
for (i in 1:length(p_value))
{
  if (is.na(p_value[i])==T)
    p_value_adjust[i]=p_value[i]
  if (is.na(p_value[i])==F & p_value[i]<0.0001)
    p_value_adjust[i]="<0.0001"
  if (is.na(p_value[i])==F & p_value[i]>0.0001)
    p_value_adjust[i]=round(p_value[i],4)
}
  return(p_value_adjust)
}
############### summary statistics for continuous variable 
summary_statistics=function(data)
{  # each column is one variable, and row one subject 
  
variables=colnames(data)
num_sample=numeric()
Mean=numeric()
SD=numeric()
SE=numeric()
range_min=numeric()
range_max=numeric()
normality_pvalue=numeric()
for (i in 1:ncol(data))
{
  observation=data[,i]
  observation=observation[!is.na(observation)] # remove missing values 
  num_sample[i]=length(observation)
  Mean[i]=round(mean(observation),4)
  SD[i]=round(sd(observation),4)
  SE[i]=round(SD[i]/sqrt(num_sample[i]),4)
  range_min[i]=round(min(observation),4)
  range_max[i]=round(max(observation),4)
  normality_pvalue[i]=round(shapiro.test(observation)$p.value,4)
}

summary_data=data.frame(materials=variables, num_sample=num_sample, Mean=Mean, SD=SD, SE=SE, Range_low=range_min, Range_upper=range_max, normality_pvalue=normality_pvalue)

summary_data%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
  
 return(summary_data) 
}

```


```{r, echo=F, message=F, warning=F}
data=as_tibble(read.csv("C:\\Shengtong\\Research\\AllCollaboration\\2023\\202306\\Arndt\\Health literacy and Periodontal Health_data_for analysis.csv", header=T))
#data%>%
#datatable(extensions = 'Buttons',
#          caption = "Sample data", 
#            options = list(dom = 'Blfrtip',
#                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
#                           lengthMenu = list(c(10,25,50,-1),
#                                             c(10,25,50,"All"))))
```

## Basic statistics 

```{r, echo=F, message=F, warning=F}
ggplot(data %>% dplyr::count(fourGroupsVAR00001)%>% mutate(status=c("Periodontal Health", "Gingivitis", "Early/Moderate Periodontitis", "Severe Periodontitis")), aes(x=as.factor(fourGroupsVAR00001), y=n, fill=status)) +geom_bar(stat="identity")+
  theme(legend.position="bottom")+
   theme(legend.title=element_blank())+ # remove legend title 
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("n")+
  xlab("fourGroupsVAR00001")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25)+  # add numbers over bars
  ggtitle("")+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title
```

```{r, echo=F,message=F, warning=F}
############## age 
variable="Age"
sub_data=data.frame(mean=round(c(mean(data$Age[data$Disease_Y_N=="Y"], na.rm=T), mean(data$Age[data$Disease_Y_N=="N"], na.rm=T))), sd=round(c(sd(data$Age[data$Disease_Y_N=="Y"], na.rm=T), sd(data$Age[data$Disease_Y_N=="N"], na.rm=T))), Disease=c("Y", "N"))
f1=ggplot(sub_data, aes(x=Disease, y=round(mean), fill=Disease)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
   theme(legend.title=element_blank())+ # remove legend title 
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab(variable)+
  xlab("Disease")+
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9))+
  geom_text(aes(label=round(mean)), position=position_dodge(width=0.6), vjust=-0.25)+  # add numbers over bars
  ggtitle("")+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title
sub_data %>%
datatable(extensions = 'Buttons',
          caption = variable, 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
#f1
########### decayed teeth 
variable="Decayed"
sub_data=data.frame(mean=round(c(mean(data$Decayed[data$Disease_Y_N=="Y"], na.rm=T), mean(data$Decayed[data$Disease_Y_N=="N"], na.rm=T)),1), sd=round(c(sd(data$Decayed[data$Disease_Y_N=="Y"], na.rm=T), sd(data$Decayed[data$Disease_Y_N=="N"], na.rm=T)),1), Disease=c("Y", "N"))
f2=ggplot(sub_data, aes(x=Disease, y=mean, fill=Disease)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
   theme(legend.title=element_blank())+ # remove legend title 
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab(variable)+
  xlab("Disease")+
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9))+
  geom_text(aes(label=mean), position=position_dodge(width=0.6), vjust=-0.25)+  # add numbers over bars
  ggtitle("")+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title
sub_data %>%
datatable(extensions = 'Buttons',
          caption = variable, 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
#f2


########### missing teeth 
variable="Missing"
sub_data=data.frame(mean=round(c(mean(data$Missing[data$Disease_Y_N=="Y"], na.rm=T), mean(data$Missing[data$Disease_Y_N=="N"], na.rm=T)),1), sd=round(c(sd(data$Missing[data$Disease_Y_N=="Y"], na.rm=T), sd(data$Missing[data$Disease_Y_N=="N"], na.rm=T)),1), Disease=c("Y", "N"))
f3=ggplot(sub_data, aes(x=Disease, y=mean, fill=Disease)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
   theme(legend.title=element_blank())+ # remove legend title 
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab(variable)+
  xlab("Disease")+
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9))+
  geom_text(aes(label=mean), position=position_dodge(width=0.6), vjust=-0.25)+  # add numbers over bars
  ggtitle("")+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title
sub_data %>%
datatable(extensions = 'Buttons',
          caption = variable, 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
#f3

########### filled teeth 
variable="Filled"
sub_data=data.frame(mean=round(c(mean(data$Filled[data$Disease_Y_N=="Y"], na.rm=T), mean(data$Filled[data$Disease_Y_N=="N"], na.rm=T)),1), sd=round(c(sd(data$Filled[data$Disease_Y_N=="Y"], na.rm=T), sd(data$Filled[data$Disease_Y_N=="N"], na.rm=T)),1), Disease=c("Y", "N"))
f4=ggplot(sub_data, aes(x=Disease, y=mean, fill=Disease)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
   theme(legend.title=element_blank())+ # remove legend title 
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab(variable)+
  xlab("Disease")+
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9))+
  geom_text(aes(label=mean), position=position_dodge(width=0.6), vjust=-0.25)+  # add numbers over bars
  ggtitle("")+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title
sub_data %>%
datatable(extensions = 'Buttons',
          caption = variable, 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
#f4

########### DMFT
variable="DMFT"
sub_data=data.frame(mean=round(c(mean(data$DMFT[data$Disease_Y_N=="Y"], na.rm=T), mean(data$DMFT[data$Disease_Y_N=="N"], na.rm=T)),1), sd=round(c(sd(data$DMFT[data$Disease_Y_N=="Y"], na.rm=T), sd(data$DMFT[data$Disease_Y_N=="N"], na.rm=T)),1), Disease=c("Y", "N"))
f5=ggplot(sub_data, aes(x=Disease, y=mean, fill=Disease)) +geom_bar(stat="identity")+
  theme(legend.position="right")+
   theme(legend.title=element_blank())+ # remove legend title 
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab(variable)+
  xlab("Disease")+
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.9))+
  geom_text(aes(label=mean), position=position_dodge(width=0.6), vjust=-0.25)+  # add numbers over bars
  ggtitle("")+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title
sub_data %>%
datatable(extensions = 'Buttons',
          caption = variable, 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
#f5


grid.arrange(f1, f2, f3,  f4, f5, nrow=3)
```



## statistical software 

```{r, echo=F}
R.version
```


