---
title: "combing corr and restore"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2024-05-21"
---


```{r, echo=F, message=F, warning=F}
source("C:/Shengtong/Research/AllCollaboration/Collaborations/analysis/Rfunctions.R")
multiplesheets <- function(fname) {
   
  # getting info about all excel sheets
  sheets <- readxl::excel_sheets(fname)
  tibble <- lapply(sheets, function(x) readxl::read_excel(fname, sheet = x))
  data_frame <- lapply(tibble, as.data.frame)
    
  # assigning names to data frames
  names(data_frame) <- sheets
    
  # print data frame
  print(data_frame)
}

```



## Home 

[home](2023_0901_Teerarat.html)



## corr+restore


```{r, message=F, warning=F, results=F}

data2=multiplesheets("C:\\Shengtong\\Research\\AllCollaboration\\2023\\202309\\Teerarat\\Peri-Implant DATA CLEAN 111023_without_header.xlsx")

```


### Gender


```{r, message=F, warning=F}
num_indi1=55
num_indi2=23
data_subset1=data2$`Data RESTORE` %>% dplyr::count(Gender) %>% drop_na()
data_subset1$Gender[data_subset1$Gender==1]="Male"; data_subset1$Gender[data_subset1$Gender==2]="Female"
data_subset2=data2$`Data CORR` %>% dplyr::count(Gender)  %>% drop_na()
data_subset2$Gender[data_subset2$Gender==1]="Male"; data_subset2$Gender[data_subset2$Gender==2]="Female"
data_subset=data_frame(Gender=data_subset1$Gender, n=data_subset1$n+data_subset2$n) %>% mutate(prop=round(n/(num_indi1+num_indi2),4))

data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


### Smoking


```{r, message=F, warning=F}
data_subset1=data2$`Data RESTORE` %>% dplyr::count(Smoking) %>% drop_na()
data_subset2=data2$`Data CORR` %>% dplyr::count(Smoking)  %>% drop_na()


data_subset=data_frame(Smoking=data_subset1$Smoking, n=data_subset1$n+data_subset2$n) %>% mutate(prop=round(n/(num_indi1+num_indi2),4))
data_subset$Smoking[data_subset$Smoking==1]="Never"; data_subset$Smoking[data_subset$Smoking==2]="Past"
data_subset$Smoking[data_subset$Smoking==3]="Current"; data_subset$Smoking[data_subset$Smoking==4]="not reported"

data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


### Diabetes





```{r, message=F, warning=F}
data_subset1=data2$`Data RESTORE` %>% dplyr::count(Diabetes) %>% drop_na()
data_subset2=data2$`Data CORR` %>% dplyr::count(Diabetes)  %>% drop_na()


data_subset=data_frame(Diabetes=data_subset1$Diabetes, n=data_subset1$n+c(data_subset2$n,0)) %>% mutate(prop=round(n/(num_indi1+num_indi2),4))
data_subset$Diabetes[data_subset$Diabetes==1]="Yes"; data_subset$Diabetes[data_subset$Diabetes==2]="No"

data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



### Implant_site



```{r, message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(Implant_site)  %>% drop_na()
index1=which(data_subset1$Implant_site<=16); index2=which(data_subset1$Implant_site>16)
n=c(sum(data_subset1$n[index1]), sum(data_subset1$n[index2]))
data_subset11=data.frame(Implant_site=c("Maxilla", "Mandible"), n=n)

data_subset2=data2$`Data CORR` %>% dplyr::count(Implant_site)  %>% drop_na()
index1=which(data_subset2$Implant_site<=16); index2=which(data_subset2$Implant_site>16)
n=c(sum(data_subset2$n[index1]), sum(data_subset2$n[index2]))
data_subset22=data.frame(Implant_site=c("Maxilla", "Mandible"), n=n)



data_subset=data_frame(Implant_site=data_subset11$Implant_site, n=data_subset11$n+data_subset22$n) %>% mutate(prop=round(n/(num_indi1+num_indi2),4))

data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



### Implant_site



```{r,  message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(Implant_site)  %>% drop_na()
index1=union(which(data_subset1$Implant_site<=5), which(data_subset1$Implant_site<=16 & data_subset1$Implant_site>=12)); index2=which(data_subset1$Implant_site>=6 &data_subset1$Implant_site<=11);
index3=union(which(data_subset1$Implant_site>=17 & data_subset1$Implant_site<=21), which(data_subset1$Implant_site<=31 & data_subset1$Implant_site>=28));
index4=which(data_subset1$Implant_site>=22 &data_subset1$Implant_site<=27 )

n=c(sum(data_subset1$n[index1]), sum(data_subset1$n[index2]), sum(data_subset1$n[index3]), sum(data_subset1$n[index4]))
prop=c(sum(data_subset1$prop[index1]), sum(data_subset1$prop[index2]), sum(data_subset1$prop[index3]), sum(data_subset1$prop[index4]))
data_subset11=data.frame(Implant_site=c("Upper posterior", "Upper anterior", "Lower posterior", "Lower anterior"), n=n, prop=prop)

data_subset2=data2$`Data CORR` %>% dplyr::count(Implant_site)  %>% drop_na()
index1=union(which(data_subset2$Implant_site<=5), which(data_subset2$Implant_site<=16 & data_subset2$Implant_site>=12)); index2=which(data_subset2$Implant_site>=6 &data_subset2$Implant_site<=11);
index3=union(which(data_subset2$Implant_site>=17 & data_subset2$Implant_site<=21), which(data_subset2$Implant_site<=31 & data_subset2$Implant_site>=28));
index4=which(data_subset2$Implant_site>=22 &data_subset2$Implant_site<=27 )

n=c(sum(data_subset2$n[index1]), sum(data_subset2$n[index2]), sum(data_subset2$n[index3]), sum(data_subset2$n[index4]))
prop=c(sum(data_subset2$prop[index1]), sum(data_subset2$prop[index2]), sum(data_subset2$prop[index3]), sum(data_subset2$prop[index4]))
data_subset22=data.frame(Implant_site=c("Upper posterior", "Upper anterior", "Lower posterior", "Lower anterior"), n=n, prop=prop)


data_subset=data_frame(Implant_site=data_subset11$Implant_site, n=data_subset11$n+data_subset22$n) %>% mutate(prop=round(n/(num_indi1+num_indi2),4))

data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



### Pre_implant_Procedure




```{r, message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(Pre_implant_Procedure)  %>% drop_na()

data_subset2=data2$`Data CORR` %>% dplyr::count(Pre_implant_Procedure)  %>% drop_na()



data_subset=data_frame(Pre_implant_Procedure=data_subset1$Pre_implant_Procedure, n=data_subset1$n+c(data_subset2$n[1:4], 0, data_subset2$n[5])) %>% mutate(prop=round(n/(num_indi1+num_indi2),4))

data_subset$Pre_implant_Procedure[data_subset$Pre_implant_Procedure==1]="Extraction alone"; data_subset$Pre_implant_Procedure[data_subset$Pre_implant_Procedure==2]="Extraction and bone graft"; 
data_subset$Pre_implant_Procedure[data_subset$Pre_implant_Procedure==3]="Extraction, bone graft and membrane";
data_subset$Pre_implant_Procedure[data_subset$Pre_implant_Procedure==4]="GBR";
data_subset$Pre_implant_Procedure[data_subset$Pre_implant_Procedure==5]="Sinus lift";
data_subset$Pre_implant_Procedure[data_subset$Pre_implant_Procedure==6]="other";
data_subset$Pre_implant_Procedure[data_subset$Pre_implant_Procedure==7]="not reported";


data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



### I_placement



```{r,  message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(I_placement) %>% drop_na()

data_subset2=data2$`Data CORR` %>% dplyr::count(I_placement)  %>% drop_na()



data_subset=data_frame(I_placement=c(seq(1,8),"NR"), n=c(38+13, 0+1, 0+0, 7+3, 3+3, 0+0, 5+2, 0+1, 2+0)) %>% mutate(prop=round(n/(num_indi1+num_indi2),4))

data_subset$I_placement[data_subset$I_placement==1]="Single implant placement"; data_subset$I_placement[data_subset$I_placement==2]="Placement with bone graft"; 
data_subset$I_placement[data_subset$I_placement==3]="Placement with membrane";
data_subset$I_placement[data_subset$I_placement==4]="Placement with bone graft and membrane";
data_subset$I_placement[data_subset$I_placement==5]="Placement with indirect sinus lift";
data_subset$I_placement[data_subset$I_placement==6]="Placement with direct sinus lift";
data_subset$I_placement[data_subset$I_placement==7]="Immediate/delayed placement";
data_subset$I_placement[data_subset$I_placement==8]="other";



data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


### Comp_placement




```{r,  message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(Comp_placement) %>% drop_na()

data_subset2=data2$`Data CORR` %>% dplyr::count(Comp_placement) %>% drop_na()

data_subset=data_frame(Comp_placement=c(1,3,8,9,"NR"), n=c(1+0, 1+0, 3+3, 50+19, 1))

data_subset$Comp_placement[data_subset$Comp_placement==1]="Adjusted direction during drill sequence"; data_subset$Comp_placement[data_subset$Comp_placement==2]="Guide broke, did not fit"; 
data_subset$Comp_placement[data_subset$Comp_placement==3]="Implant placed, immediately removed, reinserted";
data_subset$Comp_placement[data_subset$Comp_placement==4]="Bone perforatio during drilling or implant placement";
data_subset$Comp_placement[data_subset$Comp_placement==5]="Bone dehiscence during drilling or implant placement";
data_subset$Comp_placement[data_subset$Comp_placement==6]="Damage to vital structures";
data_subset$Comp_placement[data_subset$Comp_placement==7]="Flap tear/perforation/other damage";
data_subset$Comp_placement[data_subset$Comp_placement==8]="other";
data_subset$Comp_placement[data_subset$Comp_placement==9]="none/WNL";



data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```



### HA




```{r, message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(HA) %>%  drop_na()

data_subset2=data2$`Data CORR` %>% dplyr::count(HA)  %>% drop_na()

data_subset=data_frame(HA=data_subset1$HA, n=data_subset1$n+data_subset2$n) %>% mutate(prop=round(n/(num_indi1+num_indi2),4))

data_subset$HA[data_subset$HA==1]="Yes"; 
data_subset$HA[data_subset$HA==2]="No"; 




data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```




### I_Brand


```{r,  message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(I_Brand) %>% drop_na()

data_subset2=data2$`Data CORR` %>% dplyr::count(I_Brand)  %>% drop_na()

count_num=function(X)
{
  if (length(data_subset1 %>% filter(I_Brand==X) %>% select(n) %>% pull())==0)
    n1=0
  if (length(data_subset1 %>% filter(I_Brand==X) %>% select(n) %>% pull())>0)
    n1=data_subset1 %>% filter(I_Brand==X) %>% select(n) %>% pull()

  if (length(data_subset2 %>% filter(I_Brand==X) %>% select(n) %>% pull())==0)
    n2=0
   if (length(data_subset2 %>% filter(I_Brand==X) %>% select(n) %>% pull())>0)
    n2=data_subset2 %>% filter(I_Brand==X) %>% select(n) %>% pull()

  
  return(n1+n2)
    
}

all_variable=union(data_subset1$I_Brand, data_subset2$I_Brand)
variable_count=sapply(all_variable, count_num)


data_subset=data_frame(I_Brand=all_variable, n=variable_count)
data_subset$I_Brand[data_subset$I_Brand==1]="Nobel Biocare";
data_subset$I_Brand[data_subset$I_Brand==2]="Nobel Replace";
data_subset$I_Brand[data_subset$I_Brand==3]="Straumann BLT"; 
data_subset$I_Brand[data_subset$I_Brand==4]="Osseospeed Ev"; 
data_subset$I_Brand[data_subset$I_Brand==5]="Nobel Replace Connical Connection";
data_subset$I_Brand[data_subset$I_Brand==6]="Atra EV";
data_subset$I_Brand[data_subset$I_Brand==7]="BioHorizons Tapered Plus";
data_subset$I_Brand[data_subset$I_Brand==8]="Nobel Replace Select";
data_subset$I_Brand[data_subset$I_Brand==9]="Nobel Replace Tapered Groovy";
data_subset$I_Brand[data_subset$I_Brand==10]="Nobel Active Internal RP";
data_subset$I_Brand[data_subset$I_Brand==11]="Straumann WN";





data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All")))) 
```




### I_Surface



```{r, message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(I_Surface) %>% drop_na()

data_subset2=data2$`Data CORR` %>% dplyr::count(I_Surface)  %>% drop_na()

count_num=function(X)
{
  if (length(data_subset1 %>% filter(I_Surface==X) %>% select(n) %>% pull())==0)
    n1=0
  if (length(data_subset1 %>% filter(I_Surface==X) %>% select(n) %>% pull())>0)
    n1=data_subset1 %>% filter(I_Surface==X) %>% select(n) %>% pull()

  if (length(data_subset2 %>% filter(I_Surface==X) %>% select(n) %>% pull())==0)
    n2=0
   if (length(data_subset2 %>% filter(I_Surface==X) %>% select(n) %>% pull())>0)
    n2=data_subset2 %>% filter(I_Surface==X) %>% select(n) %>% pull()

  
  return(n1+n2)
    
}

all_variable=union(data_subset1$I_Surface, data_subset2$I_Surface)
variable_count=sapply(all_variable, count_num)
data_subset=data_frame(I_Surface=all_variable, n=variable_count)

data_subset$I_Surface[data_subset$I_Surface==1]="TiUltra";
data_subset$I_Surface[data_subset$I_Surface==2]="TiUnite"; 
data_subset$I_Surface[data_subset$I_Surface==3]="SLA";
data_subset$I_Surface[data_subset$I_Surface==4]="TiO2";
data_subset$I_Surface[data_subset$I_Surface==5]="Ti";
data_subset$I_Surface[data_subset$I_Surface==6]="TLXP3812";
data_subset$I_Surface[data_subset$I_Surface==7]="Tiu"; 




data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```



### I_Shape


```{r,  message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(I_Shape)  %>% drop_na()

data_subset2=data2$`Data CORR` %>% dplyr::count(I_Shape)  %>% drop_na()

count_num=function(X)
{
  if (length(data_subset1 %>% filter(I_Shape==X) %>% select(n) %>% pull())==0)
    n1=0
  if (length(data_subset1 %>% filter(I_Shape==X) %>% select(n) %>% pull())>0)
    n1=data_subset1 %>% filter(I_Shape==X) %>% select(n) %>% pull()

  if (length(data_subset2 %>% filter(I_Shape==X) %>% select(n) %>% pull())==0)
    n2=0
   if (length(data_subset2 %>% filter(I_Shape==X) %>% select(n) %>% pull())>0)
    n2=data_subset2 %>% filter(I_Shape==X) %>% select(n) %>% pull()

  
  return(n1+n2)
    
}

all_variable=union(data_subset1$I_Shape, data_subset2$I_Shape)
variable_count=sapply(all_variable, count_num)
data_subset=data_frame(I_Shape=all_variable, n=variable_count)


data_subset$I_Shape[data_subset$I_Shape==1]="straight"; 
data_subset$I_Shape[data_subset$I_Shape==2]="tapered"; 







data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```




### I_Techique


```{r, message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(I_Technique)  %>% drop_na()

data_subset2=data2$`Data CORR` %>% dplyr::count(I_Technique)  %>% drop_na()

count_num=function(X)
{
  if (length(data_subset1 %>% filter(I_Technique==X) %>% select(n) %>% pull())==0)
    n1=0
  if (length(data_subset1 %>% filter(I_Technique==X) %>% select(n) %>% pull())>0)
    n1=data_subset1 %>% filter(I_Technique==X) %>% select(n) %>% pull()

  if (length(data_subset2 %>% filter(I_Technique==X) %>% select(n) %>% pull())==0)
    n2=0
   if (length(data_subset2 %>% filter(I_Technique==X) %>% select(n) %>% pull())>0)
    n2=data_subset2 %>% filter(I_Technique==X) %>% select(n) %>% pull()

  
  return(n1+n2)
    
}

all_variable=union(data_subset1$I_Technique, data_subset2$I_Technique)
variable_count=sapply(all_variable, count_num)
data_subset=data_frame(I_Technique=all_variable, n=variable_count)

data_subset$I_Technique[data_subset$I_Technique==1]="Free handed"; 
data_subset$I_Technique[data_subset$I_Technique==2]="Pilot guided";
data_subset$I_Technique[data_subset$I_Technique==3]="Fully guided";
data_subset$I_Technique[data_subset$I_Technique==4]="Surgical guide";
data_subset$I_Technique[data_subset$I_Technique==5]="NR"; 







data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```







### I_Location


```{r,  message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(I_Location) %>% drop_na()

data_subset2=data2$`Data CORR` %>% dplyr::count(I_Location) %>% drop_na()

count_num=function(X)
{
  if (length(data_subset1 %>% filter(I_Location==X) %>% select(n) %>% pull())==0)
    n1=0
  if (length(data_subset1 %>% filter(I_Location==X) %>% select(n) %>% pull())>0)
    n1=data_subset1 %>% filter(I_Location==X) %>% select(n) %>% pull()

  if (length(data_subset2 %>% filter(I_Location==X) %>% select(n) %>% pull())==0)
    n2=0
   if (length(data_subset2 %>% filter(I_Location==X) %>% select(n) %>% pull())>0)
    n2=data_subset2 %>% filter(I_Location==X) %>% select(n) %>% pull()

  
  return(n1+n2)
    
}

all_variable=union(data_subset1$I_Location, data_subset2$I_Location)
variable_count=sapply(all_variable, count_num)
data_subset=data_frame(I_Location=all_variable, n=variable_count)

data_subset$I_Location[data_subset$I_Location==1]="Supracrestal";
data_subset$I_Location[data_subset$I_Location==2]="Equicrestal"; 
data_subset$I_Location[data_subset$I_Location==3]="Subcrestal";







data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```





### Postop_med


```{r,  message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(Postop_med) %>%  drop_na()

data_subset2=data2$`Data CORR` %>% dplyr::count(Postop_med) %>%  drop_na()

count_num=function(X)
{
  if (length(data_subset1 %>% filter(Postop_med==X) %>% select(n) %>% pull())==0)
    n1=0
  if (length(data_subset1 %>% filter(Postop_med==X) %>% select(n) %>% pull())>0)
    n1=data_subset1 %>% filter(Postop_med==X) %>% select(n) %>% pull()

  if (length(data_subset2 %>% filter(Postop_med==X) %>% select(n) %>% pull())==0)
    n2=0
   if (length(data_subset2 %>% filter(Postop_med==X) %>% select(n) %>% pull())>0)
    n2=data_subset2 %>% filter(Postop_med==X) %>% select(n) %>% pull()

  
  return(n1+n2)
    
}

all_variable=union(data_subset1$Postop_med, data_subset2$Postop_med)
variable_count=sapply(all_variable, count_num)
data_subset=data_frame(Postop_med=all_variable, n=variable_count)

data_subset$Postop_med[data_subset$Postop_med==1]="Amoxicillin";
data_subset$Postop_med[data_subset$Postop_med==2]="Clindamycin"; 
data_subset$Postop_med[data_subset$Postop_med==3]="Azithromycin";
data_subset$Postop_med[data_subset$Postop_med==4]="not reported"; 
data_subset$Postop_med[data_subset$Postop_med==5]="doxycycline"
data_subset$Postop_med[data_subset$Postop_med==6]="antibiotic not specified"







data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```


### Premed


```{r,  message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(Premed) %>% drop_na()

data_subset2=data2$`Data CORR` %>% dplyr::count(Premed)  %>% drop_na()


count_num=function(X)
{
  if (length(data_subset1 %>% filter(Premed==X) %>% select(n) %>% pull())==0)
    n1=0
  if (length(data_subset1 %>% filter(Premed==X) %>% select(n) %>% pull())>0)
    n1=data_subset1 %>% filter(Premed==X) %>% select(n) %>% pull()

  if (length(data_subset2 %>% filter(Premed==X) %>% select(n) %>% pull())==0)
    n2=0
   if (length(data_subset2 %>% filter(Premed==X) %>% select(n) %>% pull())>0)
    n2=data_subset2 %>% filter(Premed==X) %>% select(n) %>% pull()

  
  return(n1+n2)
    
}

all_variable=union(data_subset1$Premed, data_subset2$Premed)
variable_count=sapply(all_variable, count_num)
data_subset=data_frame(Premed=all_variable, n=variable_count)

data_subset$Premed[data_subset$Premed==1]="Amoxicillin";
data_subset$Premed[data_subset$Premed==2]="not reported"; 







data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```



### Provider_level


```{r, message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(Provider_level)  %>% drop_na()

data_subset2=data2$`Data CORR` %>% dplyr::count(Provider_level) %>% drop_na()

count_num=function(X)
{
  if (length(data_subset1 %>% filter(Provider_level==X) %>% select(n) %>% pull())==0)
    n1=0
  if (length(data_subset1 %>% filter(Provider_level==X) %>% select(n) %>% pull())>0)
    n1=data_subset1 %>% filter(Provider_level==X) %>% select(n) %>% pull()

  if (length(data_subset2 %>% filter(Provider_level==X) %>% select(n) %>% pull())==0)
    n2=0
   if (length(data_subset2 %>% filter(Provider_level==X) %>% select(n) %>% pull())>0)
    n2=data_subset2 %>% filter(Provider_level==X) %>% select(n) %>% pull()

  
  return(n1+n2)
    
}

all_variable=union(data_subset1$Provider_level, data_subset2$Provider_level)
variable_count=sapply(all_variable, count_num)
data_subset=data_frame(Provider_level=all_variable, n=variable_count)

data_subset$Provider_level[data_subset$Provider_level==1]="Faculty";
data_subset$Provider_level[data_subset$Provider_level==2]="Perio resident";
data_subset$Provider_level[data_subset$Provider_level==3]="Pros resident";
data_subset$Provider_level[data_subset$Provider_level==4]="AEGD resident";






data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```



### Present_comp_post_placement


```{r,  message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(Present_comp_post_placement) %>%  drop_na()

data_subset2=data2$`Data CORR` %>% dplyr::count(Present_comp_post_placement) %>% drop_na()



count_num=function(X)
{
  if (length(data_subset1 %>% filter(Present_comp_post_placement==X) %>% select(n) %>% pull())==0)
    n1=0
  if (length(data_subset1 %>% filter(Present_comp_post_placement==X) %>% select(n) %>% pull())>0)
    n1=data_subset1 %>% filter(Present_comp_post_placement==X) %>% select(n) %>% pull()

  if (length(data_subset2 %>% filter(Present_comp_post_placement==X) %>% select(n) %>% pull())==0)
    n2=0
   if (length(data_subset2 %>% filter(Present_comp_post_placement==X) %>% select(n) %>% pull())>0)
    n2=data_subset2 %>% filter(Present_comp_post_placement==X) %>% select(n) %>% pull()

  
  return(n1+n2)
    
}

all_variable=union(data_subset1$Present_comp_post_placement, data_subset2$Present_comp_post_placement)
variable_count=sapply(all_variable, count_num)
data_subset=data_frame(Present_comp_post_placement=all_variable, n=variable_count)


data_subset$Present_comp_post_placement[data_subset$Present_comp_post_placement==1]="yes";
data_subset$Present_comp_post_placement[data_subset$Present_comp_post_placement==2]="no";





data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```



### Coverscrew_exp_post_placement


```{r,  message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(Coverscrew_exp_post_placement)  %>% drop_na()

data_subset2=data2$`Data CORR` %>% dplyr::count(Coverscrew_exp_post_placement)  %>% drop_na()

count_num=function(X)
{
  if (length(data_subset1 %>% filter(Coverscrew_exp_post_placement==X) %>% select(n) %>% pull())==0)
    n1=0
  if (length(data_subset1 %>% filter(Coverscrew_exp_post_placement==X) %>% select(n) %>% pull())>0)
    n1=data_subset1 %>% filter(Coverscrew_exp_post_placement==X) %>% select(n) %>% pull()

  if (length(data_subset2 %>% filter(Coverscrew_exp_post_placement==X) %>% select(n) %>% pull())==0)
    n2=0
   if (length(data_subset2 %>% filter(Coverscrew_exp_post_placement==X) %>% select(n) %>% pull())>0)
    n2=data_subset2 %>% filter(Coverscrew_exp_post_placement==X) %>% select(n) %>% pull()

  
  return(n1+n2)
    
}

all_variable=union(data_subset1$Coverscrew_exp_post_placement, data_subset2$Coverscrew_exp_post_placement)
variable_count=sapply(all_variable, count_num)
data_subset=data_frame(Coverscrew_exp_post_placement=all_variable, n=variable_count)


data_subset$Coverscrew_exp_post_placement[data_subset$Coverscrew_exp_post_placement==1]="yes";
data_subset$Coverscrew_exp_post_placement[data_subset$Coverscrew_exp_post_placement==2]="no";





data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```




### Infection/pus_post_placement


```{r,  message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(`Infection/pus_post_placement`)  %>% drop_na()

data_subset2=data2$`Data CORR` %>% dplyr::count(`Infection/pus_post_placement`) %>% drop_na()

count_num=function(X)
{
  if (length(data_subset1 %>% filter(`Infection/pus_post_placement`==X) %>% select(n) %>% pull())==0)
    n1=0
  if (length(data_subset1 %>% filter(`Infection/pus_post_placement`==X) %>% select(n) %>% pull())>0)
    n1=data_subset1 %>% filter(`Infection/pus_post_placement`==X) %>% select(n) %>% pull()

  if (length(data_subset2 %>% filter(`Infection/pus_post_placement`==X) %>% select(n) %>% pull())==0)
    n2=0
   if (length(data_subset2 %>% filter(`Infection/pus_post_placement`==X) %>% select(n) %>% pull())>0)
    n2=data_subset2 %>% filter(`Infection/pus_post_placement`==X) %>% select(n) %>% pull()

  
  return(n1+n2)
    
}

all_variable=union(data_subset1$`Infection/pus_post_placement`, data_subset2$`Infection/pus_post_placement`)
variable_count=sapply(all_variable, count_num)
data_subset=data_frame(`Infection/pus_post_placement`=all_variable, n=variable_count)


data_subset$`Infection/pus_post_placement`[data_subset$`Infection/pus_post_placement`==1]="yes";
data_subset$`Infection/pus_post_placement`[data_subset$`Infection/pus_post_placement`==2]="no";





data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```



### Other_post_placement


```{r,  message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(Other_post_placement)  %>% drop_na()

data_subset2=data2$`Data CORR` %>% dplyr::count(Other_post_placement)  %>% drop_na()

count_num=function(X)
{
  if (length(data_subset1 %>% filter(Other_post_placement==X) %>% select(n) %>% pull())==0)
    n1=0
  if (length(data_subset1 %>% filter(Other_post_placement==X) %>% select(n) %>% pull())>0)
    n1=data_subset1 %>% filter(Other_post_placement==X) %>% select(n) %>% pull()

  if (length(data_subset2 %>% filter(Other_post_placement==X) %>% select(n) %>% pull())==0)
    n2=0
   if (length(data_subset2 %>% filter(Other_post_placement==X) %>% select(n) %>% pull())>0)
    n2=data_subset2 %>% filter(Other_post_placement==X) %>% select(n) %>% pull()

  
  return(n1+n2)
    
}

all_variable=union(data_subset1$Other_post_placement, data_subset2$Other_post_placement)
variable_count=sapply(all_variable, count_num)
data_subset=data_frame(Other_post_placement=all_variable, n=variable_count)


data_subset$Other_post_placement[data_subset$Other_post_placement==1]="yes";
data_subset$Other_post_placement[data_subset$Other_post_placement==2]="no";





data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```


### Type_bone_loss


```{r,  message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(Type_bone_loss)  %>% drop_na()

data_subset2=data2$`Data CORR` %>% dplyr::count(Type_bone_loss)  %>% drop_na()

count_num=function(X)
{
  if (length(data_subset1 %>% filter(Type_bone_loss==X) %>% select(n) %>% pull())==0)
    n1=0
  if (length(data_subset1 %>% filter(Type_bone_loss==X) %>% select(n) %>% pull())>0)
    n1=data_subset1 %>% filter(Type_bone_loss==X) %>% select(n) %>% pull()

  if (length(data_subset2 %>% filter(Type_bone_loss==X) %>% select(n) %>% pull())==0)
    n2=0
   if (length(data_subset2 %>% filter(Type_bone_loss==X) %>% select(n) %>% pull())>0)
    n2=data_subset2 %>% filter(Type_bone_loss==X) %>% select(n) %>% pull()

  
  return(n1+n2)
    
}

all_variable=union(data_subset1$Type_bone_loss, data_subset2$Type_bone_loss)
variable_count=sapply(all_variable, count_num)
data_subset=data_frame(Type_bone_loss=all_variable, n=variable_count)


data_subset$Type_bone_loss[data_subset$Type_bone_loss==1]="vertical";
data_subset$Type_bone_loss[data_subset$Type_bone_loss==2]="horizontal";





data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```



### I_Survival


```{r,  message=F, warning=F}

data_subset1=data2$`Data RESTORE` %>% dplyr::count(I_Survival...45)  %>% drop_na()
colnames(data_subset1)[1]="I_Survival"

data_subset2=data2$`Data CORR` %>% dplyr::count(I_Survival)  %>% drop_na()

count_num=function(X)
{
  if (length(data_subset1 %>% filter(I_Survival==X) %>% select(n) %>% pull())==0)
    n1=0
  if (length(data_subset1 %>% filter(I_Survival==X) %>% select(n) %>% pull())>0)
    n1=data_subset1 %>% filter(I_Survival==X) %>% select(n) %>% pull()

  if (length(data_subset2 %>% filter(I_Survival==X) %>% select(n) %>% pull())==0)
    n2=0
   if (length(data_subset2 %>% filter(I_Survival==X) %>% select(n) %>% pull())>0)
    n2=data_subset2 %>% filter(I_Survival==X) %>% select(n) %>% pull()

  
  return(n1+n2)
    
}

all_variable=union(data_subset1$I_Survival, data_subset2$I_Survival)
variable_count=sapply(all_variable, count_num)
data_subset=data_frame(I_Survival=all_variable, n=variable_count)


data_subset$I_Survival[data_subset$I_Survival==1]="yes";
data_subset$I_Survival[data_subset$I_Survival==2]="no";





data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2]%>% pull(), data_subset[j,2]%>% pull()), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```
