---
title: "12/18/2023"
output: html_document
date: "2023-12-18"
---

```{r, echo=F, message=F, warning=F, results=F}
source("C:/Shengtong/Research/AllCollaboration/Collaborations/analysis/Rfunctions.R")
data_raw=multiplesheets("C:\\Shengtong\\Research\\AllCollaboration\\2023\\202310\\Cem\\Dr Han Excel workbook-Hall SSC study.xlsx")
data=as_tibble(data_raw[[1]])
```


## survival analysis of SSCs 

### basic numbers 

```{r, echo=F, message=F, warning=F}
data_ssc_survival=data %>% filter(`SSC Placement Technique`==1 | `SSC Placement Technique`==2 ) %>% select(`SSC Placement Technique`, `6-month`, `12-month`, `18-month`, `24-month`, `30-month`, `36-month`, `42-month`, `48-month`, `54-month`, `60-month`, `66-month`)

time_point=c("6-month", "12-month", "18-month", "24-month", "30-month", "36-month", "42-month", "48-month", "54-month", "60-month", "66-month")
#time_point=seq(6,66,by=6)

TT=numeric()
HT=numeric()
for (i in 1:length(time_point))
{
  TT[i]=sum(data_ssc_survival %>% filter(`SSC Placement Technique`==1) %>% select(time_point[i]) %>% pull()==1) # count survivors at every time point  
  HT[i]=sum(data_ssc_survival %>% filter(`SSC Placement Technique`==2) %>% select(time_point[i]) %>% pull()==1)
}
time_point[1]="06-month"
TT_HT=data.frame(num_success=c(TT, HT), time_point= rep(time_point,2), technique=c(rep("TT", length(time_point)), rep("HT", length(time_point))))

ggplot(data = TT_HT, aes(x = time_point, y = num_success, fill = technique)) +
  geom_bar(stat = "identity", position = position_dodge(), alpha = 0.75)  +
  ylim(0,400) +
  geom_text(aes(label = num_success), fontface = "bold", vjust = 1.5, 
             position = position_dodge(.9), size = 4) +
  labs(x = "\n time ", y = "#. success:SSC=1\n", title = "\n  \n") +
  theme(plot.title = element_text(hjust = 0.5), 
        axis.title.x = element_text(face="bold", colour="red", size = 12),
        axis.title.y = element_text(face="bold", colour="red", size = 12),
        legend.title = element_text(face="bold", size = 10))+
   theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))

```
* only include HT and TT 


### Kaplan-Meier survival analyses 

```{r, echo=F, message=F, warning=F}
library(survival)


######## compute survival time for every tooth 
survival_time=numeric()
for (i in 1:nrow(data_ssc_survival))
  survival_time[i]=(sum(as.numeric(data_ssc_survival[i,2:12])==1)+1)*6 # survival time in months 

data_ssc_survival_complete=data_ssc_survival %>% add_column(survival_time=survival_time, status=rep(1, length(survival_time))) %>% drop_na()  
colnames(data_ssc_survival_complete)[1]="SSC_Placement_Technique"


s1 <- survfit(Surv(survival_time, status) ~ 1, data = data_ssc_survival_complete)
str(s1)
summary(s1)


survfit2(Surv(survival_time, status) ~ 1, data = data_ssc_survival_complete) %>% 
  ggsurvfit() +
  labs(
    x = "Months",
    y = "Overall survival probability"
  ) + 
  add_confidence_interval()+
  add_risktable()


colnames(data_ssc_survival_complete)[1]="SSC_Placement_Technique"
survfit2(Surv(survival_time, status) ~ SSC_Placement_Technique, data = data_ssc_survival_complete) %>% 
  ggsurvfit() +
  labs(
    x = "Months",
    y = "Overall survival probability"
  ) +
  add_confidence_interval()+
  add_risktable()

```
 

* [reference](https://www.emilyzabor.com/tutorials/survival_analysis_in_r_tutorial.html)

* `TT:SSC_Placement_Technique=1` vs `HT:SSC_Placement_Technique=2`

* `At Risk: No. survivals`, `Events: No.failures`


```{r, echo=F, message=F, warning=F}
 # comparing survival time between groups
survdiff(Surv(survival_time, status) ~ SSC_Placement_Technique, data = data_ssc_survival_complete)
```
* there is a significant difference in survival time between TT and HT  



