---
title: "11/14/2023"
output: html_document
date: "2023-11-14"
---





```{r, echo=F,message=F, warning=F, results=F}
source("C:/Shengtong/Research/AllCollaboration/Collaborations/analysis/Rfunctions.R")
data=multiplesheets("C:\\Shengtong\\Research\\AllCollaboration\\2023\\202311\\Holly\\All Data.xlsx")
```

## Inter-rater reliability-Cohen’s kappa

```{r, echo=F, message=F, warning=F}
kappa_pvalue=numeric()
kappa_value=numeric()
for (i in 1:length(data))
{
sub_data=data[[i]]
ratings=sub_data%>% select(`CVMS IH`, `CVMS 1D`) %>% drop_na()
kappa_test=kappa2(ratings, weight="squared")
kappa_value[i]=kappa_test$value
kappa_pvalue[i]=kappa_test$p.value
}
combine=bind_rows(data, .id = "column_label")
ratings=combine%>% select(`CVMS IH`, `CVMS 1D`) %>% drop_na()
kappa_test=kappa2(ratings, weight="squared")
kappa_value[i+1]=kappa_test$value
kappa_pvalue[i+1]=kappa_test$p.value



data.frame(sheet=c(names(data),"combine"), kappa_value=round(kappa_value,4), kappa_pvalue=pvalue_adjust(kappa_pvalue)) %>%
datatable(extensions = 'Buttons',
          caption = "CVMS IH vs CVMS 1D", 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```

* weighed Kappa test was used 

* [reference](https://www.andywills.info/rminr/irr.html)


```{r, echo=F, message=F, warning=F}
kappa_pvalue=numeric()
kappa_value=numeric()
for (i in 1:length(data))
{
sub_data=data[[i]]
ratings=sub_data%>% select(`CVMS 2H`, `CVMS 2D`) %>% drop_na()
kappa_test=kappa2(ratings, weight="squared")
kappa_value[i]=kappa_test$value
kappa_pvalue[i]=kappa_test$p.value
}
combine=bind_rows(data, .id = "column_label")
ratings=combine%>% select(`CVMS 2H`, `CVMS 2D`) %>% drop_na()
kappa_test=kappa2(ratings, weight="squared")
kappa_value[i+1]=kappa_test$value
kappa_pvalue[i+1]=kappa_test$p.value

data.frame(sheet=c(names(data), "combine"), kappa_value=round(kappa_value,4), kappa_pvalue=pvalue_adjust(kappa_pvalue)) %>%
datatable(extensions = 'Buttons',
          caption = "CVMS 2H vs CVMS 2D", 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```

## Intra-rater reliability 



### Kendall's W





```{r, echo=F, message=F, warning=F}

kendall_pvalue=numeric()
kendall_value=numeric()
for (i in 1:length(data))
{
sub_data=data[[i]]
ratings=sub_data%>% select(`CVMS IH`, `CVMS 2H`) %>% drop_na()
kendall_test=kendall(ratings,correct = FALSE)
kendall_pvalue[i]=kendall_test$p.value
kendall_value[i]=kendall_test$value
}
combine=bind_rows(data, .id = "column_label")
ratings=combine%>% select(`CVMS IH`, `CVMS 2H`) %>% drop_na()
kendal_test=kendall(ratings, correct = FALSE)
kendall_value[i+1]=kendall_test$value
kendall_pvalue[i+1]=kendall_test$p.value

data.frame(sheet=c(names(data), "combine"), kendall_value=round(kendall_value,4), kendall_pvalue=pvalue_adjust(kendall_pvalue)) %>%
datatable(extensions = 'Buttons',
          caption = "CVMS IH vs CVMS 2H", 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```




```{r, echo=F, message=F, warning=F}

kendall_pvalue=numeric()
kendall_value=numeric()
for (i in 1:length(data))
{
sub_data=data[[i]]
ratings=sub_data%>% select(`CVMS 1D`, `CVMS 2D`) %>% drop_na()
kendall_test=kendall(ratings,correct = FALSE)
kendall_pvalue[i]=kendall_test$p.value
kendall_value[i]=kendall_test$value
}

combine=bind_rows(data, .id = "column_label")
ratings=combine%>% select(`CVMS 1D`, `CVMS 2D`) %>% drop_na()
kendal_test=kendall(ratings, correct = FALSE)
kendall_value[i+1]=kendall_test$value
kendall_pvalue[i+1]=kendall_test$p.value

data.frame(sheet=c(names(data), "combine"), kendall_value=round(kendall_value,4), kendall_pvalue=pvalue_adjust(kendall_pvalue)) %>%
datatable(extensions = 'Buttons',
          caption = "CVMS 1D vs CVMS 2D", 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```




### ICC


```{r, echo=F, message=F, warning=F}

icc_pvalue=numeric()
icc_value=numeric()
for (i in 1:length(data))
{
sub_data=data[[i]]
ratings=sub_data%>% select(`CVMS IH`, `CVMS 2H`) %>% drop_na()
icc_test=icc(ratings, model ="oneway",  type = "consistency")
icc_pvalue[i]=icc_test$p.value
icc_value[i]=icc_test$value
}

combine=bind_rows(data, .id = "column_label")
ratings=combine%>% select(`CVMS IH`, `CVMS 2H`) %>% drop_na()
icc_test=icc(ratings, model ="oneway",  type = "consistency")
icc_value[i+1]=icc_test$value
icc_pvalue[i+1]=icc_test$p.value

data.frame(sheet=c(names(data), "combine"), icc_value=round(icc_value,4), icc_pvalue=pvalue_adjust(icc_pvalue)) %>%
datatable(extensions = 'Buttons',
          caption = "CVMS IH vs CVMS 2H", 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, echo=F, message=F, warning=F}

icc_pvalue=numeric()
icc_value=numeric()
for (i in 1:length(data))
{
sub_data=data[[i]]
ratings=sub_data%>% select(`CVMS 1D`, `CVMS 2D`) %>% drop_na()
icc_test=icc(ratings, model ="oneway",  type = "consistency")
icc_pvalue[i]=icc_test$p.value
icc_value[i]=icc_test$value
}

combine=bind_rows(data, .id = "column_label")
ratings=combine%>% select(`CVMS 1D`, `CVMS 2D`) %>% drop_na()
icc_test=icc(ratings, model ="oneway",  type = "consistency")
icc_value[i+1]=icc_test$value
icc_pvalue[i+1]=icc_test$p.value

data.frame(sheet=c(names(data), "combine"), icc_value=round(icc_value,4), icc_pvalue=pvalue_adjust(icc_pvalue)) %>%
datatable(extensions = 'Buttons',
          caption = "CVMS 1D vs CVMS 2D", 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



* [ICC test was used](https://www.r-bloggers.com/2021/06/intraclass-correlation-coefficient-in-r-quick-guide/) 




### repeated measure agreement-Concordance Correlation Coefficient



```{r, echo=F, message=F, warning=F}
library(SimplyAgree)

ccc_pvalue=numeric()
ccc_value=numeric()
for (i in 1:length(data))
{
sub_data=data[[i]]
ratings=sub_data%>% select(`CVMS IH`, `CVMS 2H`) %>% drop_na()
ccc_test=agree_test(x=ratings[,1],y=ratings[,2], agree.level = .8)
ccc_value[i]=ccc_test$ccc.xy[1]
}

combine=bind_rows(data, .id = "column_label")
ratings=combine%>% select(`CVMS IH`, `CVMS 2H`) %>% drop_na()
ccc_test=agree_test(x=ratings[,1],y=ratings[,2], agree.level = .8)
ccc_value[i+1]=ccc_test$ccc.xy[1]

data.frame(sheet=c(names(data), "combine"), ccc_value=round(unlist(ccc_value),4)) %>%
datatable(extensions = 'Buttons',
          caption = "CVMS IH vs CVMS 2H", 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, echo=F, message=F, warning=F}
library(SimplyAgree)

ccc_pvalue=numeric()
ccc_value=numeric()
for (i in 1:length(data))
{
sub_data=data[[i]]
ratings=sub_data%>% select(`CVMS 1D`, `CVMS 2D`) %>% drop_na()
ccc_test=agree_test(x=ratings[,1],y=ratings[,2], agree.level = .8)
#ccc_pvalue[i]=icc_test$p.value
ccc_value[i]=ccc_test$ccc.xy[1]
}

combine=bind_rows(data, .id = "column_label")
ratings=combine%>% select(`CVMS 1D`, `CVMS 2D`) %>% drop_na()
ccc_test=agree_test(x=ratings[,1],y=ratings[,2], agree.level = .8)
ccc_value[i+1]=ccc_test$ccc.xy[1]

data.frame(sheet=c(names(data), "combine"), ccc_value=round(unlist(ccc_value),4)) %>%
datatable(extensions = 'Buttons',
          caption = "CVMS 1D vs CVMS 2D", 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



* [reference](https://cran.r-project.org/web/packages/SimplyAgree/vignettes/agreement_analysis.html)


