---
title: "12/7/2023"
output: html_document
date: "2023-12-07"
---

```{r setup, include=FALSE}
rm(list=ls())
library(tidyverse)
library(kableExtra)
library(ggpubr)
library(rstatix) # use anova_test function 
library(grid)
library(DT)
library(gridExtra)
library(matrixStats)
library(cowplot)
library(readxl)
set.seed(123)
```




```{r, echo=F, warning=F, message=F}
######## adjust p values 
pvalue_adjust=function(p_value)
{
  p_value_adjust=numeric()
for (i in 1:length(p_value))
{
  if (is.na(p_value[i])==T)
    p_value_adjust[i]=p_value[i]
  if (is.na(p_value[i])==F & p_value[i]<0.0001)
    p_value_adjust[i]="<0.0001"
  if (is.na(p_value[i])==F & p_value[i]>0.0001)
    p_value_adjust[i]=round(p_value[i],4)
}
  return(p_value_adjust)
}
############### summary statistics for continuous variable 
summary_statistics=function(data)
{  # each column is one variable, and row one subject 
  
variables=colnames(data)
num_sample=numeric()
Mean=numeric()
Median=numeric()
SD=numeric()
SE=numeric()
range_min=numeric()
range_max=numeric()
normality_pvalue=numeric()
per_25_quantile=numeric()
per_75_quantile=numeric()

for (i in 1:ncol(data))
{
  observation=data[,i]
  observation=observation[!is.na(observation)] # remove missing values 
  num_sample[i]=length(observation)
  if (num_sample[i]>0)
  {
  Mean[i]=round(mean(observation),4)
  Median[i]=round(median(observation),4)
  SD[i]=round(sd(observation),4)
  SE[i]=round(SD[i]/sqrt(num_sample[i]),4)
  per_25_quantile[i]=round(quantile(observation, prob=0.25),4)
  per_75_quantile[i]=round(quantile(observation, prob=0.75),4)
  range_min[i]=round(min(observation),4)
  range_max[i]=round(max(observation),4)
  normality_pvalue[i]=round(shapiro.test(observation)$p.value,4)
  }
  if (num_sample[i]==0)
  {
  Mean[i]=NA
  Median[i]=NA
  SD[i]=NA
  SE[i]=NA
  per_25_quantile[i]=NA
  per_75_quantile[i]=NA
  range_min[i]=NA
  range_max[i]=NA
  normality_pvalue[i]=NA
  }
  
}

summary_data=data.frame(variable=variables, num_sample=num_sample, Mean=Mean, Median=Median, SD=SD, SE=SE,per_25_quantile, per_75_quantile, Range_low=range_min, Range_upper=range_max, normality_pvalue=normality_pvalue)

summary_data%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
  
 return(summary_data) 
}

multiplesheets <- function(fname) {
   
  # getting info about all excel sheets
  sheets <- readxl::excel_sheets(fname)
  tibble <- lapply(sheets, function(x) readxl::read_excel(fname, sheet = x))
  data_frame <- lapply(tibble, as.data.frame)
    
  # assigning names to data frames
  names(data_frame) <- sheets
    
  # print data frame
  print(data_frame)
}


```



```{r, echo=F, message=F, warning=F, results=F}
data=read_xlsx("C:\\Shengtong\\Research\\AllCollaboration\\2023\\202312\\Jenna\\Jenna Data for Statistics.xlsx")
```


## Sleeve vs Sleeveless 

```{r, echo=F, message=F, warning=F}
parameters=colnames(data)[3:12]
pvalue=numeric()

for (i in 1:length(parameters))
{
  #i=1
  sample1=data %>% filter(methods=="Sleeve") %>% select(parameters[i]) %>% pull()
  sample2=data %>% filter(methods=="Sleeveless") %>% select(parameters[i]) %>% pull()
  pvalue[i]=t.test(sample1, sample2)$p.value
}

data.frame(parameters=parameters, pvalue=pvalue_adjust(pvalue))%>%
datatable(extensions = 'Buttons',
          caption=" Sleeve vs Sleeveless",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

* two sample t test was used. 
