---
title: "09/25 2023"
output: html_document
date: "2023-09-25"
---


```{r setup, include=FALSE}
rm(list=ls())
library(tidyverse)
library(kableExtra)
library(ggpubr)
library(rstatix) # use anova_test function 
library(grid)
library(DT)
library(gridExtra)
library(matrixStats)
library(cowplot)
library(readxl)
set.seed(123)
```




```{r, echo=F, warning=F, message=F}
######## adjust p values 
pvalue_adjust=function(p_value)
{
  p_value_adjust=numeric()
for (i in 1:length(p_value))
{
  if (is.na(p_value[i])==T)
    p_value_adjust[i]=p_value[i]
  if (is.na(p_value[i])==F & p_value[i]<0.0001)
    p_value_adjust[i]="<0.0001"
  if (is.na(p_value[i])==F & p_value[i]>0.0001)
    p_value_adjust[i]=round(p_value[i],4)
}
  return(p_value_adjust)
}
############### summary statistics for continuous variable 
summary_statistics=function(data)
{  # each column is one variable, and row one subject 
  
variables=colnames(data)
num_sample=numeric()
Mean=numeric()
Median=numeric()
SD=numeric()
SE=numeric()
range_min=numeric()
range_max=numeric()
normality_pvalue=numeric()
per_25_quantile=numeric()
per_75_quantile=numeric()

for (i in 1:ncol(data))
{
  observation=data[,i]
  observation=observation[!is.na(observation)] # remove missing values 
  num_sample[i]=length(observation)
  if (num_sample[i]>0)
  {
  Mean[i]=round(mean(observation),4)
  Median[i]=round(median(observation),4)
  SD[i]=round(sd(observation),4)
  SE[i]=round(SD[i]/sqrt(num_sample[i]),4)
  per_25_quantile[i]=round(quantile(observation, prob=0.25),4)
  per_75_quantile[i]=round(quantile(observation, prob=0.75),4)
  range_min[i]=round(min(observation),4)
  range_max[i]=round(max(observation),4)
  normality_pvalue[i]=round(shapiro.test(observation)$p.value,4)
  }
  if (num_sample[i]==0)
  {
  Mean[i]=NA
  Median[i]=NA
  SD[i]=NA
  SE[i]=NA
  per_25_quantile[i]=NA
  per_75_quantile[i]=NA
  range_min[i]=NA
  range_max[i]=NA
  normality_pvalue[i]=NA
  }
  
}

summary_data=data.frame(variable=variables, num_sample=num_sample, Mean=Mean, Median=Median, SD=SD, SE=SE,per_25_quantile, per_75_quantile, Range_low=range_min, Range_upper=range_max, normality_pvalue=normality_pvalue)

summary_data%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
  
 return(summary_data) 
}

multiplesheets <- function(fname) {
   
  # getting info about all excel sheets
  sheets <- readxl::excel_sheets(fname)
  tibble <- lapply(sheets, function(x) readxl::read_excel(fname, sheet = x))
  data_frame <- lapply(tibble, as.data.frame)
    
  # assigning names to data frames
  names(data_frame) <- sheets
    
  # print data frame
  print(data_frame)
}


```




```{r, echo=F, message=F, warning=F, results=F}
data2=multiplesheets("C:\\Shengtong\\Research\\AllCollaboration\\2023\\202309\\Teerarat\\Peri-Implant DATA CLEAN 111023_without_header.xlsx")
```




## summary statistics 

### CORR

```{r, echo=F, message=F, warning=F}
group_corr=data2$`Data CORR`

num_indi=24
Data=group_corr
Age=as.numeric(Data$Age[1:num_indi])
CBL_diagnosis_months=as.numeric(Data$CBL_diagnosis_months)[1:num_indi]
I_Torque=as.numeric(Data$I_Torque)[1:num_indi]
I_Diameter=as.numeric(Data$I_Diameter)[1:num_indi]
I_Length=as.numeric(Data$I_Length)[1:num_indi]
Time_comp_days=as.numeric(Data$Time_comp_days)[1:num_indi]
Bone_loss_mm=as.numeric(Data$Bone_loss_mm)[1:num_indi]
Bone_loss_percentage=as.numeric(Data$`Bone_loss_%`)[1:num_indi]
Bone_loss_crest=as.numeric(Data$Bone_loss_crest)[1:num_indi]
Bone_loss_post_regen_mm=as.numeric(Data$Bone_loss_post_regen_mm)[1:num_indi]
Bone_loss_post_regen_percentage=as.numeric(Data$`Bone_loss_post_regen_%`)[1:num_indi]
Month_post_regen=as.numeric(Data$Month_post_regen)[1:num_indi]
RTR_post_regen_IP=as.numeric(Data$RTR_post_regen_IP)[1:num_indi]
RTR_post_regen_CRP=as.numeric(Data$RTR_post_regen_CRP)[1:num_indi]
Time_comp_post_regen=as.numeric(Data$Time_comp_post_regen)[1:num_indi]
Post_cr_del_months=as.numeric(Data$Post_cr_del_months)[1:num_indi]
Latest_bone_levels_mm=as.numeric(Data$Latest_bone_levels_mm)[1:num_indi]
Latest_bone_levels_percentage=as.numeric(Data$`Latest_bone_levels_%`)[1:num_indi]

data_interest=data.frame(Age, CBL_diagnosis_months, I_Torque, I_Diameter, I_Length, Time_comp_days, Bone_loss_mm, Bone_loss_percentage, Bone_loss_crest, Bone_loss_post_regen_mm, Bone_loss_post_regen_percentage, Month_post_regen, RTR_post_regen_IP,RTR_post_regen_CRP, Time_comp_post_regen, Post_cr_del_months, Latest_bone_levels_mm, Latest_bone_levels_percentage )

data_summary=summary_statistics(data_interest)
data_summary %>%
datatable(extensions = 'Buttons',
          caption = "CORR",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```


* `num_sample` numeric samples after removing NA's  




### restore 

```{r, echo=F, message=F, warning=F}
group_restore=data2$`Data RESTORE`

num_indi=55
Data=group_restore
Age=as.numeric(Data$Age[1:num_indi])
CBL_diagnosis_months=as.numeric(Data$CBL_diagnosis_months)[1:num_indi]
I_Torque=as.numeric(Data$I_Torque)[1:num_indi]
I_Diameter=as.numeric(Data$I_Diameter)[1:num_indi]
I_Length=as.numeric(Data$I_Length)[1:num_indi]
Time_comp_days=as.numeric(Data$Time_comp_days)[1:num_indi]
Bone_loss_mm=as.numeric(Data$Bone_loss_mm)[1:num_indi]
Bone_loss_percentage=as.numeric(Data$`Bone_loss_%`)[1:num_indi]
Bone_loss_crest=as.numeric(Data$Bone_loss_crest)[1:num_indi]
Bone_loss_post_regen_mm=as.numeric(Data$Bone_loss_post_regen_mm)[1:num_indi]
Bone_loss_post_regen_percentage=as.numeric(Data$`Bone_loss_post_regen_%`)[1:num_indi]
Month_post_regen=as.numeric(Data$Month_post_regen)[1:num_indi]
RTR_post_regen_IP=as.numeric(Data$RTR_post_regen_IP)[1:num_indi]
RTR_post_regen_CRP=as.numeric(Data$RTR_post_regen_CRP)[1:num_indi]
Time_comp_post_regen=as.numeric(Data$Time_comp_post_regen)[1:num_indi]
Post_cr_del_months=as.numeric(Data$Post_cr_del_months)[1:num_indi]
Latest_bone_levels_mm=as.numeric(Data$Latest_bone_levels_mm)[1:num_indi]
Latest_bone_levels_percentage=as.numeric(Data$`Latest_bone_levels_%`)[1:num_indi]

data_interest=data.frame(Age, CBL_diagnosis_months, I_Torque, I_Diameter, I_Length, Time_comp_days, Bone_loss_mm, Bone_loss_percentage, Bone_loss_crest, Bone_loss_post_regen_mm, Bone_loss_post_regen_percentage, Month_post_regen, RTR_post_regen_IP,RTR_post_regen_CRP, Time_comp_post_regen, Post_cr_del_months, Latest_bone_levels_mm, Latest_bone_levels_percentage )

data_summary=summary_statistics(data_interest)
data_summary %>%
datatable(extensions = 'Buttons',
          caption = "restore",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```


```{r, echo=F, message=F, warning=F, results=F}
data=multiplesheets("C:\\Shengtong\\Research\\AllCollaboration\\2023\\202309\\Teerarat\\Early peri-implant bone loss CORRECTIVE TREATMENT) VK092423.xlsx")

num_indi=24
Age=data$Data$Age[1:num_indi]
CBL_diagnosis_months=as.numeric(data$Data$CBL_diagnosis_months)[1:num_indi]
I_Torque=as.numeric(data$Data$I_Torque)[1:num_indi]
I_Diameter=as.numeric(data$Data$I_Diameter)[1:num_indi]
I_Length=as.numeric(data$Data$I_Length)[1:num_indi]
Bone_loss_mm=as.numeric(data$Data$Bone_loss_mm)[1:num_indi]
Bone_loss_percentage=as.numeric(data$Data$`Bone_loss_%`)[1:num_indi]
Bone_loss_post_regen_mm=as.numeric(data$Data$Bone_loss_post_regen_mm)[1:num_indi]
Bone_loss_post_regen_percentage=as.numeric(data$Data$`Bone_loss_post_regen_%`)[1:num_indi]
Month_post_regen=as.numeric(data$Data$Month_post_regen)[1:num_indi]
data2=data.frame(Age, CBL_diagnosis_months, I_Torque, I_Diameter, I_Length, Bone_loss_mm, Bone_loss_percentage, Bone_loss_post_regen_mm, Bone_loss_post_regen_percentage, Month_post_regen)
```



## summary statistics 

```{r, echo=F, message=F, warning=F}
data_summary=summary_statistics(data2)
data_summary %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```


## data distribution 


```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(Gender) %>% mutate(prop=n/24)
data_subset$Gender[data_subset$Gender==1]="Male"; data_subset$Gender[data_subset$Gender==2]="Female"
g1=ggplot(data_subset, aes(x=Gender, y=prop, fill=Gender)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1

pvalue=round(binom.test(data_subset$n, p = 0.5)$p.value,4)
  
  g2=ggplot(data_subset, aes(x=Gender, y=n, fill=Gender)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
    geom_signif(annotations ="p=0.541", y_position = 15  ,xmin=1, xmax=2, size=1, vjust=-0.5, textsize=3)+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("count")+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("Gender", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)
############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

* binomial exact test was used to compute p values 


```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(Smoking) %>% mutate(prop=n/24)
data_subset$Smoking[data_subset$Smoking==1]="Never"; data_subset$Smoking[data_subset$Smoking==2]="Past"
data_subset$Smoking[data_subset$Smoking==3]="Current"; data_subset$Smoking[data_subset$Smoking==4]="not reported
"


g1=ggplot(data_subset, aes(x=Smoking, y=prop, fill=Smoking)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 30, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1

pvalue1=round(binom.test(c(12,7), p = 0.5)$p.value,4)
pvalue2=round(binom.test(c(7,3), p = 0.5)$p.value,4)
pvalue3=round(binom.test(c(12,3), p = 0.5)$p.value,4)

  g2=ggplot(data_subset, aes(x=Smoking, y=n, fill=Smoking)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 30, vjust = 0.5, size=10))+
  ylab("count")+
    xlab("")+
     geom_signif(annotations ="p=0.035", y_position = 13.5  ,xmin=1, xmax=1.9, size=1, vjust=-0.5, textsize=3, col="red")+
    geom_signif(annotations ="p=0.359", y_position = 13.5  ,xmin=2.1, xmax=4, size=1, vjust=-0.5, textsize=3)+
    geom_signif(annotations ="p=0.344", y_position = 15  ,xmin=1, xmax=4, size=1, vjust=-0.5, textsize=3)+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("Smoking", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```

```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(Diabetes) %>% mutate(prop=n/24)
data_subset$Diabetes[data_subset$Diabetes==1]="Yes"; data_subset$Diabetes[data_subset$Diabetes==2]="No"



g1=ggplot(data_subset, aes(x=Diabetes, y=prop, fill=Diabetes)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1


pvalue1=round(binom.test(c(15,9), p = 0.5)$p.value,4)

  g2=ggplot(data_subset, aes(x=Diabetes, y=n, fill=Diabetes)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("count")+
    xlab("")+
    geom_signif(annotations ="p=0.308", y_position = 16  ,xmin=1, xmax=2, size=1, vjust=-0.5, textsize=3, col="black")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("Diabetes", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(Implant_site) %>% mutate(prop=n/24)
index1=which(data_subset$Implant_site<=16); index2=which(data_subset$Implant_site>16)
n=c(sum(data_subset$n[index1]), sum(data_subset$n[index2]))
prop=c(sum(data_subset$prop[index1]), sum(data_subset$prop[index2]))
data_subset2=data.frame(Implant_site=c("Maxilla", "Mandible"), n=n, prop=prop)


g1=ggplot(data_subset2, aes(x=Implant_site, y=prop, fill=Implant_site)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1


pvalue1=round(binom.test(c(6,18), p = 0.5)$p.value,4)

  g2=ggplot(data_subset2, aes(x=Implant_site, y=n, fill=Implant_site)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("count")+
    xlab("")+
    geom_signif(annotations ="p=0.023", y_position = 19.5  ,xmin=1, xmax=2, size=1, vjust=-0.5, textsize=3, col="red")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("Implant_site", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset2)-1))
  for (j in (i+1):nrow(data_subset2))
  {
    k=k+1
    parameters[k]=paste(data_subset2[i,1], data_subset2[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset2[i,2], data_subset2[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(Implant_site) %>% mutate(prop=n/24)
index1=union(which(data_subset$Implant_site<=5), which(data_subset$Implant_site<=16 & data_subset$Implant_site>=12)); index2=which(data_subset$Implant_site>=6 &data_subset$Implant_site<=11);
index3=union(which(data_subset$Implant_site>=17 & data_subset$Implant_site<=21), which(data_subset$Implant_site<=31 & data_subset$Implant_site>=28));
index4=which(data_subset$Implant_site>=22 &data_subset$Implant_site<=27 )

n=c(sum(data_subset$n[index1]), sum(data_subset$n[index2]), sum(data_subset$n[index3]), sum(data_subset$n[index4]))
prop=c(sum(data_subset$prop[index1]), sum(data_subset$prop[index2]), sum(data_subset$prop[index3]), sum(data_subset$prop[index4]))
data_subset2=data.frame(Implant_site=c("Upper posterior", "Upper anterior", "Lower posterior", "Lower anterior"), n=n, prop=prop)


g1=ggplot(data_subset2, aes(x=Implant_site, y=prop, fill=Implant_site)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 30, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1

pvalue1=round(binom.test(c(4,14), p = 0.5)$p.value,4)
pvalue2=round(binom.test(c(4,14), p = 0.5)$p.value,4)
pvalue3=round(binom.test(c(2,14), p = 0.5)$p.value,4)
pvalue4=round(binom.test(c(4,4), p = 0.5)$p.value,4)
pvalue5=round(binom.test(c(2,4), p = 0.5)$p.value,4)
pvalue6=round(binom.test(c(2,4), p = 0.5)$p.value,4)

  g2=ggplot(data_subset2, aes(x=Implant_site, y=n, fill=Implant_site)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 30, vjust = 0.5, size=10))+
  ylab("count")+
    xlab("")+
    geom_signif(annotations ="p=0.031", y_position = 15  ,xmin=3, xmax=4, size=1, vjust=-0.5, textsize=3, col="red")+
    geom_signif(annotations ="p=0.031", y_position = 16  ,xmin=2, xmax=4, size=1, vjust=-0.5, textsize=3, col="red")+
    geom_signif(annotations ="p=0.004", y_position = 17  ,xmin=1, xmax=4, size=1, vjust=-0.5, textsize=3, col="red")+
    geom_signif(annotations ="p=1.000", y_position = 6  ,xmin=2, xmax=3, size=1, vjust=-0.5, textsize=3, col="black")+
    geom_signif(annotations ="p=0.689", y_position = 7  ,xmin=1, xmax=3, size=1, vjust=-0.5, textsize=3, col="black")+
    geom_signif(annotations ="p=0.689", y_position = 5.2  ,xmin=1, xmax=2, size=1, vjust=-0.5, textsize=3, col="black")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("Implant_site", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset2)-1))
  for (j in (i+1):nrow(data_subset2))
  {
    k=k+1
    parameters[k]=paste(data_subset2[i,1], data_subset2[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset2[i,2], data_subset2[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```




```{r, echo=F, message=F, warning=F}
data$Data$Pre_implant_Procedure[1]=1
data_subset=data$Data %>% dplyr::count(Pre_implant_Procedure) %>% mutate(prop=n/24)

data_subset$Pre_implant_Procedure[data_subset$Pre_implant_Procedure==1]="Extraction alone"; data_subset$Pre_implant_Procedure[data_subset$Pre_implant_Procedure==2]="Extraction and bone graft"; 
data_subset$Pre_implant_Procedure[data_subset$Pre_implant_Procedure==3]="Extraction, bone graft and membrane";
data_subset$Pre_implant_Procedure[data_subset$Pre_implant_Procedure==4]="GBR";
data_subset$Pre_implant_Procedure[data_subset$Pre_implant_Procedure==7]="not reported";



g1=ggplot(data_subset, aes(x=Pre_implant_Procedure, y=prop, fill=Pre_implant_Procedure)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 60, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1

pvalue1=round(binom.test(c(4,1), p = 0.5)$p.value,4)
pvalue2=round(binom.test(c(6,4), p = 0.5)$p.value,4)
pvalue3=round(binom.test(c(6,1), p = 0.5)$p.value,4)
pvalue4=round(binom.test(c(9,4), p = 0.5)$p.value,4)
pvalue5=round(binom.test(c(9,1), p = 0.5)$p.value,4)
pvalue6=round(binom.test(c(9,6), p = 0.5)$p.value,4)


  g2=ggplot(data_subset, aes(x=Pre_implant_Procedure, y=n, fill=Pre_implant_Procedure)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 60, vjust = 0.5, size=10))+
  ylab("count")+ylim(c(0, max(data_subset$n)+6))+
    xlab("")+
    geom_signif(annotations ="p=0.375", y_position = 5.5  ,xmin=3.1, xmax=4, size=1, vjust=-0.5, textsize=2, col="black")+
    geom_signif(annotations ="p=0.375", y_position = 5.5  ,xmin=2, xmax=2.9, size=1, vjust=-0.5, textsize=2, col="black")+
    geom_signif(annotations ="p=1.000", y_position = 6.5  ,xmin=2, xmax=4, size=1, vjust=-0.5, textsize=2, col="black")+
    geom_signif(annotations ="p=0.754", y_position = 7.5  ,xmin=1, xmax=2, size=1, vjust=-0.5, textsize=2, col="black")+
    geom_signif(annotations ="p=0.125", y_position = 8.5  ,xmin=1, xmax=3, size=1, vjust=-0.5, textsize=2, col="black")+
    geom_signif(annotations ="p=0.754", y_position = 9.5  ,xmin=1, xmax=4, size=1, vjust=-0.5, textsize=2, col="black")+
    geom_signif(annotations ="p=0.267", y_position = 10.5  ,xmin=4, xmax=5, size=1, vjust=-0.5, textsize=2, col="black")+
    geom_signif(annotations ="p=0.022", y_position = 12  ,xmin=3, xmax=5, size=1, vjust=-0.5, textsize=2, col="red")+
    geom_signif(annotations ="p=0.267", y_position = 13  ,xmin=2, xmax=5, size=1, vjust=-0.5, textsize=2, col="black")+
    geom_signif(annotations ="p=0.607", y_position = 14  ,xmin=1, xmax=5, size=1, vjust=-0.5, textsize=2, col="black")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("Pre_implant_Procedure", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```




```{r, echo=F, message=F, warning=F}
data$Data$I_placement[6]="4"
data_subset=data$Data %>% dplyr::count(I_placement) %>% mutate(prop=n/24)

data_subset$I_placement[data_subset$I_placement==1]="Single implant placement"; data_subset$I_placement[data_subset$I_placement==2]="Placement with bone graft"; 
data_subset$I_placement[data_subset$I_placement==4]="Placement with bone graft and membrane";
data_subset$I_placement[data_subset$I_placement==5]="Placement with indirect sinus lift";
data_subset$I_placement[data_subset$I_placement==7]="Immediate/delayed placement";
data_subset$I_placement[data_subset$I_placement==8]="other";


g1=ggplot(data_subset, aes(x=I_placement, y=prop, fill=I_placement)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 60, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1


pvalue1=round(binom.test(c(13,3), p = 0.5)$p.value,4)
pvalue2=round(binom.test(c(13,4), p = 0.5)$p.value,4)
pvalue3=round(binom.test(c(13,1), p = 0.5)$p.value,4)
pvalue4=round(binom.test(c(13,2), p = 0.5)$p.value,4)
pvalue5=round(binom.test(c(9,1), p = 0.5)$p.value,4)
pvalue6=round(binom.test(c(9,6), p = 0.5)$p.value,4)

  g2=ggplot(data_subset, aes(x=I_placement, y=n, fill=I_placement)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 60, vjust = 0.5, size=10))+
  ylab("count")+ylim(c(0, max(data_subset$n)+8))+
    xlab("")+
    geom_signif(annotations ="p=0.021", y_position = 15  ,xmin=5, xmax=6, size=1, vjust=-0.5, textsize=2, col="red")+
    geom_signif(annotations ="p=0.049", y_position = 16.5  ,xmin=4, xmax=6, size=1, vjust=-0.5, textsize=2, col="red")+
    geom_signif(annotations ="p=0.002", y_position = 18  ,xmin=3, xmax=6, size=1, vjust=-0.5, textsize=2, col="red")+
    geom_signif(annotations ="p=0.007", y_position = 19.5  ,xmin=1, xmax=6, size=1, vjust=-0.5, textsize=2, col="red")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("I_placement", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(HA) %>% mutate(prop=n/24)

data_subset$HA[data_subset$HA==1]="yes"; 
data_subset$HA[data_subset$HA==2]="no"; 


g1=ggplot(data_subset, aes(x=HA, y=prop, fill=HA)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
pvalue1=round(binom.test(c(21,3), p = 0.5)$p.value,4)

  g2=ggplot(data_subset, aes(x=HA, y=n, fill=HA)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("count")+ylim(c(0, max(data_subset$n)+2))+
    xlab("")+
    geom_signif(annotations ="p<0.001", y_position = 23  ,xmin=1, xmax=2, size=1, vjust=-0.5, textsize=3, col="red")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("HA", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```

```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(I_Brand) %>% mutate(prop=n/24)

data_subset$I_Brand[data_subset$I_Brand==3]="Straumann BLT"; 
data_subset$I_Brand[data_subset$I_Brand==4]="Osseospeed Ev"; 
data_subset$I_Brand[data_subset$I_Brand==5]="Nobel Replace Connical Connection";
data_subset$I_Brand[data_subset$I_Brand==6]="Atra EV";
data_subset$I_Brand[data_subset$I_Brand==7]="BioHorizons Tapered Plus";
data_subset$I_Brand[data_subset$I_Brand==8]="Nobel Replace Select";
data_subset$I_Brand[data_subset$I_Brand==9]="Nobel Replace Tapered Groovy";

g1=ggplot(data_subset, aes(x=I_Brand, y=prop, fill=I_Brand)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 60, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(data_subset, aes(x=I_Brand, y=n, fill=I_Brand)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 60, vjust = 0.5, size=10))+
  ylab("count")+ylim(c(0, max(data_subset$n)+2))+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("I_Brand", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```




```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(I_Surface) %>% mutate(prop=n/24)

data_subset$I_Surface[data_subset$I_Surface==2]="TiUnite"; 
data_subset$I_Surface[data_subset$I_Surface==3]="SLA";
data_subset$I_Surface[data_subset$I_Surface==4]="TiO2";
data_subset$I_Surface[data_subset$I_Surface==5]="Ti";
data_subset$I_Surface[data_subset$I_Surface==6]="TLXP3812";
data_subset$I_Surface[data_subset$I_Surface==7]="Tiu"; 

g1=ggplot(data_subset, aes(x=I_Surface, y=prop, fill=I_Surface)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 30, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(data_subset, aes(x=I_Surface, y=n, fill=I_Surface)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 30, vjust = 0.5, size=10))+
  ylab("count")+ylim(c(0, max(data_subset$n)+2))+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("I_Surface", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(I_Shape) %>% mutate(prop=n/24)

data_subset$I_Shape[data_subset$I_Shape==1]="straight"; 
data_subset$I_Shape[data_subset$I_Shape==2]="tapered"; 


g1=ggplot(data_subset, aes(x=I_Shape, y=prop, fill=I_Shape)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(data_subset, aes(x=I_Shape, y=n, fill=I_Shape)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("count")+ylim(c(0, max(data_subset$n)+2))+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("I_Shape", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, echo=F, message=F, warning=F}
data$Data$I_Technique[data$Data$I_Technique=="NR"]=5
data_subset=data$Data %>% dplyr::count(I_Technique) %>% mutate(prop=n/24)

data_subset$I_Technique[data_subset$I_Technique==1]="Free handed"; 
data_subset$I_Technique[data_subset$I_Technique==2]="Pilot guided";
data_subset$I_Technique[data_subset$I_Technique==3]="Fully guided";
data_subset$I_Technique[data_subset$I_Technique==5]="NR"; 



g1=ggplot(data_subset, aes(x=I_Technique, y=prop, fill=I_Technique)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 30, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(data_subset, aes(x=I_Technique, y=n, fill=I_Technique)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 30, vjust = 0.5, size=10))+
  ylab("count")+ylim(c(0, max(data_subset$n)+2))+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("I_Technique", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(I_Location) %>% mutate(prop=n/24)

data_subset$I_Location[data_subset$I_Location==2]="Equicrestal"; 
data_subset$I_Location[data_subset$I_Location==3]="Subcrestal"; 


g1=ggplot(data_subset, aes(x=I_Location, y=prop, fill=I_Location)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(data_subset, aes(x=I_Location, y=n, fill=I_Location)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("count")+ylim(c(0, max(data_subset$n)+2))+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("I_Location", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```

```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(Present_comp_post_placement) %>% mutate(prop=n/24)

data_subset$Present_comp_post_placement[data_subset$Present_comp_post_placement==1]="yes"; 
data_subset$Present_comp_post_placement[data_subset$Present_comp_post_placement==2]="no"; 


g1=ggplot(data_subset, aes(x=Present_comp_post_placement, y=prop, fill=Present_comp_post_placement)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(data_subset, aes(x=Present_comp_post_placement, y=n, fill=Present_comp_post_placement)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("count")+ylim(c(0, max(data_subset$n)+2))+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("Present_comp_post_placement", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(Coverscrew_exp_post_placement) %>% mutate(prop=n/24)

data_subset$Coverscrew_exp_post_placement[data_subset$Coverscrew_exp_post_placement==1]="yes"; 
data_subset$Coverscrew_exp_post_placement[data_subset$Coverscrew_exp_post_placement==2]="no"; 


g1=ggplot(data_subset, aes(x=Coverscrew_exp_post_placement, y=prop, fill=Coverscrew_exp_post_placement)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(data_subset, aes(x=Coverscrew_exp_post_placement, y=n, fill=Coverscrew_exp_post_placement)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("count")+ylim(c(0, max(data_subset$n)+2))+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("Coverscrew_exp_post_placement", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(`Infection/pus_post_placement`) %>% mutate(prop=n/24)

data_subset$`Infection/pus_post_placement`[data_subset$`Infection/pus_post_placement`==1]="yes"; 
data_subset$`Infection/pus_post_placement`[data_subset$`Infection/pus_post_placement`==2]="no"; 


g1=ggplot(data_subset, aes(x=`Infection/pus_post_placement`, y=prop, fill=`Infection/pus_post_placement`)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(data_subset, aes(x=`Infection/pus_post_placement`, y=n, fill=`Infection/pus_post_placement`)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("count")+ylim(c(0, max(data_subset$n)+2))+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("`Infection/pus_post_placement`", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(abscess_post_placement) %>% mutate(prop=n/24)

data_subset$abscess_post_placement[data_subset$abscess_post_placement==1]="yes"; 
data_subset$abscess_post_placement[data_subset$abscess_post_placement==2]="no"; 


g1=ggplot(data_subset, aes(x=abscess_post_placement, y=prop, fill=abscess_post_placement)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(data_subset, aes(x=abscess_post_placement, y=n, fill=abscess_post_placement)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("count")+ylim(c(0, max(data_subset$n)+2))+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("abscess_post_placement", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(sinus_post_placement) %>% mutate(prop=n/24)

data_subset$sinus_post_placement[data_subset$sinus_post_placement==1]="yes"; 
data_subset$sinus_post_placement[data_subset$sinus_post_placement==2]="no"; 


g1=ggplot(data_subset, aes(x=sinus_post_placement, y=prop, fill=sinus_post_placement)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(data_subset, aes(x=sinus_post_placement, y=n, fill=sinus_post_placement)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("count")+ylim(c(0, max(data_subset$n)+2))+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("sinus_post_placement", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```
```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(swell_post_placement) %>% mutate(prop=n/24)

data_subset$swell_post_placement[data_subset$swell_post_placement==1]="yes"; 
data_subset$swell_post_placement[data_subset$swell_post_placement==2]="no"; 


g1=ggplot(data_subset, aes(x=swell_post_placement, y=prop, fill=swell_post_placement)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(data_subset, aes(x=swell_post_placement, y=n, fill=swell_post_placement)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("count")+ylim(c(0, max(data_subset$n)+2))+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("swell_post_placement", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(pain_post_placement) %>% mutate(prop=n/24)

data_subset$pain_post_placement[data_subset$pain_post_placement==1]="yes"; 
data_subset$pain_post_placement[data_subset$pain_post_placement==2]="no"; 


g1=ggplot(data_subset, aes(x=pain_post_placement, y=prop, fill=pain_post_placement)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(data_subset, aes(x=pain_post_placement, y=n, fill=pain_post_placement)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("count")+ylim(c(0, max(data_subset$n)+2))+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("pain_post_placement", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(Type_bone_loss) %>% mutate(prop=n/24)

data_subset$Type_bone_loss[data_subset$Type_bone_loss==1]="vertical"; 
data_subset$Type_bone_loss[data_subset$Type_bone_loss==2]="horizontal"; 


g1=ggplot(data_subset, aes(x=Type_bone_loss, y=prop, fill=Type_bone_loss)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(data_subset, aes(x=Type_bone_loss, y=n, fill=Type_bone_loss)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, size=10))+
  ylab("count")+ylim(c(0, max(data_subset$n)+2))+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("Type_bone_loss", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



```{r, echo=F, message=F, warning=F}
data_subset=data$Data %>% dplyr::count(Corr_regen_procedure) %>% mutate(prop=n/24)

data_subset$Corr_regen_procedure[data_subset$Corr_regen_procedure==1]="Debridement alone"; 
data_subset$Corr_regen_procedure[data_subset$Corr_regen_procedure==3]="Debridement with bone graft";
data_subset$Corr_regen_procedure[data_subset$Corr_regen_procedure==4]="Debridement with bone graft and membrane";
data_subset$Corr_regen_procedure[data_subset$Corr_regen_procedure==7]="Debridement with bone graft, membrane, and biologics";
data_subset$Corr_regen_procedure[data_subset$Corr_regen_procedure==8]="other";


g1=ggplot(data_subset, aes(x=Corr_regen_procedure, y=prop, fill=Corr_regen_procedure)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, size=7))+
  ylab("%")+ylim(c(0,1))+
    xlab("")+
  geom_text(aes(label=round(prop,4)*100), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
  #ggtitle(paste(questions[i]))+
  #theme(plot.title = element_text(hjust = 0.5, size=10))  #center the title 
#g1
  g2=ggplot(data_subset, aes(x=Corr_regen_procedure, y=n, fill=Corr_regen_procedure)) +geom_bar(stat="identity")+
  theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, size=7))+
  ylab("count")+ylim(c(0, max(data_subset$n)+2))+
    xlab("")+
  geom_text(aes(label=n), position=position_dodge(width=0.6), vjust=-0.25, size=4)#+  # add numbers over bars
#questions[1]
  figure=ggarrange(g1, g2, common.legend = TRUE, legend="none") 
annotate_figure(figure,
                top = text_grob("Corr_regen_procedure", color = "red", face = "bold", size = 14),
#                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
#                                   hjust = 1, x = 1, face = "italic", size = 10),
#                left = text_grob("Tooth length", color = "green", rot = 90),
#                right = "I'm done, thanks :-)!",
#                fig.lab = "Figure 1", fig.lab.face = "bold"
)

############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```
