---
title: "2024/10/07"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2024-10-07"
---



```{r, echo=F, message=F, warning=F}
source("C:/Shengtong/Research/AllCollaboration/Collaborations/analysis/Rfunctions.R")
```


```{r, message=F, warning=F, results=F}
#data_raw=multiplesheets("C:\\Shengtong\\Research\\AllCollaboration\\2024\\202410\\Neal\\CBCT Thesis data FINAL VK111324.xlsx")
#finalized_data=data_raw$`Finalized Data`
#finalized_with_omitted_data=data_raw$`Finalized with Omitted data`
#coding=data_raw$`Coding`
#save(finalized_with_omitted_data, finalized_data, coding, file="C:\\Shengtong\\Research\\AllCollaboration\\2024\\202410\\Neal\\data.RData")
load("C:\\Shengtong\\Research\\AllCollaboration\\2024\\202410\\Neal\\data.RData")
col_names=as.character(finalized_data[1,])
finalized_data=finalized_data[-c(1,2),]

colnames(finalized_data)=col_names
```



```{r, message=F, warning=F}
upper_posterior=c(2, 3, 4, 5, 12, 13, 14, 15)
upper_anterior=6:11
lower_posterior=c(18, 19, 20, 21, 28, 29, 30, 31)
lower_anterior=22:27
```





## Finalized data 


```{r, message=F, warning=F}

colnames(finalized_data)
```




### continuous variables 

```{r, message=F, warning=F, eval=T}
continuous_var=c("Age", 
"Months_btwn_CBCTS",  
"Months_btwn_Ext_CBCT#1",
"mesial_tooth_bone_loss_CBCT#2__mm",   
"mesial_tooth_bone_loss_DIFF", 
"mesial_tooth_bone_loss_CBCT#1__mm",
"distal_tooth_bone_loss_CBCT#1__mm",    
"distal_tooth_bone_loss_CBCT#2__mm",   
"distal_tooth_bone_loss_DIFF",    
"ANPNS_Crest_Coronal_CBCT1",
"ANSPNS_Crest_Coronal_CBCT2",          
"ANSPNS_Crest_Coronal_DIFF",           
"ANSPNS_Crest_Sagittal_CBCT1",        
"ANSPNS_Crest_Sagittal_CBCT2",         
"ANSPNS_Crest_Sagittal_DIFF",          
"ANSPNS_Sinus_Floor_Coronal_CBCT1",   
"ANSPNS_Sinus_Floor_Coronal_CBCT2",    
"ANSPNS_Sinus_Floor_Coronal_DIFF",     
"ANSPNS_Sinus_Floor_Sagittal_CBCT1",   
"ANSPNS_Sinus_Floor_Sagittal_CBCT2",   
"ANSPNS_Sinus_Floor_Sagittal_DIFF",    
"MENTAL_Crest_Coronal_CBCT1",         
"MENTAL_Crest_Coronal_CBCT2",         
 "MENTAL_Crest_Coronal_DIFF",           
"MENTAL_Crest_Sagittal_CBCT1",         
"MENTAL_Crest_Sagittal_CBCT2",         
"MENTAL_Crest_Sagittal_DIFF",
"Width_3mm_CBCT1",                     
"Width_3mm_CBCT2",                     
"Width_3mm_DIFF",                      
"Width_5mm_CBCT1",                     
"Width_5mm_CBCT2",                     
"Width_5mm_DIFF")
data_conti=finalized_data[,which(colnames(finalized_data)%in%continuous_var)]

res=summary_statistics(data_conti)
data.frame(res) %>%
datatable(extensions = 'Buttons',
          caption = "",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```


```{r, message=F, warning=F}
################ compute p values 
#data_conti[is.na(data_conti)] <- "0"
#cormat2=round(cor(data_conti, method="pearson", use = "na.or.complete"),2)
cormat2=matrix(nrow=ncol(data_conti), ncol=ncol(data_conti))
cormat2_pvalue=matrix(nrow=nrow(cormat2), ncol=nrow(cormat2))
for (i in 1:nrow(cormat2))
  for (j in 1:nrow(cormat2))
    {
    combine_data=data.frame(x=as.numeric(data_conti[,i]), y=as.numeric(data_conti[,j])) %>% drop_na()
    if (nrow(combine_data)>1)
    {
    test=cor.test(combine_data[,1], combine_data[,2], method="pearson", use = "na.or.complete")
    cormat2[i,j]=round(test$estimate,4)
    cormat2_pvalue[i,j]=round(test$p.value,4)
    }
    if (nrow(combine_data)<=1)  # no enough data to calculate correlations 
    {
     cormat2[i,j]="NA"
     cormat2_pvalue[i,j]="NA" 
      
    }
    
  }
row.names(cormat2)=colnames(data_conti) 
colnames(cormat2)=colnames(data_conti) 
cormat2 %>%
datatable(extensions = 'Buttons',
          caption = "Pearson correlation",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


row.names(cormat2_pvalue)=colnames(data_conti) 
colnames(cormat2_pvalue)=colnames(data_conti) 
cormat2_pvalue %>%
datatable(extensions = 'Buttons',
          caption = "P values of pearson correlation",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


correlation_pvalue=matrix(paste(cormat2, "(", cormat2_pvalue, ")", sep=""), nrow=nrow(cormat2))
rownames(correlation_pvalue)=row.names(cormat2)
colnames(correlation_pvalue)=row.names(cormat2)
correlation_pvalue%>%
datatable(extensions = 'Buttons',
          caption = "correlation (p value)",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```





```{r, message=F, warning=F}
################ compute p values 
#data_conti[is.na(data_conti)] <- "0"
#cormat2=round(cor(data_conti, method="pearson", use = "na.or.complete"),2)
cormat2=matrix(nrow=ncol(data_conti), ncol=ncol(data_conti))
cormat2_pvalue=matrix(nrow=nrow(cormat2), ncol=nrow(cormat2))
for (i in 1:nrow(cormat2))
  for (j in 1:nrow(cormat2))
    {
    combine_data=data.frame(x=as.numeric(data_conti[,i]), y=as.numeric(data_conti[,j])) %>% drop_na()
    if (nrow(combine_data)>1)
    {
    test=cor.test(combine_data[,1], combine_data[,2], method="spearman", use = "na.or.complete")
    cormat2[i,j]=round(test$estimate,4)
    cormat2_pvalue[i,j]=round(test$p.value,4)
    }
    if (nrow(combine_data)<=1)  # no enough data to calculate correlations 
    {
     cormat2[i,j]="NA"
     cormat2_pvalue[i,j]="NA" 
      
    }
    
  }
row.names(cormat2)=colnames(data_conti) 
colnames(cormat2)=colnames(data_conti) 
cormat2 %>%
datatable(extensions = 'Buttons',
          caption = "Spearman correlation",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


row.names(cormat2_pvalue)=colnames(data_conti) 
colnames(cormat2_pvalue)=colnames(data_conti) 
cormat2_pvalue %>%
datatable(extensions = 'Buttons',
          caption = "P values of spearman correlation",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


correlation_pvalue=matrix(paste(cormat2, "(", cormat2_pvalue, ")", sep=""), nrow=nrow(cormat2))
rownames(correlation_pvalue)=row.names(cormat2)
colnames(correlation_pvalue)=row.names(cormat2)
correlation_pvalue%>%
datatable(extensions = 'Buttons',
          caption = "Spearman correlation (p value)",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```




### discrete variables 


```{r, message=F, warning=F}
discrete_var=c("Tooth_site_number", 
               "Gender", 
               "Smoking", 
               "Tooth_migration", 
               "M_Tooth_Migration",  
               "D_Tooth_Migration",  
               "Migration_Notes", 
               "mesial_tooth_bone_loss_CBCT#1__mm", 
               "Jaw",                        
                "Arch_Fully_edentulous_both_CBCTs",
                "Partially_edentulous",
               "Partial_Edentulous_Space_\r\nLength",
                "Adjacent_teeth_number",
               "Adjacent_Note",                      
                "Restoration_type",
               "Restoration_Notes",                  
                "Ext_Reason",                                   
                "Coronal_sinus_floor_shift",  
                "Sinus_Pathology",
                 "Sites_10mm_height_or_more",          
                 "1st_CBCT_10mm_or_more",
               "2nd_CBCT_10mm_or_more" )
data_discrete=finalized_data[,which(colnames(finalized_data)%in%discrete_var)]

res=apply(data_discrete, 2, discrete_summary)
```





```{r, message=F, warning=F, results='asis'}
# Create a tagList to collect all datatables
library(htmltools)
output_list <- tagList()
for (k in 1:length(res))
  
{

  res_df <- data.frame(res[[k]]) # Convert the current list element to a data frame
# Append the datatable to the output list
  output_list <- tagAppendChild(
    output_list,
    datatable(
      res_df,
      extensions = 'Buttons',
      caption = discrete_var[k],
      options = list(
        dom = 'Blfrtip',
        buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
        lengthMenu = list(c(10, 25, 50, -1), c(10, 25, 50, "All"))
      )
    )
  )
  
  ############# calculate p values 
parameters=character()
pvalue=numeric()
kk=0
  for (i in 1:(nrow(res[[k]])-1))
  for (j in (i+1):nrow(res[[k]]))
  {
    kk=kk+1
    parameters[kk]=paste(res[[k]][i,1], res[[k]][j,1], sep="_vs_")
    pvalue[kk]=pvalue_adjust(binom.test(c(res[[k]][i,2], res[[k]][j,2]), p = 0.5)$p.value)
  }
output_list <- tagAppendChild(
    output_list,
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
          caption = discrete_var[k],
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
)


  
  
  
}

# Render all datatables
output_list
```




### tooth site groups 

```{r, message=F, warning=F}
n=c(finalized_data %>% filter(Tooth_site_number %in% upper_posterior) %>% nrow(), 
    finalized_data %>% filter(Tooth_site_number %in% upper_anterior) %>% nrow(), 
    finalized_data %>% filter(Tooth_site_number %in% lower_posterior) %>% nrow(), 
    finalized_data %>% filter(Tooth_site_number %in% lower_anterior) %>% nrow())

tooth_site_groups=data.frame(groups=c("upper_posterior", "upper_anterior", "lower_posterior", "lower_anterior"), n=n)

tooth_site_groups%>%
datatable(extensions = 'Buttons',
          caption = "tooth site groups",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


parameters=character()
pvalue=numeric()
kk=0
  for (i in 1:(nrow(tooth_site_groups)-1))
  for (j in (i+1):nrow(tooth_site_groups))
  {
    kk=kk+1
    parameters[kk]=paste(tooth_site_groups[i,1], tooth_site_groups[j,1], sep="_vs_")
    pvalue[kk]=pvalue_adjust(binom.test(c(tooth_site_groups[i,2], tooth_site_groups[j,2]), p = 0.5)$p.value)
  }


data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
          caption = "tooth site groups",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```






## group 2 vs 3


```{r, message=F, warning=F}
group2_maxilla=finalized_data %>% filter(Jaw==1)
group3_mandible=finalized_data %>% filter(Jaw==2)
```


### continuous variables 

```{r, message=F, warning=F}
two_sample_test=function(var)
{
#  cat(var, "\n")
  sample1=as.numeric(group2_maxilla %>% select(var) %>% pull())
  sample2=as.numeric(group3_mandible %>% select(var) %>% pull())
  if (sum(!is.na(sample1))>0 & sum(!is.na(sample2))>0)
  { 
   wilcox_test <- wilcox.test(sample1, sample2)
   return(wilcox_test$p.value)
  }
  else
    return("NA")
  
}
pvalue=sapply(continuous_var, two_sample_test)
data.frame(variables=continuous_var, pvalue=pvalue_adjust(as.numeric(pvalue)))%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```

* nonparametric  `wilcox.test` was used to test the difference 





### discrete variables


```{r, message=F, warning=F, results='asis'}
# Create a tagList to collect all datatables
library(htmltools)
output_list1 <- tagList()
for (k in 1:length(discrete_var))
  
{

data_subset1=group2_maxilla %>% dplyr::count(across(discrete_var[k])) %>% mutate(prop=round(n/nrow(group2_maxilla),4)) %>% drop_na()

data_subset2=group3_mandible %>% dplyr::count(across(discrete_var[k])) %>% mutate(prop=round(n/nrow(group3_mandible),4)) %>% drop_na()

data_subset=rbind(data_subset1, data_subset2) %>% mutate(sample=c(rep("group2_maxilla", nrow(data_subset1)), rep("group3_mandible", nrow(data_subset2))))


# Append the datatable to the output list
  output_list1 <- tagAppendChild(
    output_list1,
    datatable(
      data_subset,
      extensions = 'Buttons',
      caption = discrete_var[k],
      options = list(
        dom = 'Blfrtip',
        buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
        lengthMenu = list(c(10, 25, 50, -1), c(10, 25, 50, "All"))
      )
    )
  )
#############################
common_variable=intersect(data_subset %>% filter(sample=="group2_maxilla") %>% select(rlang::sym(discrete_var[k])) %>% pull(), data_subset %>% filter(sample=="group3_mandible") %>% select(rlang::sym(discrete_var[k])) %>% pull())
pvalue=numeric()
if (length(common_variable)>0)
{
for (i in 1:length(common_variable))
{
  variable_count=data_subset %>% filter(!!rlang::sym(discrete_var[k])==common_variable[i]) %>% select(n) %>% pull()
  pvalue[i]=pvalue_adjust(prop.test(x=variable_count, n=c(nrow(group2_maxilla), nrow(group3_mandible)))$p.value)
}
  
  
  ###########################
  # Append the datatable to the output list
  output_list1 <- tagAppendChild(
    output_list1,
    datatable(
      data.frame(variable=paste(common_variable, ":group2_maxilla_vs_group3_mandible"), pvalue=pvalue),
      extensions = 'Buttons',
      caption = discrete_var[k],
      options = list(
        dom = 'Blfrtip',
        buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
        lengthMenu = list(c(10, 25, 50, -1), c(10, 25, 50, "All"))
      )
    )
  )  
  
}
if (length(common_variable)==0)
  cat("no common variables between two groups", "\n")

  
}

# Render all datatables
output_list1

```


* two  sample proportion test was used. 



## group 4 



