---
title: "2024/02/12"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2024-02-12"
---

```{r, echo=F, message=F, warning=F, results=F}
source("C:/Shengtong/Research/AllCollaboration/Collaborations/analysis/Rfunctions.R")
data_raw=multiplesheets("C:\\Shengtong\\Research\\AllCollaboration\\2024\\202402\\Ann\\Graphs for Control vs Tx_new.xlsx")

```




```{r,  message=F, warning=F}
variable_index=1
variable=names(data_raw)[variable_index]
data=data_raw[[variable_index]]

sub_data=data.frame(control_pre=as.numeric(data[,3]), control_post=as.numeric(data[,4]), case_pre=as.numeric(data[,8]), case_post=as.numeric(data[,9]))

mean=numeric(); sd=numeric()
phase=c("1:pre", "2:post"); group=c("control", "case")
plot_data=data.frame(mean=round(apply(sub_data, 2, mean, na.rm=T),2),  sd=round(apply(sub_data, 2, sd, na.rm=T),2), time=rep(phase, length(group)), group=rep(group, each=length(phase)))

###################
ggplot(plot_data, aes(x=time, y=mean, group=group, color=group)) + 
  geom_line() +
  geom_point()+
  ylab(variable)+
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.05)) 
###################
plot_data%>%
datatable(extensions = 'Buttons',
          caption=variable, 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
t.test(sub_data$control_pre, sub_data$control_post, paired = T)
t.test(sub_data$case_pre, sub_data$case_post, paired = T)
```


* no statistical difference between pre and post in both case (p value of 0.78) and control groups (p value of 0.46) using two sample paired t test. 



```{r, message=F, warning=F}
variable_index=2
variable=names(data_raw)[variable_index]
data=data_raw[[variable_index]]

sub_data=data.frame(control_pre=as.numeric(data[,2]), control_post=as.numeric(data[,3]), case_pre=as.numeric(data[,6]), case_post=as.numeric(data[,7]))

mean=numeric(); sd=numeric()
phase=c("1:pre", "2:post"); group=c("control", "case")
plot_data=data.frame(mean=round(apply(sub_data, 2, mean, na.rm=T),2),  sd=round(apply(sub_data, 2, sd, na.rm=T),2), time=rep(phase, length(group)), group=rep(group, each=length(phase)))

###################
ggplot(plot_data, aes(x=time, y=mean, group=group, color=group)) + 
  geom_line() +
  geom_point()+
  ylab(variable)+
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.05)) 
###################
plot_data%>%
datatable(extensions = 'Buttons',
          caption=variable, 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
t.test(sub_data$control_pre, sub_data$control_post, paired = T)
t.test(sub_data$case_pre, sub_data$case_post, paired = T)
```





```{r, message=F, warning=F}
variable_index=3
variable=names(data_raw)[variable_index]
data=data_raw[[variable_index]]

sub_data=data.frame(control_pre=as.numeric(data[,2]), control_post=as.numeric(data[,3]), case_pre=as.numeric(data[,7]), case_post=as.numeric(data[,8]))

mean=numeric(); sd=numeric()
phase=c("1:pre", "2:post"); group=c("control", "case")
plot_data=data.frame(mean=round(apply(sub_data, 2, mean, na.rm=T),2),  sd=round(apply(sub_data, 2, sd, na.rm=T),2), time=rep(phase, length(group)), group=rep(group, each=length(phase)))

###################
ggplot(plot_data, aes(x=time, y=mean, group=group, color=group)) + 
  geom_line() +
  geom_point()+
  ylab(variable)+
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.05)) 
###################
plot_data%>%
datatable(extensions = 'Buttons',
          caption=variable, 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
t.test(sub_data$control_pre, sub_data$control_post, paired = T)
t.test(sub_data$case_pre, sub_data$case_post, paired = T)
```

```{r, message=F, warning=F}
variable_index=4
variable=names(data_raw)[variable_index]
data=data_raw[[variable_index]]

sub_data=data.frame(control_pre=as.numeric(data[,6]), control_post=as.numeric(data[,7]), case_pre=as.numeric(data[,10]), case_post=as.numeric(data[,11]))

mean=numeric(); sd=numeric()
phase=c("1:pre", "2:post"); group=c("control", "case")
plot_data=data.frame(mean=round(apply(sub_data, 2, mean, na.rm=T),2),  sd=round(apply(sub_data, 2, sd, na.rm=T),2), time=rep(phase, length(group)), group=rep(group, each=length(phase)))

###################
ggplot(plot_data, aes(x=time, y=mean, group=group, color=group)) + 
  geom_line() +
  geom_point()+
  ylab(variable)+
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.05)) 
###################
plot_data%>%
datatable(extensions = 'Buttons',
          caption=variable, 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
t.test(sub_data$control_pre, sub_data$control_post, paired = T)
t.test(sub_data$case_pre, sub_data$case_post, paired = T)
```



```{r, message=F, warning=F}
variable_index=5
variable=names(data_raw)[variable_index]
data=data_raw[[variable_index]]

sub_data=data.frame(control_pre=as.numeric(data[,2]), control_post=as.numeric(data[,3]), case_pre=as.numeric(data[,7]), case_post=as.numeric(data[,8]))

mean=numeric(); sd=numeric()
phase=c("1:pre", "2:post"); group=c("control", "case")
plot_data=data.frame(mean=round(apply(sub_data, 2, mean, na.rm=T),2),  sd=round(apply(sub_data, 2, sd, na.rm=T),2), time=rep(phase, length(group)), group=rep(group, each=length(phase)))

###################
ggplot(plot_data, aes(x=time, y=mean, group=group, color=group)) + 
  geom_line() +
  geom_point()+
  ylab(variable)+
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.05)) 
###################
plot_data%>%
datatable(extensions = 'Buttons',
          caption=variable, 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
t.test(sub_data$control_pre, sub_data$control_post, paired = T)
t.test(sub_data$case_pre, sub_data$case_post, paired = T)
```




```{r, message=F, warning=F}
variable_index=6
variable=names(data_raw)[variable_index]
data=data_raw[[variable_index]]

sub_data=data.frame(control_pre=as.numeric(data[,2]), control_post=as.numeric(data[,3]), case_pre=as.numeric(data[,7]), case_post=as.numeric(data[,8]))

mean=numeric(); sd=numeric()
phase=c("1:pre", "2:post"); group=c("control", "case")
plot_data=data.frame(mean=round(apply(sub_data, 2, mean, na.rm=T),2),  sd=round(apply(sub_data, 2, sd, na.rm=T),2), time=rep(phase, length(group)), group=rep(group, each=length(phase)))

###################
ggplot(plot_data, aes(x=time, y=mean, group=group, color=group)) + 
  geom_line() +
  geom_point()+
  ylab(variable)+
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.05)) 
###################
plot_data%>%
datatable(extensions = 'Buttons',
          caption=variable, 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
t.test(sub_data$control_pre, sub_data$control_post, paired = T)
t.test(sub_data$case_pre, sub_data$case_post, paired = T)
```





```{r, message=F, warning=F}
variable_index=7
variable=names(data_raw)[variable_index]
data=data_raw[[variable_index]]

sub_data=data.frame(control_pre=as.numeric(data[,2]), control_post=as.numeric(data[,3]), case_pre=as.numeric(data[,6]), case_post=as.numeric(data[,7]))

mean=numeric(); sd=numeric()
phase=c("1:pre", "2:post"); group=c("control", "case")
plot_data=data.frame(mean=round(apply(sub_data, 2, mean, na.rm=T),2),  sd=round(apply(sub_data, 2, sd, na.rm=T),2), time=rep(phase, length(group)), group=rep(group, each=length(phase)))

###################
ggplot(plot_data, aes(x=time, y=mean, group=group, color=group)) + 
  geom_line() +
  geom_point()+
  ylab(variable)+
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.05)) 
###################
plot_data%>%
datatable(extensions = 'Buttons',
          caption=variable, 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
t.test(sub_data$control_pre, sub_data$control_post, paired = T)
t.test(sub_data$case_pre, sub_data$case_post, paired = T)
```


```{r, message=F, warning=F, eval=T}
variable_index=8
variable=names(data_raw)[variable_index]
data=data_raw[[variable_index]]

sub_data=data.frame(control_pre=as.numeric(data[,2]), control_post=as.numeric(data[,3]), case_pre=as.numeric(data[,6]), case_post=as.numeric(data[,7]))

mean=numeric(); sd=numeric()
phase=c("1:pre", "2:post"); group=c("control", "case")
plot_data=data.frame(mean=round(apply(sub_data, 2, mean, na.rm=T),2),  sd=round(apply(sub_data, 2, sd, na.rm=T),2), time=rep(phase, length(group)), group=rep(group, each=length(phase)))

###################
ggplot(plot_data, aes(x=time, y=mean, group=group, color=group)) + 
  geom_line() +
  geom_point()+
  ylab(variable)+
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.05)) 
###################
plot_data%>%
datatable(extensions = 'Buttons',
          caption=variable, 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
t.test(sub_data$control_pre, sub_data$control_post, paired = T)
t.test(sub_data$case_pre, sub_data$case_post, paired = T)
```


```{r, message=F, warning=F, eval=T}
variable_index=10
variable=names(data_raw)[variable_index]
data=data_raw[[variable_index]]

sub_data=data.frame(control_pre=as.numeric(data[,2]), control_post=as.numeric(data[,3]), case_pre=as.numeric(data[,6]), case_post=as.numeric(data[,7]))

mean=numeric(); sd=numeric()
phase=c("1:pre", "2:post"); group=c("control", "case")
plot_data=data.frame(mean=round(apply(sub_data, 2, mean, na.rm=T),2),  sd=round(apply(sub_data, 2, sd, na.rm=T),2), time=rep(phase, length(group)), group=rep(group, each=length(phase)))

###################
ggplot(plot_data, aes(x=time, y=mean, group=group, color=group)) + 
  geom_line() +
  geom_point()+
  ylab(variable)+
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                 position=position_dodge(.05)) 
###################
plot_data%>%
datatable(extensions = 'Buttons',
          caption=variable, 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
t.test(sub_data$control_pre, sub_data$control_post, paired = T)
t.test(sub_data$case_pre, sub_data$case_post, paired = T)
```



## further analysis 

```{r, echo=F, message=F, warning=F}
#questionnaire_data=multiplesheets("C:\\Shengtong\\Research\\AllCollaboration\\2024\\202402\\Ann\\Control and Intervention groups outtake questionnaire.xlsx")
#data=list(intervention=questionnaire_data$Intervention, control=questionnaire_data$Control)
#save(data, file="C:\\Shengtong\\Research\\AllCollaboration\\2024\\202402\\Ann\\questionnaire_data.RData")
load("C:\\Shengtong\\Research\\AllCollaboration\\2024\\202402\\Ann\\questionnaire_data.RData")
```


### questions 


```{r, message=F, warning=F}
colnames(data$intervention)[2:19]==colnames(data$control)[2:19]
questions=colnames(data$intervention)[3:19]
questions
```

```{r, echo=F, message=F, warning=F}
main_function=function(variable)
{
  data_subset1=data$intervention %>% dplyr::count(!!rlang::sym(variable))%>% drop_na() 
num_indi1=sum(data_subset1$n)
if (num_indi1>0)
  data_subset1=data_subset1%>% mutate(prop=round(n/num_indi1,4)) %>% drop_na()

data_subset2=data$control %>% dplyr::count(!!rlang::sym(variable))%>% drop_na() 
num_indi2=sum(data_subset2$n)
if (num_indi2>0)
 data_subset2=data_subset2%>% mutate(prop=round(n/num_indi2,4)) %>% drop_na()

if (num_indi1>0 & num_indi2>0)
{
data_subset=rbind(data_subset1, data_subset2) %>% mutate(sample=c(rep("intervention", nrow(data_subset1)), rep("control", nrow(data_subset2))))
data_subset[,1][data_subset[,1]==1]="strongly disagree"; 
data_subset[,1][data_subset[,1]==2]="disagree";
data_subset[,1][data_subset[,1]==3]="neutral";
data_subset[,1][data_subset[,1]==4]="agree";
data_subset[,1][data_subset[,1]==5]="strongly agree";


  
common_variable=intersect(data_subset %>% filter(sample=="intervention") %>% select(!!rlang::sym(variable)) %>% pull(), data_subset %>% filter(sample=="control") %>% select(!!rlang::sym(variable)) %>% pull())
pvalue=numeric()
for (i in 1:length(common_variable))
{
  variable_count=data_subset %>% filter(!!rlang::sym(variable)==common_variable[i]) %>% select(n) %>% pull()
  pvalue[i]=pvalue_adjust(prop.test(x=variable_count, n=c(num_indi1, num_indi2))$p.value)
}
return(list(data_subset=data_subset, comparison=data.frame(variable=paste(common_variable, ":intervention_vs_control"), pvalue=pvalue)))

}

if (num_indi1==0 & num_indi2>0)
{
data_subset=data_subset2
data_subset[,1][data_subset[,1]==1]="strongly disagree"; 
data_subset[,1][data_subset[,1]==2]="disagree";
data_subset[,1][data_subset[,1]==3]="neutral";
data_subset[,1][data_subset[,1]==4]="agree";
data_subset[,1][data_subset[,1]==5]="strongly agree";
  
return(list(data_subset=data_subset, comparison="NA"))
}
if (num_indi1>0 & num_indi2==0)
{
  
data_subset=data_subset1
data_subset[,1][data_subset[,1]==1]="strongly disagree"; 
data_subset[,1][data_subset[,1]==2]="disagree";
data_subset[,1][data_subset[,1]==3]="neutral";
data_subset[,1][data_subset[,1]==4]="agree";
data_subset[,1][data_subset[,1]==5]="strongly agree";
  return(list(data_subset=data_subset, comparison="NA"))
}
if (num_indi1==0 & num_indi2==0)
return(list(data_subset="NA", comparison="NA"))


}
```



```{r, message=F, warning=F}
k=1
main_function(questions[k])$data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
main_function(questions[k])$comparison%>%
datatable(extensions = 'Buttons',
          caption = questions[k], 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```


```{r, message=F, warning=F}
k=2
main_function(questions[k])$data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
main_function(questions[k])$comparison%>%
datatable(extensions = 'Buttons',
          caption = questions[k],
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```


```{r, message=F, warning=F}
k=3
main_function(questions[k])$data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
main_function(questions[k])$comparison%>%
datatable(extensions = 'Buttons',
          caption = questions[k],
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```




```{r, message=F, warning=F}
k=4
main_function(questions[k])$data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
main_function(questions[k])$comparison%>%
datatable(extensions = 'Buttons',
          caption = questions[k],
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



```{r, message=F, warning=F}
k=5
main_function(questions[k])$data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
main_function(questions[k])$comparison%>%
datatable(extensions = 'Buttons',
          caption = questions[k],
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```




```{r, message=F, warning=F}

k=6
main_function(questions[k])$data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
main_function(questions[k])$comparison%>%
datatable(extensions = 'Buttons',
          caption = questions[k],
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


```


```{r, message=F, warning=F}
k=7
main_function(questions[k])$data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
main_function(questions[k])$comparison%>%
datatable(extensions = 'Buttons',
          caption = questions[k],
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```




```{r, message=F, warning=F}

k=8
main_function(questions[k])$data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
main_function(questions[k])$comparison%>%
datatable(extensions = 'Buttons',
          caption = questions[k],
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


```



```{r, message=F, warning=F}
k=9
main_function(questions[k])$data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
main_function(questions[k])$comparison%>%
datatable(extensions = 'Buttons',
          caption = questions[k],
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


```




```{r, message=F, warning=F}

k=10
main_function(questions[k])$data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
main_function(questions[k])$comparison%>%
datatable(extensions = 'Buttons',
          caption = questions[k],
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


```



```{r, message=F, warning=F}
k=11
main_function(questions[k])$data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
main_function(questions[k])$comparison%>%
datatable(extensions = 'Buttons',
          caption = questions[k],
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


```




```{r, message=F, warning=F, eval=T}

k=12
main_function(questions[k])$data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))



```



```{r, message=F, warning=F, eval=F}
k=13
main_function(questions[k])$data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))



```




```{r, message=F, warning=F, eval=T}

k=14
main_function(questions[k])$data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



```{r, message=F, warning=F, eval=T}
k=15
main_function(questions[k])$data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


```




```{r, message=F, warning=F, eval=T}

k=16
main_function(questions[k])$data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


```


```{r, message=F, warning=F, eval=T}
k=17
main_function(questions[k])$data_subset%>%
datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


```






