---
title: "02/19/2024"
output: html_document
date: "2024-02-19"
---


```{r, echo=F, message=F, warning=F, results=F}
source("C:/Shengtong/Research/AllCollaboration/Collaborations/analysis/Rfunctions.R")
data_raw=multiplesheets("C:\\Shengtong\\Research\\AllCollaboration\\2024\\202402\\Zaid\\Data for Kappa after intra-reader.xlsx")
#data=as_tibble(data_raw[[1]])
data_combine=data_raw$combine
```

```{r, echo=F, message=F, warning=F}
library(SimplyAgree)
data_split=list(); all_surface=c()
for (i in 1:66)
{
  #i=1
  sub_data=data_combine[((i-1)*3+1):(i*3),]
  column_names=sub_data[1,]
  sub_data=sub_data[-1,]
  colnames(sub_data)=column_names
  data_split[[i]]=sub_data
  all_surface=c(all_surface, column_names[3:length(column_names)])
}
all_surface=unique(unlist(all_surface))
all_surface=all_surface[!is.na(all_surface)]

#################
kappa_value=numeric()
kappa_pvalue=numeric()
num_teeth=numeric()
agreement=numeric()
ccc_value=numeric()
for (i in 1:length(all_surface))
{
#  i=9
  rate1=numeric(); rate2=numeric()
  k=0
  for (j in 1:length(data_split))
  {
    if(sum(colnames(data_split[[j]])==all_surface[i], na.rm=T)>0)
    {
      k=k+1
      rate1[k]=data_split[[j]][1,  which(colnames(data_split[[j]])==all_surface[i])]
      rate2[k]=data_split[[j]][2,  which(colnames(data_split[[j]])==all_surface[i])]
    }
    
  }
   num_teeth[i]=length(rate1)
  
   kappa_test=kappa2(data.frame(rate1=as.numeric(unlist(rate1)), rate2=as.numeric(unlist(rate2))))
  kappa_value[i]=round(kappa_test$value,4)
  kappa_pvalue[i]=pvalue_adjust(kappa_test$p.value) 
  
  agreement[i]=agree(data.frame(rate1=as.numeric(unlist(rate1)), rate2=as.numeric(unlist(rate2))))$value
  
#  if (k>1)
 # ccc_value[i]=agree_test(x=as.numeric(unlist(rate1)), y=as.numeric(unlist(rate2)), agree.level = 0.8)$ccc.xy[1]
  
}
data.frame(surface=all_surface, num_teeth=num_teeth, kappa_value=kappa_value, kappa_pvalue=kappa_pvalue, agreement=round(agreement,4))%>%
datatable(extensions = 'Buttons',
          caption = "", 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```

```{r, echo=T, message=F, warning=F}
result=data.frame(surface=all_surface, num_teeth=num_teeth, kappa_value=kappa_value, kappa_pvalue=kappa_pvalue, agreement=round(agreement,4))
kappa_value_all=result %>% filter(num_teeth>10 & kappa_value>0) %>% drop_na() %>% select(kappa_value) %>% pull()
summary(kappa_value_all)
```



* average kappa value is 0.68 that is substantial according to the [interpretation](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3900052/#:~:text=Cohen%20suggested%20the%20Kappa%20result,1.00%20as%20almost%20perfect%20agreement.)


* [reference](https://www.andywills.info/rminr/irr.html)
