---
title: "group 6"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2025-06-04"
---



```{r, echo=F, message=F, warning=F, results=F}
library(rprojroot)
root <- rprojroot::find_rstudio_root_file()
source(file.path(root, "analysis/Rfunctions.R"))
root <- rprojroot::find_rstudio_root_file()
```



```{r, message=F, warning=F, results=F}
#data_raw=multiplesheets("C:\\Shengtong\\Research\\AllCollaboration\\2024\\202410\\Neal\\CBCT Thesis data FINAL VK011525.xlsx")
#finalized_data=as_tibble(read.csv(file.path(root,"..\\2024\\202410\\Neal\\CBCT Thesis data FINAL VK011525_Finalized_Data.csv")))

finalized_data=as_tibble(read.csv(file.path(root,"..\\2024\\202410\\Neal\\6 FINAL CBCT Thesis data (09-11-25)_finalized_data.csv")))

#finalized_with_omitted_data=data_raw$`Finalized with Omitted data`
#coding=data_raw$`Coding`
#save(finalized_with_omitted_data, finalized_data, coding, file="C:\\Shengtong\\Research\\AllCollaboration\\2024\\202410\\Neal\\data.RData")
#load("C:\\Shengtong\\Research\\AllCollaboration\\2024\\202410\\Neal\\data.RData")


#colnames(finalized_data)
finalized_data=finalized_data %>% filter(Subject!=185)  #excluding subject 185 requested by Vrisiis
```




```{r, message=F, warning=F}
upper_posterior=c(2, 3, 4, 5, 12, 13, 14, 15)
upper_anterior=6:11
lower_posterior=c(18, 19, 20, 21, 28, 29, 30, 31)
lower_anterior=22:27
```






```{r, message=F, warning=F, eval=T}
continuous_var=c("Age", 
"Months_btwn_CBCTS",  
"Months_btwn_Ext_CBCT.1",
"mesial_tooth_bone_loss_CBCT.2__mm",   
"mesial_tooth_bone_loss_DIFF", 
"mesial_tooth_bone_loss_CBCT.1__mm",
"distal_tooth_bone_loss_CBCT.1__mm",    
"distal_tooth_bone_loss_CBCT.2__mm",   
"distal_tooth_bone_loss_DIFF",    
"ANPNS_Crest_Coronal_CBCT1",
"ANSPNS_Crest_Coronal_CBCT2",          
"ANSPNS_Crest_Coronal_DIFF",           
"ANSPNS_Crest_Sagittal_CBCT1",        
"ANSPNS_Crest_Sagittal_CBCT2",         
"ANSPNS_Crest_Sagittal_DIFF",          
"ANSPNS_Sinus_Floor_Coronal_CBCT1",   
"ANSPNS_Sinus_Floor_Coronal_CBCT2",    
"ANSPNS_Sinus_Floor_Coronal_DIFF",     
"ANSPNS_Sinus_Floor_Sagittal_CBCT1",   
"ANSPNS_Sinus_Floor_Sagittal_CBCT2",   
"ANSPNS_Sinus_Floor_Sagittal_DIFF",    
"MENTAL_Crest_Coronal_CBCT1",         
"MENTAL_Crest_Coronal_CBCT2",         
 "MENTAL_Crest_Coronal_DIFF",           
"MENTAL_Crest_Sagittal_CBCT1",         
"MENTAL_Crest_Sagittal_CBCT2",         
"MENTAL_Crest_Sagittal_DIFF",
"Width_3mm_CBCT1",                     
"Width_3mm_CBCT2",                     
"Width_3mm_DIFF",                      
"Width_5mm_CBCT1",                     
"Width_5mm_CBCT2",                     
"Width_5mm_DIFF")
data_conti=data.frame(as.matrix(finalized_data[,which(colnames(finalized_data)%in%continuous_var)]))


###################### definitions
#Height_coronal_CBCT1 = ANS_PNS_crest_coronal_CBCT1 + mental_crest_coronal_CBCT1
#Height_coronal_CBCT2 = ANS_PNS_crest_coronal_CBCT2 + mental_crest_coronal_CBCT2
#Height_sagittal_CBCT1 = ANS_PNS_crest_sagittal_CBCT1 + mental_crest_sagittal_CBCT1
#Height_sagittal_CBCT2 = ANS_PNS_crest_sagittal_CBCT2 + mental_crest_sagittal_CBCT2


data_conti$Height_coronal_CBCT1=
  ifelse(is.na(data_conti$ANPNS_Crest_Coronal_CBCT1), 0, data_conti$ANPNS_Crest_Coronal_CBCT1) +
  ifelse(is.na(data_conti$MENTAL_Crest_Coronal_CBCT1), 0, data_conti$MENTAL_Crest_Coronal_CBCT1)
##############

data_conti$Height_coronal_CBCT2 <- 
  ifelse(is.na(data_conti$ANSPNS_Crest_Coronal_CBCT2), 0, data_conti$ANSPNS_Crest_Coronal_CBCT2) + 
  ifelse(is.na(data_conti$MENTAL_Crest_Coronal_CBCT2), 0, data_conti$MENTAL_Crest_Coronal_CBCT2)
##############

data_conti$Height_sagittal_CBCT1 <- 
  ifelse(is.na(data_conti$ANSPNS_Crest_Sagittal_CBCT1), 0, data_conti$ANSPNS_Crest_Sagittal_CBCT1) +  
  ifelse(is.na(data_conti$MENTAL_Crest_Sagittal_CBCT1), 0, data_conti$MENTAL_Crest_Sagittal_CBCT1)
  
##############

data_conti$Height_sagittal_CBCT2 <- 
  ifelse(is.na(data_conti$ANSPNS_Crest_Sagittal_CBCT2), 0, data_conti$ANSPNS_Crest_Sagittal_CBCT2) +
  ifelse(is.na(data_conti$MENTAL_Crest_Sagittal_CBCT2), 0, data_conti$MENTAL_Crest_Sagittal_CBCT2) 


##############

data_conti$Height_coronal_DIFF <- 
  ifelse(is.na(data_conti$ANSPNS_Crest_Coronal_DIFF), 0, data_conti$ANSPNS_Crest_Coronal_DIFF) +  
  ifelse(is.na(data_conti$MENTAL_Crest_Coronal_DIFF), 0, data_conti$MENTAL_Crest_Coronal_DIFF)
##############

data_conti$Height_sagittal_DIFF <- 
  ifelse(is.na(data_conti$ANSPNS_Crest_Sagittal_DIFF), 0, data_conti$ANSPNS_Crest_Sagittal_DIFF) +
  ifelse(is.na(data_conti$MENTAL_Crest_Sagittal_DIFF), 0, data_conti$MENTAL_Crest_Sagittal_DIFF)
#################


continuous_var=c(continuous_var,"Height_sagittal_CBCT1", "Height_sagittal_CBCT2", "Height_sagittal_DIFF",  "Height_coronal_DIFF", "Height_coronal_CBCT1", "Height_coronal_CBCT2" )

finalized_data$Height_coronal_CBCT1=data_conti$Height_coronal_CBCT1
finalized_data$Height_coronal_CBCT2=data_conti$Height_coronal_CBCT2
finalized_data$Height_sagittal_CBCT1=data_conti$Height_sagittal_CBCT1
finalized_data$Height_sagittal_CBCT2=data_conti$Height_sagittal_CBCT2
finalized_data$Height_coronal_DIFF=data_conti$Height_coronal_DIFF
finalized_data$Height_sagittal_DIFF=data_conti$Height_sagittal_DIFF

#res=summary_statistics(data_conti)
#data.frame(res) %>%
#datatable(extensions = 'Buttons',
#          caption = "",
#            options = list(dom = 'Blfrtip',
#                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
#                           lengthMenu = list(c(10,25,50,-1),
#                                             c(10,25,50,"All"))))
```




```{r, message=F, warning=F}
finalized_data <- finalized_data %>%
  mutate(Month_Group = case_when(
    Months_btwn_CBCTS >= 12 & Months_btwn_CBCTS < 18 ~ "6A",
    Months_btwn_CBCTS >= 18 & Months_btwn_CBCTS < 36 ~ "6B",
    Months_btwn_CBCTS >= 36                          ~ "6C",
    TRUE                                             ~ NA_character_  # Handles missing or <12 values
  ))
```




## continuous variables comparions  between groups


```{r, message=F, warning=F}
pvalue_df <- map_dfr(continuous_var, function(var) {
  group_data <- finalized_data %>%
    select(Month_Group, value = all_of(var)) %>%
    filter(!is.na(value))
  
  group_6A <- filter(group_data, Month_Group == "6A") %>% pull(value)
  group_6B <- filter(group_data, Month_Group == "6B") %>% pull(value)
  group_6C <- filter(group_data, Month_Group == "6C") %>% pull(value)

  tibble(
    Variable = var,
    Comparison = c("6A vs 6B", "6A vs 6C", "6B vs 6C"),
    p_value = c(
      adjust_pvalue(t.test(group_6A, group_6B)$p.value),
      adjust_pvalue(t.test(group_6A, group_6C)$p.value),
      adjust_pvalue(t.test(group_6B, group_6C)$p.value)
    )
  )
})

pvalue_df$p_value=pvalue_adjust(pvalue_df$p_value)
 pvalue_df%>%
datatable(extensions = 'Buttons',
          caption = "",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```



##  descriptive statistics later only for parameters with p<0.05

```{r, message=F, warning=F}
threshold=0.05
significant_variables=unique(pvalue_df %>% filter(p_value<threshold)%>% select(Variable) %>% pull())

res=summary_statistics(data_conti %>% select(significant_variables))
res%>%
datatable(extensions = 'Buttons',
          caption = "",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```
