---
title: "2024/10/07"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2024-10-07"
---



```{r, echo=F, message=F, warning=F}
source("C:/Shengtong/Research/AllCollaboration/Collaborations/analysis/Rfunctions.R")
```


```{r, message=F, warning=F, results=F}
#data_raw=multiplesheets("C:\\Shengtong\\Research\\AllCollaboration\\2024\\202410\\Samah\\Samah 2025 AADOCR.xlsx")
#data=data_raw$Data
#variables=data_raw$`Variables `
#coding=data_raw$`Coding `
#save(data, variables, coding, file="C:\\Shengtong\\Research\\AllCollaboration\\2024\\202410\\Samah\\data.RData")
load("C:\\Shengtong\\Research\\AllCollaboration\\2024\\202410\\Samah\\data.RData")
```


```{r, message=F, warning=F}
colnames(data)
```




## continuous variables 

```{r, message=F, warning=F}
data_conti=data.frame(data$Age, data$Cigarrettes_per_day, data$VAS_pain_anticipated, data$VAS_pain_preop, data$VAS_swell_anticipated, data$VAS_swell_preop, data[,60:90])

res=summary_statistics(data_conti)
data.frame(res) %>%
datatable(extensions = 'Buttons',
          caption = "",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```



## discrete variables 


```{r, message=F, warning=F}
discrete_variable_func=function(data_subset, variable_name)
{
  ############ compute/print out between group p values 
parameters=character()
pvalue=numeric()
k=0
for (i in 1:(nrow(data_subset)-1))
  for (j in (i+1):nrow(data_subset))
  {
    k=k+1
    parameters[k]=paste(data_subset[i,1], data_subset[j,1], sep="_vs_")
    pvalue[k]=pvalue_adjust(binom.test(c(data_subset[i,2], data_subset[j,2]), p = 0.5)$p.value)
  }

return(data.frame(comparison=parameters, pvalue=pvalue))
}
```




```{r, message=F, warning=F}
variable_name="Gender"

data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==1]="Male"
data_subset[,variable_name][data_subset[,variable_name]==2]="Female"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="Race"

#1= Asian
#2= African American
#3= Caucasian 
#4= Hispanic 
#5= Others 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==1]="Asian"
data_subset[,variable_name][data_subset[,variable_name]==2]="African American"
data_subset[,variable_name][data_subset[,variable_name]==3]="Caucasian"
data_subset[,variable_name][data_subset[,variable_name]==4]="Hispanic"
data_subset[,variable_name][data_subset[,variable_name]==6]="Others"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, message=F, warning=F}
variable_name="Smoking_status"

#1= Never smoked
#2= Past smoker
#3= Current smoker
 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==1]="Never smoked"
data_subset[,variable_name][data_subset[,variable_name]==2]="Past smoker"
data_subset[,variable_name][data_subset[,variable_name]==3]="current smoker"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, message=F, warning=F}
variable_name="Oral_surgery_history"

#Oral surgery Hx	1= Yes
#	2= No
#	3= Maybe 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==1]="Yes"
data_subset[,variable_name][data_subset[,variable_name]==2]="No"
data_subset[,variable_name][data_subset[,variable_name]==3]="Maybe"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="MDAS_Q1"

#MDAS_Q1	0= Not anxious
#	1= Slightly anxious
#	2= Fairly anxious
#	3= Very anxious
#	4= Extremely anxious
 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not anxious"
data_subset[,variable_name][data_subset[,variable_name]==1]="Slightly anxious"
data_subset[,variable_name][data_subset[,variable_name]==2]="Fairly anxious"
data_subset[,variable_name][data_subset[,variable_name]==3]="Very anxious"
data_subset[,variable_name][data_subset[,variable_name]==4]="Extremely anxious"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, message=F, warning=F}
variable_name="MDAS_Q2"

#MDAS_Q1	0= Not anxious
#	1= Slightly anxious
#	2= Fairly anxious
#	3= Very anxious
#	4= Extremely anxious
 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not anxious"
data_subset[,variable_name][data_subset[,variable_name]==1]="Slightly anxious"
data_subset[,variable_name][data_subset[,variable_name]==2]="Fairly anxious"
data_subset[,variable_name][data_subset[,variable_name]==3]="Very anxious"
data_subset[,variable_name][data_subset[,variable_name]==4]="Extremely anxious"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="MDAS_Q3"

#MDAS_Q1	0= Not anxious
#	1= Slightly anxious
#	2= Fairly anxious
#	3= Very anxious
#	4= Extremely anxious
 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not anxious"
data_subset[,variable_name][data_subset[,variable_name]==1]="Slightly anxious"
data_subset[,variable_name][data_subset[,variable_name]==2]="Fairly anxious"
data_subset[,variable_name][data_subset[,variable_name]==3]="Very anxious"
data_subset[,variable_name][data_subset[,variable_name]==4]="Extremely anxious"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, message=F, warning=F}
variable_name="MDAS_Q4"

#MDAS_Q1	0= Not anxious
#	1= Slightly anxious
#	2= Fairly anxious
#	3= Very anxious
#	4= Extremely anxious
 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not anxious"
data_subset[,variable_name][data_subset[,variable_name]==1]="Slightly anxious"
data_subset[,variable_name][data_subset[,variable_name]==2]="Fairly anxious"
data_subset[,variable_name][data_subset[,variable_name]==3]="Very anxious"
data_subset[,variable_name][data_subset[,variable_name]==4]="Extremely anxious"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="MDAS_Q5"

#MDAS_Q1	0= Not anxious
#	1= Slightly anxious
#	2= Fairly anxious
#	3= Very anxious
#	4= Extremely anxious
 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not anxious"
data_subset[,variable_name][data_subset[,variable_name]==1]="Slightly anxious"
data_subset[,variable_name][data_subset[,variable_name]==2]="Fairly anxious"
data_subset[,variable_name][data_subset[,variable_name]==3]="Very anxious"
data_subset[,variable_name][data_subset[,variable_name]==4]="Extremely anxious"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="OHIP_Q1"

#OHIP_Q1	0= Never
#	1= Hardly ever
#	2= Occasionally
#	3= Fairly often 
#	4= Very often 

 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Never"
data_subset[,variable_name][data_subset[,variable_name]==1]="Hardly ever"
data_subset[,variable_name][data_subset[,variable_name]==2]="Occasionally"
data_subset[,variable_name][data_subset[,variable_name]==3]="Fairly often"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very often"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, message=F, warning=F}
variable_name="OHIP_Q2"

#OHIP_Q1	0= Never
#	1= Hardly ever
#	2= Occasionally
#	3= Fairly often 
#	4= Very often 

 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Never"
data_subset[,variable_name][data_subset[,variable_name]==1]="Hardly ever"
data_subset[,variable_name][data_subset[,variable_name]==2]="Occasionally"
data_subset[,variable_name][data_subset[,variable_name]==3]="Fairly often"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very often"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="OHIP_Q3"

#OHIP_Q1	0= Never
#	1= Hardly ever
#	2= Occasionally
#	3= Fairly often 
#	4= Very often 

 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Never"
data_subset[,variable_name][data_subset[,variable_name]==1]="Hardly ever"
data_subset[,variable_name][data_subset[,variable_name]==2]="Occasionally"
data_subset[,variable_name][data_subset[,variable_name]==3]="Fairly often"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very often"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="OHIP_Q4"

#OHIP_Q1	0= Never
#	1= Hardly ever
#	2= Occasionally
#	3= Fairly often 
#	4= Very often 

 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Never"
data_subset[,variable_name][data_subset[,variable_name]==1]="Hardly ever"
data_subset[,variable_name][data_subset[,variable_name]==2]="Occasionally"
data_subset[,variable_name][data_subset[,variable_name]==3]="Fairly often"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very often"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, message=F, warning=F}
variable_name="OHIP_Q5"

#OHIP_Q1	0= Never
#	1= Hardly ever
#	2= Occasionally
#	3= Fairly often 
#	4= Very often 

 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Never"
data_subset[,variable_name][data_subset[,variable_name]==1]="Hardly ever"
data_subset[,variable_name][data_subset[,variable_name]==2]="Occasionally"
data_subset[,variable_name][data_subset[,variable_name]==3]="Fairly often"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very often"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="OHIP_Q6"

#OHIP_Q1	0= Never
#	1= Hardly ever
#	2= Occasionally
#	3= Fairly often 
#	4= Very often 

 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Never"
data_subset[,variable_name][data_subset[,variable_name]==1]="Hardly ever"
data_subset[,variable_name][data_subset[,variable_name]==2]="Occasionally"
data_subset[,variable_name][data_subset[,variable_name]==3]="Fairly often"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very often"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, message=F, warning=F}
variable_name="OHIP_Q7"

#OHIP_Q1	0= Never
#	1= Hardly ever
#	2= Occasionally
#	3= Fairly often 
#	4= Very often 

 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Never"
data_subset[,variable_name][data_subset[,variable_name]==1]="Hardly ever"
data_subset[,variable_name][data_subset[,variable_name]==2]="Occasionally"
data_subset[,variable_name][data_subset[,variable_name]==3]="Fairly often"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very often"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



```{r, message=F, warning=F}
variable_name="OHIP_Q8"

#OHIP_Q1	0= Never
#	1= Hardly ever
#	2= Occasionally
#	3= Fairly often 
#	4= Very often 

 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Never"
data_subset[,variable_name][data_subset[,variable_name]==1]="Hardly ever"
data_subset[,variable_name][data_subset[,variable_name]==2]="Occasionally"
data_subset[,variable_name][data_subset[,variable_name]==3]="Fairly often"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very often"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



```{r, message=F, warning=F}
variable_name="OHIP_Q9"

#OHIP_Q1	0= Never
#	1= Hardly ever
#	2= Occasionally
#	3= Fairly often 
#	4= Very often 

 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Never"
data_subset[,variable_name][data_subset[,variable_name]==1]="Hardly ever"
data_subset[,variable_name][data_subset[,variable_name]==2]="Occasionally"
data_subset[,variable_name][data_subset[,variable_name]==3]="Fairly often"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very often"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="OHIP_Q10"

#OHIP_Q1	0= Never
#	1= Hardly ever
#	2= Occasionally
#	3= Fairly often 
#	4= Very often 

 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Never"
data_subset[,variable_name][data_subset[,variable_name]==1]="Hardly ever"
data_subset[,variable_name][data_subset[,variable_name]==2]="Occasionally"
data_subset[,variable_name][data_subset[,variable_name]==3]="Fairly often"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very often"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, message=F, warning=F}
variable_name="OHIP_Q11"

#OHIP_Q1	0= Never
#	1= Hardly ever
#	2= Occasionally
#	3= Fairly often 
#	4= Very often 

 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Never"
data_subset[,variable_name][data_subset[,variable_name]==1]="Hardly ever"
data_subset[,variable_name][data_subset[,variable_name]==2]="Occasionally"
data_subset[,variable_name][data_subset[,variable_name]==3]="Fairly often"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very often"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="OHIP_Q12"

#OHIP_Q1	0= Never
#	1= Hardly ever
#	2= Occasionally
#	3= Fairly often 
#	4= Very often 

 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Never"
data_subset[,variable_name][data_subset[,variable_name]==1]="Hardly ever"
data_subset[,variable_name][data_subset[,variable_name]==2]="Occasionally"
data_subset[,variable_name][data_subset[,variable_name]==3]="Fairly often"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very often"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="OHIP_Q13"

#OHIP_Q1	0= Never
#	1= Hardly ever
#	2= Occasionally
#	3= Fairly often 
#	4= Very often 

 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Never"
data_subset[,variable_name][data_subset[,variable_name]==1]="Hardly ever"
data_subset[,variable_name][data_subset[,variable_name]==2]="Occasionally"
data_subset[,variable_name][data_subset[,variable_name]==3]="Fairly often"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very often"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, message=F, warning=F}
variable_name="OHIP_Q14"

#OHIP_Q1	0= Never
#	1= Hardly ever
#	2= Occasionally
#	3= Fairly often 
#	4= Very often 

 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Never"
data_subset[,variable_name][data_subset[,variable_name]==1]="Hardly ever"
data_subset[,variable_name][data_subset[,variable_name]==2]="Occasionally"
data_subset[,variable_name][data_subset[,variable_name]==3]="Fairly often"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very often"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="Fear_Pain_Q1"

#Fear_Pain_Q1	1= Not at all
#	2= A little 
#	3= A fair amount
#	4= Very much
#	5= Extreme


 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==1]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==2]="A little"
data_subset[,variable_name][data_subset[,variable_name]==3]="A fair amount"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very much"
data_subset[,variable_name][data_subset[,variable_name]==5]="Extreme"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, message=F, warning=F}
variable_name="Fear_Pain_Q2"

#Fear_Pain_Q1	1= Not at all
#	2= A little 
#	3= A fair amount
#	4= Very much
#	5= Extreme


 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==1]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==2]="A little"
data_subset[,variable_name][data_subset[,variable_name]==3]="A fair amount"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very much"
data_subset[,variable_name][data_subset[,variable_name]==5]="Extreme"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="Fear_Pain_Q3"

#Fear_Pain_Q1	1= Not at all
#	2= A little 
#	3= A fair amount
#	4= Very much
#	5= Extreme


 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==1]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==2]="A little"
data_subset[,variable_name][data_subset[,variable_name]==3]="A fair amount"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very much"
data_subset[,variable_name][data_subset[,variable_name]==5]="Extreme"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="Fear_Pain_Q4"

#Fear_Pain_Q1	1= Not at all
#	2= A little 
#	3= A fair amount
#	4= Very much
#	5= Extreme


 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==1]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==2]="A little"
data_subset[,variable_name][data_subset[,variable_name]==3]="A fair amount"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very much"
data_subset[,variable_name][data_subset[,variable_name]==5]="Extreme"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="Fear_Pain_Q5"

#Fear_Pain_Q1	1= Not at all
#	2= A little 
#	3= A fair amount
#	4= Very much
#	5= Extreme


 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==1]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==2]="A little"
data_subset[,variable_name][data_subset[,variable_name]==3]="A fair amount"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very much"
data_subset[,variable_name][data_subset[,variable_name]==5]="Extreme"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="Fear_Pain_Q6"

#Fear_Pain_Q1	1= Not at all
#	2= A little 
#	3= A fair amount
#	4= Very much
#	5= Extreme


 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==1]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==2]="A little"
data_subset[,variable_name][data_subset[,variable_name]==3]="A fair amount"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very much"
data_subset[,variable_name][data_subset[,variable_name]==5]="Extreme"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, message=F, warning=F}
variable_name="Fear_Pain_Q7"

#Fear_Pain_Q1	1= Not at all
#	2= A little 
#	3= A fair amount
#	4= Very much
#	5= Extreme


 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==1]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==2]="A little"
data_subset[,variable_name][data_subset[,variable_name]==3]="A fair amount"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very much"
data_subset[,variable_name][data_subset[,variable_name]==5]="Extreme"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="Fear_Pain_Q8"

#Fear_Pain_Q1	1= Not at all
#	2= A little 
#	3= A fair amount
#	4= Very much
#	5= Extreme


 

 


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==1]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==2]="A little"
data_subset[,variable_name][data_subset[,variable_name]==3]="A fair amount"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very much"
data_subset[,variable_name][data_subset[,variable_name]==5]="Extreme"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="Fear_Pain_Q9"

#Fear_Pain_Q1	1= Not at all
#	2= A little 
#	3= A fair amount
#	4= Very much
#	5= Extreme


data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==1]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==2]="A little"
data_subset[,variable_name][data_subset[,variable_name]==3]="A fair amount"
data_subset[,variable_name][data_subset[,variable_name]==4]="Very much"
data_subset[,variable_name][data_subset[,variable_name]==5]="Extreme"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, message=F, warning=F}
variable_name="Pain_catastrophizing_Q1"

#Pain_catastrophizing_Q1	0= Not at all
#	1= to a slight degree
#	2= to a moderate degree
#	3= to a great degree
#	4= at the time



data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==1]="to a slight degree"
data_subset[,variable_name][data_subset[,variable_name]==2]="to a moderate degree"
data_subset[,variable_name][data_subset[,variable_name]==3]="to a great degree"
data_subset[,variable_name][data_subset[,variable_name]==4]="all the time"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, message=F, warning=F}
variable_name="Pain_catastrophizing_Q2"

#Pain_catastrophizing_Q1	0= Not at all
#	1= to a slight degree
#	2= to a moderate degree
#	3= to a great degree
#	4= at the time



data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==1]="to a slight degree"
data_subset[,variable_name][data_subset[,variable_name]==2]="to a moderate degree"
data_subset[,variable_name][data_subset[,variable_name]==3]="to a great degree"
data_subset[,variable_name][data_subset[,variable_name]==4]="all the time"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="Pain_catastrophizing_Q3"

#Pain_catastrophizing_Q1	0= Not at all
#	1= to a slight degree
#	2= to a moderate degree
#	3= to a great degree
#	4= at the time



data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==1]="to a slight degree"
data_subset[,variable_name][data_subset[,variable_name]==2]="to a moderate degree"
data_subset[,variable_name][data_subset[,variable_name]==3]="to a great degree"
data_subset[,variable_name][data_subset[,variable_name]==4]="all the time"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



```{r, message=F, warning=F}
variable_name="Pain_catastrophizing_Q4"

#Pain_catastrophizing_Q1	0= Not at all
#	1= to a slight degree
#	2= to a moderate degree
#	3= to a great degree
#	4= at the time



data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==1]="to a slight degree"
data_subset[,variable_name][data_subset[,variable_name]==2]="to a moderate degree"
data_subset[,variable_name][data_subset[,variable_name]==3]="to a great degree"
data_subset[,variable_name][data_subset[,variable_name]==4]="all the time"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="Pain_catastrophizing_Q5"

#Pain_catastrophizing_Q1	0= Not at all
#	1= to a slight degree
#	2= to a moderate degree
#	3= to a great degree
#	4= at the time



data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==1]="to a slight degree"
data_subset[,variable_name][data_subset[,variable_name]==2]="to a moderate degree"
data_subset[,variable_name][data_subset[,variable_name]==3]="to a great degree"
data_subset[,variable_name][data_subset[,variable_name]==4]="all the time"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="Pain_catastrophizing_Q6"

#Pain_catastrophizing_Q1	0= Not at all
#	1= to a slight degree
#	2= to a moderate degree
#	3= to a great degree
#	4= at the time



data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==1]="to a slight degree"
data_subset[,variable_name][data_subset[,variable_name]==2]="to a moderate degree"
data_subset[,variable_name][data_subset[,variable_name]==3]="to a great degree"
data_subset[,variable_name][data_subset[,variable_name]==4]="all the time"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="Pain_catastrophizing_Q7"

#Pain_catastrophizing_Q1	0= Not at all
#	1= to a slight degree
#	2= to a moderate degree
#	3= to a great degree
#	4= at the time



data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==1]="to a slight degree"
data_subset[,variable_name][data_subset[,variable_name]==2]="to a moderate degree"
data_subset[,variable_name][data_subset[,variable_name]==3]="to a great degree"
data_subset[,variable_name][data_subset[,variable_name]==4]="all the time"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="Pain_catastrophizing_Q8"

#Pain_catastrophizing_Q1	0= Not at all
#	1= to a slight degree
#	2= to a moderate degree
#	3= to a great degree
#	4= at the time



data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==1]="to a slight degree"
data_subset[,variable_name][data_subset[,variable_name]==2]="to a moderate degree"
data_subset[,variable_name][data_subset[,variable_name]==3]="to a great degree"
data_subset[,variable_name][data_subset[,variable_name]==4]="all the time"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="Pain_catastrophizing_Q9"

#Pain_catastrophizing_Q1	0= Not at all
#	1= to a slight degree
#	2= to a moderate degree
#	3= to a great degree
#	4= at the time



data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==1]="to a slight degree"
data_subset[,variable_name][data_subset[,variable_name]==2]="to a moderate degree"
data_subset[,variable_name][data_subset[,variable_name]==3]="to a great degree"
data_subset[,variable_name][data_subset[,variable_name]==4]="all the time"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="Pain_catastrophizing_Q10"

#Pain_catastrophizing_Q1	0= Not at all
#	1= to a slight degree
#	2= to a moderate degree
#	3= to a great degree
#	4= at the time



data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==1]="to a slight degree"
data_subset[,variable_name][data_subset[,variable_name]==2]="to a moderate degree"
data_subset[,variable_name][data_subset[,variable_name]==3]="to a great degree"
data_subset[,variable_name][data_subset[,variable_name]==4]="all the time"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, message=F, warning=F}
variable_name="Pain_catastrophizing_Q11"

#Pain_catastrophizing_Q1	0= Not at all
#	1= to a slight degree
#	2= to a moderate degree
#	3= to a great degree
#	4= at the time



data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==1]="to a slight degree"
data_subset[,variable_name][data_subset[,variable_name]==2]="to a moderate degree"
data_subset[,variable_name][data_subset[,variable_name]==3]="to a great degree"
data_subset[,variable_name][data_subset[,variable_name]==4]="all the time"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


```{r, message=F, warning=F}
variable_name="Pain_catastrophizing_Q12"

#Pain_catastrophizing_Q1	0= Not at all
#	1= to a slight degree
#	2= to a moderate degree
#	3= to a great degree
#	4= at the time



data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==1]="to a slight degree"
data_subset[,variable_name][data_subset[,variable_name]==2]="to a moderate degree"
data_subset[,variable_name][data_subset[,variable_name]==3]="to a great degree"
data_subset[,variable_name][data_subset[,variable_name]==4]="all the time"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

```{r, message=F, warning=F}
variable_name="Pain_catastrophizing_Q13"

#Pain_catastrophizing_Q1	0= Not at all
#	1= to a slight degree
#	2= to a moderate degree
#	3= to a great degree
#	4= at the time



data_subset=data %>% dplyr::count(!!rlang::sym(variable_name)) %>% mutate(prop=round(n/nrow(data),4))

data_subset[,variable_name][data_subset[,variable_name]==0]="Not at all"
data_subset[,variable_name][data_subset[,variable_name]==1]="to a slight degree"
data_subset[,variable_name][data_subset[,variable_name]==2]="to a moderate degree"
data_subset[,variable_name][data_subset[,variable_name]==3]="to a great degree"
data_subset[,variable_name][data_subset[,variable_name]==4]="all the time"

data_subset%>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


if (nrow(data_subset)>1)
 discrete_variable_func(data_subset, variable_name) %>%
datatable(extensions = 'Buttons',
          caption=variable_name,
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```