---
title: "group 5"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2025-05-30"
---

```{r, echo=F, message=F, warning=F, results=F}
library(rprojroot)
root <- rprojroot::find_rstudio_root_file()
source(file.path(root, "analysis/Rfunctions.R"))
root <- rprojroot::find_rstudio_root_file()
```



```{r, message=F, warning=F, results=F}
#data_raw=multiplesheets("C:\\Shengtong\\Research\\AllCollaboration\\2024\\202410\\Neal\\CBCT Thesis data FINAL VK011525.xlsx")
finalized_data=as_tibble(read.csv(file.path(root,"..\\2024\\202410\\Neal\\CBCT Thesis data FINAL VK011525_Finalized_Data.csv")))

#finalized_with_omitted_data=data_raw$`Finalized with Omitted data`
#coding=data_raw$`Coding`
#save(finalized_with_omitted_data, finalized_data, coding, file="C:\\Shengtong\\Research\\AllCollaboration\\2024\\202410\\Neal\\data.RData")
#load("C:\\Shengtong\\Research\\AllCollaboration\\2024\\202410\\Neal\\data.RData")


#colnames(finalized_data)

finalized_data=finalized_data %>% filter(Subject!=185)  #excluding subject 185 requested by Vrisiis 
```




```{r, message=F, warning=F}
upper_posterior=c(2, 3, 4, 5, 12, 13, 14, 15)
upper_anterior=6:11
lower_posterior=c(18, 19, 20, 21, 28, 29, 30, 31)
lower_anterior=22:27
```






```{r, message=F, warning=F, eval=T}
continuous_var=c("Age", 
"Months_btwn_CBCTS",  
"Months_btwn_Ext_CBCT.1",
"mesial_tooth_bone_loss_CBCT.2__mm",   
"mesial_tooth_bone_loss_DIFF", 
"mesial_tooth_bone_loss_CBCT.1__mm",
"distal_tooth_bone_loss_CBCT.1__mm",    
"distal_tooth_bone_loss_CBCT.2__mm",   
"distal_tooth_bone_loss_DIFF",    
"ANPNS_Crest_Coronal_CBCT1",
"ANSPNS_Crest_Coronal_CBCT2",          
"ANSPNS_Crest_Coronal_DIFF",           
"ANSPNS_Crest_Sagittal_CBCT1",        
"ANSPNS_Crest_Sagittal_CBCT2",         
"ANSPNS_Crest_Sagittal_DIFF",          
"ANSPNS_Sinus_Floor_Coronal_CBCT1",   
"ANSPNS_Sinus_Floor_Coronal_CBCT2",    
"ANSPNS_Sinus_Floor_Coronal_DIFF",     
"ANSPNS_Sinus_Floor_Sagittal_CBCT1",   
"ANSPNS_Sinus_Floor_Sagittal_CBCT2",   
"ANSPNS_Sinus_Floor_Sagittal_DIFF",    
"MENTAL_Crest_Coronal_CBCT1",         
"MENTAL_Crest_Coronal_CBCT2",         
 "MENTAL_Crest_Coronal_DIFF",           
"MENTAL_Crest_Sagittal_CBCT1",         
"MENTAL_Crest_Sagittal_CBCT2",         
"MENTAL_Crest_Sagittal_DIFF",
"Width_3mm_CBCT1",                     
"Width_3mm_CBCT2",                     
"Width_3mm_DIFF",                      
"Width_5mm_CBCT1",                     
"Width_5mm_CBCT2",                     
"Width_5mm_DIFF")
data_conti=data.frame(as.matrix(finalized_data[,which(colnames(finalized_data)%in%continuous_var)]))


###################### definitions
#Height_coronal_CBCT1 = ANS_PNS_crest_coronal_CBCT1 + mental_crest_coronal_CBCT1
#Height_coronal_CBCT2 = ANS_PNS_crest_coronal_CBCT2 + mental_crest_coronal_CBCT2
#Height_sagittal_CBCT1 = ANS_PNS_crest_sagittal_CBCT1 + mental_crest_sagittal_CBCT1
#Height_sagittal_CBCT2 = ANS_PNS_crest_sagittal_CBCT2 + mental_crest_sagittal_CBCT2


data_conti$Height_coronal_CBCT1=
  ifelse(is.na(data_conti$ANPNS_Crest_Coronal_CBCT1), 0, data_conti$ANPNS_Crest_Coronal_CBCT1) +
  ifelse(is.na(data_conti$MENTAL_Crest_Coronal_CBCT1), 0, data_conti$MENTAL_Crest_Coronal_CBCT1)
##############

data_conti$Height_coronal_CBCT2 <- 
  ifelse(is.na(data_conti$ANSPNS_Crest_Coronal_CBCT2), 0, data_conti$ANSPNS_Crest_Coronal_CBCT2) + 
  ifelse(is.na(data_conti$MENTAL_Crest_Coronal_CBCT2), 0, data_conti$MENTAL_Crest_Coronal_CBCT2)
##############

data_conti$Height_sagittal_CBCT1 <- 
  ifelse(is.na(data_conti$ANSPNS_Crest_Sagittal_CBCT1), 0, data_conti$ANSPNS_Crest_Sagittal_CBCT1) +  
  ifelse(is.na(data_conti$MENTAL_Crest_Sagittal_CBCT1), 0, data_conti$MENTAL_Crest_Sagittal_CBCT1)
  
##############

data_conti$Height_sagittal_CBCT2 <- 
  ifelse(is.na(data_conti$ANSPNS_Crest_Sagittal_CBCT2), 0, data_conti$ANSPNS_Crest_Sagittal_CBCT2) +
  ifelse(is.na(data_conti$MENTAL_Crest_Sagittal_CBCT2), 0, data_conti$MENTAL_Crest_Sagittal_CBCT2) 


##############

data_conti$Height_coronal_DIFF <- 
  ifelse(is.na(data_conti$ANSPNS_Crest_Coronal_DIFF), 0, data_conti$ANSPNS_Crest_Coronal_DIFF) +  
  ifelse(is.na(data_conti$MENTAL_Crest_Coronal_DIFF), 0, data_conti$MENTAL_Crest_Coronal_DIFF)
##############

data_conti$Height_sagittal_DIFF <- 
  ifelse(is.na(data_conti$ANSPNS_Crest_Sagittal_DIFF), 0, data_conti$ANSPNS_Crest_Sagittal_DIFF) +
  ifelse(is.na(data_conti$MENTAL_Crest_Sagittal_DIFF), 0, data_conti$MENTAL_Crest_Sagittal_DIFF)
#################


continuous_var=c(continuous_var,"Height_sagittal_CBCT1", "Height_sagittal_CBCT2", "Height_sagittal_DIFF",  "Height_coronal_DIFF", "Height_coronal_CBCT1", "Height_coronal_CBCT2" )

finalized_data$Height_coronal_CBCT1=data_conti$Height_coronal_CBCT1
finalized_data$Height_coronal_CBCT2=data_conti$Height_coronal_CBCT2
finalized_data$Height_sagittal_CBCT1=data_conti$Height_sagittal_CBCT1
finalized_data$Height_sagittal_CBCT2=data_conti$Height_sagittal_CBCT2
finalized_data$Height_coronal_DIFF=data_conti$Height_coronal_DIFF
finalized_data$Height_sagittal_DIFF=data_conti$Height_sagittal_DIFF

#res=summary_statistics(data_conti)
#data.frame(res) %>%
#datatable(extensions = 'Buttons',
#          caption = "",
#            options = list(dom = 'Blfrtip',
#                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
#                           lengthMenu = list(c(10,25,50,-1),
#                                             c(10,25,50,"All"))))
```




```{r, message=F, warning=F}
#Group 5 (NEW group): include only patients with partially_edentulous YES
group5_data=finalized_data %>% filter(Partially_edentulous =="Y")



#group5_data%>%
#datatable(extensions = 'Buttons',
#          caption = "group 5",
#            options = list(dom = 'Blfrtip',
#                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
#                           lengthMenu = list(c(10,25,50,-1),
#                                             c(10,25,50,"All"))))
```


## 1. home

[home](2024_1002_Neal.html)



## 2. continuous variables



```{r, message=F, warning=F}

data_conti=as.matrix(group5_data[,which(colnames(group5_data)%in%continuous_var)])

res=summary_statistics(data_conti)
data.frame(res) %>%
datatable(extensions = 'Buttons',
          caption = "",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```



```{r, message=F, warning=F}
################ compute p values 
#data_conti[is.na(data_conti)] <- "0"
#cormat2=round(cor(data_conti, method="pearson", use = "na.or.complete"),2)
cormat2=matrix(nrow=ncol(data_conti), ncol=ncol(data_conti))
cormat2_pvalue=matrix(nrow=nrow(cormat2), ncol=nrow(cormat2))
for (i in 1:nrow(cormat2))
  for (j in 1:nrow(cormat2))
    {
    combine_data=data.frame(x=as.numeric(data_conti[,i]), y=as.numeric(data_conti[,j])) %>% drop_na()
    if (nrow(combine_data)>2)
    {
    test=cor.test(combine_data[,1], combine_data[,2], method="pearson", use = "na.or.complete")
    cormat2[i,j]=round(test$estimate,4)
    cormat2_pvalue[i,j]=round(test$p.value,4)
    }
    if (nrow(combine_data)<=2)  # no enough data to calculate correlations 
    {
     cormat2[i,j]="NA"
     cormat2_pvalue[i,j]="NA" 
      
    }
    
  }
row.names(cormat2)=colnames(data_conti) 
colnames(cormat2)=colnames(data_conti) 
cormat2 %>%
datatable(extensions = 'Buttons',
          caption = "Pearson correlation",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


row.names(cormat2_pvalue)=colnames(data_conti) 
colnames(cormat2_pvalue)=colnames(data_conti) 
cormat2_pvalue %>%
datatable(extensions = 'Buttons',
          caption = "P values of pearson correlation",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


correlation_pvalue=matrix(paste(cormat2, "(", cormat2_pvalue, ")", sep=""), nrow=nrow(cormat2))
rownames(correlation_pvalue)=row.names(cormat2)
colnames(correlation_pvalue)=row.names(cormat2)
correlation_pvalue%>%
datatable(extensions = 'Buttons',
          caption = "correlation (p value)",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```





```{r, message=F, warning=F}
################ compute p values 
#data_conti[is.na(data_conti)] <- "0"
#cormat2=round(cor(data_conti, method="pearson", use = "na.or.complete"),2)
cormat2=matrix(nrow=ncol(data_conti), ncol=ncol(data_conti))
cormat2_pvalue=matrix(nrow=nrow(cormat2), ncol=nrow(cormat2))
for (i in 1:nrow(cormat2))
  for (j in 1:nrow(cormat2))
    {
    combine_data=data.frame(x=as.numeric(data_conti[,i]), y=as.numeric(data_conti[,j])) %>% drop_na()
    if (nrow(combine_data)>2)
    {
    test=cor.test(combine_data[,1], combine_data[,2], method="spearman", use = "na.or.complete")
    cormat2[i,j]=round(test$estimate,4)
    cormat2_pvalue[i,j]=round(test$p.value,4)
    }
    if (nrow(combine_data)<=2)  # no enough data to calculate correlations 
    {
     cormat2[i,j]="NA"
     cormat2_pvalue[i,j]="NA" 
      
    }
    
  }
row.names(cormat2)=colnames(data_conti) 
colnames(cormat2)=colnames(data_conti) 
cormat2 %>%
datatable(extensions = 'Buttons',
          caption = "Spearman correlation",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


row.names(cormat2_pvalue)=colnames(data_conti) 
colnames(cormat2_pvalue)=colnames(data_conti) 
cormat2_pvalue %>%
datatable(extensions = 'Buttons',
          caption = "P values of spearman correlation",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


correlation_pvalue=matrix(paste(cormat2, "(", cormat2_pvalue, ")", sep=""), nrow=nrow(cormat2))
rownames(correlation_pvalue)=row.names(cormat2)
colnames(correlation_pvalue)=row.names(cormat2)
correlation_pvalue%>%
datatable(extensions = 'Buttons',
          caption = "Spearman correlation (p value)",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```





## 3. discrete variables 


```{r, message=F, warning=F}
discrete_var=c("Tooth_site_number", 
               "Tooth_migration", 
               "M_Tooth_Migration",  
               "D_Tooth_Migration",  
               "Migration_Notes", 
               "mesial_tooth_bone_loss_CBCT.1__mm", 
               "Jaw",                        
                "Arch_Fully_edentulous_both_CBCTs",
                "Partially_edentulous",
               "Partial_Edentulous_Space_.Length",
                "Adjacent_teeth_number",
               "Adjacent_Note",                      
                "Restoration_type",
               "Restoration_Notes",                  
                "Ext_Reason",                                   
                "Coronal_sinus_floor_shift",  
                "Sinus_Pathology",
                 "Sites_10mm_height_or_more",          
                 "X1st_CBCT_10mm_or_more",
               "X2nd_CBCT_10mm_or_more" )
data_discrete=group5_data[,which(colnames(group5_data)%in%discrete_var)]

res=apply(data_discrete, 2, discrete_summary)
```





```{r, message=F, warning=F, results='asis'}
# Create a tagList to collect all datatables
library(htmltools)
output_list <- tagList()
for (k in 1:length(res))
  
{

  res_df <- data.frame(res[[k]]) # Convert the current list element to a data frame
# Append the datatable to the output list
  output_list <- tagAppendChild(
    output_list,
    datatable(
      res_df,
      extensions = 'Buttons',
      caption = discrete_var[k],
      options = list(
        dom = 'Blfrtip',
        buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
        lengthMenu = list(c(10, 25, 50, -1), c(10, 25, 50, "All"))
      )
    )
  )
  
  ############# calculate p values 
parameters=character()
pvalue=numeric()
kk=0

if (nrow(res[[k]])>1)
  for (i in 1:(nrow(res[[k]])-1))
  for (j in (i+1):nrow(res[[k]]))
  {
    kk=kk+1
    parameters[kk]=paste(res[[k]][i,1], res[[k]][j,1], sep="_vs_")
    pvalue[kk]=pvalue_adjust(binom.test(c(res[[k]][i,2], res[[k]][j,2]), p = 0.5)$p.value)
  }
output_list <- tagAppendChild(
    output_list,
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
          caption = discrete_var[k],
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
)


  
  
  
}

# Render all datatables
output_list
```




```{r, message=F, warning=F}

discrete_var=c("Gender", "Smoking" )
data_discrete=group5_data[,which(colnames(group5_data)%in%discrete_var)]

res=apply(data_discrete, 2, discrete_summary)



# Create a tagList to collect all datatables
library(htmltools)
output_list <- tagList()
for (k in 1:length(res))
  
{

  res_df <- data.frame(res[[k]]) # Convert the current list element to a data frame
# Append the datatable to the output list
  output_list <- tagAppendChild(
    output_list,
    datatable(
      res_df,
      extensions = 'Buttons',
      caption = names(res)[k],
      options = list(
        dom = 'Blfrtip',
        buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
        lengthMenu = list(c(10, 25, 50, -1), c(10, 25, 50, "All"))
      )
    )
  )
  
  ############# calculate p values 
parameters=character()
pvalue=numeric()
kk=0
  for (i in 1:(nrow(res[[k]])-1))
  for (j in (i+1):nrow(res[[k]]))
  {
    kk=kk+1
    parameters[kk]=paste(res[[k]][i,1], res[[k]][j,1], sep="_vs_")
    pvalue[kk]=pvalue_adjust(binom.test(c(res[[k]][i,2], res[[k]][j,2]), p = 0.5)$p.value)
  }
output_list <- tagAppendChild(
    output_list,
data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
          caption = names(res)[k],
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
)


  
  
  
}

# Render all datatables
output_list

```




## 4. tooth site groups 

```{r, message=F, warning=F}
n=c(group5_data %>% filter(Tooth_site_number %in% upper_posterior) %>% nrow(), 
    group5_data %>% filter(Tooth_site_number %in% upper_anterior) %>% nrow(), 
    group5_data %>% filter(Tooth_site_number %in% lower_posterior) %>% nrow(), 
    group5_data %>% filter(Tooth_site_number %in% lower_anterior) %>% nrow())

tooth_site_groups=data.frame(groups=c("upper_posterior", "upper_anterior", "lower_posterior", "lower_anterior"), n=n) %>% mutate(prop=round(n/sum(n),4))

tooth_site_groups%>%
datatable(extensions = 'Buttons',
          caption = "tooth site groups",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


parameters=character()
pvalue=numeric()
kk=0
  for (i in 1:(nrow(tooth_site_groups)-1))
  for (j in (i+1):nrow(tooth_site_groups))
  {
    kk=kk+1
    parameters[kk]=paste(tooth_site_groups[i,1], tooth_site_groups[j,1], sep="_vs_")
    pvalue[kk]=pvalue_adjust(binom.test(c(tooth_site_groups[i,2], tooth_site_groups[j,2]), p = 0.5)$p.value)
  }


data.frame(comparison=parameters, pvalue=pvalue) %>%
datatable(extensions = 'Buttons',
          caption = "tooth site groups",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```







## 5. Variables with CBCT1 and CBCT2 versions


```{r, message=F, warning=F}
#"Height_coronal",
#"Height_sagittal",


variables=c("ANS_PNS_crest_coronal", 
"ANS_PNS_crest_sagittal",
"mental_crest_coronal",
"mental_crest_sagittal",
"ANS_PNS_sinus_floor_coronal",
"ANS_PNS_sinus_floor_sagittal", 
"width_3mm", 
"width_5mm",
"mesial_tooth_bone_loss",
"distal_tooth_bone_loss", 
"Height_coronal", 
"Height_sagittal")


CBCT1=data.frame(group5_data$ANPNS_Crest_Coronal_CBCT1, 
        group5_data$ANSPNS_Crest_Sagittal_CBCT1, 
        group5_data$MENTAL_Crest_Sagittal_CBCT1, 
        group5_data$MENTAL_Crest_Coronal_CBCT1, 
        group5_data$ANSPNS_Sinus_Floor_Coronal_CBCT1, 
        group5_data$ANSPNS_Sinus_Floor_Sagittal_CBCT1, 
        group5_data$Width_3mm_CBCT1, 
        group5_data$Width_5mm_CBCT1, 
        group5_data$mesial_tooth_bone_loss_CBCT.1__mm, 
        group5_data$distal_tooth_bone_loss_CBCT.1__mm, 
        group5_data$Height_coronal_CBCT1, 
        group5_data$Height_sagittal_CBCT1)


CBCT2=data.frame(group5_data$ANSPNS_Crest_Coronal_CBCT2, 
        group5_data$ANSPNS_Crest_Sagittal_CBCT2, 
        group5_data$MENTAL_Crest_Sagittal_CBCT2, 
        group5_data$MENTAL_Crest_Coronal_CBCT2, 
        group5_data$ANSPNS_Sinus_Floor_Coronal_CBCT2, 
        group5_data$ANSPNS_Sinus_Floor_Sagittal_CBCT2, 
        group5_data$Width_3mm_CBCT2, 
        group5_data$Width_5mm_CBCT2, 
        group5_data$mesial_tooth_bone_loss_CBCT.2__mm, 
        group5_data$distal_tooth_bone_loss_CBCT.2__mm, 
        group5_data$Height_coronal_CBCT2, 
        group5_data$Height_sagittal_CBCT2)

colnames(CBCT1)=colnames(CBCT2)=variables
CBCT1 <- CBCT1 %>% select(where(~ !all(is.na(.))))
CBCT2 <- CBCT2 %>% select(where(~ !all(is.na(.))))

pvalue <- sapply(1:ncol(CBCT1), function(i) t.test(CBCT1[,i], CBCT2[,i], paired = TRUE)$p.value)

data.frame(variables=colnames(CBCT1), pvalue=pvalue_adjust(pvalue))%>%
datatable(extensions = 'Buttons',
          caption = "CBCT 1 vs CBCT 2",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```


* variables full of NA need to be dropped 



##  6. descriptive statistics for maxilla and mandible in group 5


```{r, message=F, warning=F}

group5_maxilla=group5_data %>% filter(Jaw==1)
group5_mandible=group5_data %>% filter(Jaw==2)


data_conti=as.matrix(group5_maxilla[,which(colnames(group5_maxilla)%in%continuous_var)])

res=summary_statistics(data_conti)
data.frame(res) %>%
datatable(extensions = 'Buttons',
          caption = " maxilla in group 5",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


data_conti=as.matrix(group5_mandible[,which(colnames(group5_mandible)%in%continuous_var)])

res=summary_statistics(data_conti)
data.frame(res) %>%
datatable(extensions = 'Buttons',
          caption = " mandible in group 5",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))



```



## 7. continuous variable comparisons between maxilla and mandible

```{r, message=F, warning=F}

group5_maxilla_conti=as.matrix(group5_maxilla[,which(colnames(group5_maxilla)%in%continuous_var)])
group5_mandible_conti=as.matrix(group5_mandible[,which(colnames(group5_mandible)%in%continuous_var)])

pvalue=numeric()
pvalue <- sapply(1:ncol(group5_mandible_conti), function(i) {
  x <- group5_mandible_conti[, i]
  y <- group5_maxilla_conti[, i]
  if (sum(!is.na(x)) > 0 && sum(!is.na(y)) > 0) {
    t.test(x, y)$p.value
  } else {
    NA
  }
})

data.frame(variables=colnames(group5_mandible_conti), pvalue=pvalue_adjust(pvalue)) %>%
datatable(extensions = 'Buttons',
          caption = " ",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
 

```






## 8. discrete variable comparisons between maxilla and mandible

```{r, message=F, warning=F}

discrete_var=c("Tooth_site_number", 
               "Tooth_migration", 
               "M_Tooth_Migration",  
               "D_Tooth_Migration",  
               "Migration_Notes", 
               "mesial_tooth_bone_loss_CBCT.1__mm", 
               "Jaw",                        
                "Arch_Fully_edentulous_both_CBCTs",
                "Partially_edentulous",
               "Partial_Edentulous_Space_.Length",
                "Adjacent_teeth_number",
               "Adjacent_Note",                      
                "Restoration_type",
               "Restoration_Notes",                  
                "Ext_Reason",                                   
                "Coronal_sinus_floor_shift",  
                "Sinus_Pathology",
                 "Sites_10mm_height_or_more",          
                 "X1st_CBCT_10mm_or_more",
               "X2nd_CBCT_10mm_or_more" )

group5_maxilla_discrete=as.matrix(group5_maxilla[,which(colnames(group5_maxilla)%in%discrete_var)])
group5_mandible_discrete=as.matrix(group5_mandible[,which(colnames(group5_mandible)%in%discrete_var)])

# Prepare result list
results <- list()

# Loop through each column
for (col in colnames(group5_maxilla_discrete)) {
  x <- group5_maxilla_discrete[, col]
  y <- group5_mandible_discrete[, col]
  
  # Get unique non-NA values from both datasets
  levels <- unique(na.omit(c(x, y)))
  
  # For each outcome value in the column
  for (level in levels) {
    x_count <- sum(x == level, na.rm = TRUE)
    y_count <- sum(y == level, na.rm = TRUE)
    x_total <- sum(!is.na(x))
    y_total <- sum(!is.na(y))
    
    # 2x2 table: rows = groups, columns = outcome (yes/no)
    mat <- matrix(c(x_count, x_total - x_count,
                    y_count, y_total - y_count), 
                  nrow = 2, byrow = TRUE)
    
    # Run test
    test <- if (any(mat < 5)) fisher.test(mat) else prop.test(mat)
    
    # Save results
    results[[paste(col, level, sep = "_")]] <- list(
      column = col,
      level = level,
      p.value = pvalue_adjust(test$p.value),
      prop_maxilla = x_count / x_total,
      prop_mandible = y_count / y_total
    )
  }
}

# Convert results to a data frame
results_df <- do.call(rbind, lapply(results, as.data.frame))
rownames(results_df) <- names(results)
 
results_df%>%
datatable(extensions = 'Buttons',
          caption = " ",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```