---
title: "geographical distribution"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2024-12-19"
---



```{r, echo=F, message=F, warning=F}
library(rprojroot)
root <- rprojroot::find_rstudio_root_file()
```



```{r, echo=F, message=F, warning=F, results=F}
source(file.path(root, "analysis/Rfunctions.R"))
changeCellColor <- function(row, col){
  c(
    "function(row, data, num, index){",
    sprintf("  if(index == %d){", row-1),
    sprintf("    $('td:eq(' + %d + ')', row)", col),
    "    .css({'background-color': 'orange'});",
    "  }",
    "}"  
  )
}
```




```{r, echo=F, message=F, warning=F}
plot_function=function(title, data, legend_rows=1, var_name, num_size=3, legend_text_size=11, y_axis_text=12, custom_colors=Null)
{
  x_var <- sym(var_name)  ########## https://stackoverflow.com/questions/4856849/looping-over-variables-in-ggplot this is the key step for the loop 

  
  y_limit=max(data$n)*1.1
g1=ggplot(data, aes(x=!!x_var, y=n, fill=!!x_var)) +geom_bar(position = "dodge", stat="identity")+
  ylim(c(0, y_limit))+
  ylab("n")+xlab("")+
  #theme(legend.position="", legend.title=element_text(size=10))+
  theme(legend.position="bottom", legend.title=element_blank(), legend.text = element_text(size=legend_text_size))+
  theme(axis.text.x = element_blank())+
  theme(axis.text.y = element_text(size = y_axis_text))+
  #geom_text(aes(label=practice_setting2$n), position=position_dodge(width=0.9), vjust=-0.25, size=3)+  # add numbers over bars
  geom_text(label = with(data, paste(n, paste0("(", prop*100, "%", ")"))), vjust=-1, size=num_size)+
  ggtitle(title)+
  theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
   guides(fill = guide_legend(nrow = legend_rows))

if (!is.null(custom_colors)) {
    g1 <- g1 + scale_fill_manual(values = custom_colors)
  }

  return(g1)
}


plot_function2=function(title, data, legend_rows=1, var_name, num_size=3, legend_text_size=11, y_axis_text=12)
{
  
  x_var <- sym(var_name)  ########## https://stackoverflow.com/questions/4856849/looping-over-variables-in-ggplot this is the key step for the loop 

  
  y_limit=1
g1=ggplot(data, aes(x=!!x_var, y=prop, fill=!!x_var)) +geom_bar(position = "dodge", stat="identity")+
  ylim(c(0, y_limit))+
  ylab("%")+xlab("")+
  #theme(legend.position="", legend.title=element_text(size=10))+
  theme(legend.position="bottom", legend.title=element_blank(), legend.text = element_text(size=legend_text_size))+
  theme(axis.text.x = element_blank())+
  theme(axis.text.y = element_text(size = y_axis_text))+
  #geom_text(aes(label=practice_setting2$n), position=position_dodge(width=0.9), vjust=-0.25, size=3)+  # add numbers over bars
  geom_text(label = with(data, paste(paste0(prop*100, "%", "(", n, ")"))), vjust=-1, size=num_size)+
  ggtitle(title)+
  theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
   guides(fill = guide_legend(nrow = legend_rows))
  return(g1)
}


side_by_side_barplot2=function(data, angle=0, num_size=3, x_text_size=10, legend_text_size=10, title, legend_rows=1)
{
  y_limit=max(data$n)*1.1
  g=ggplot(data, aes(x=gender, y=n, fill=class)) +geom_bar(position = "dodge", stat="identity")+
  ylim(c(0, y_limit))+
  ylab("n")+xlab("")+
  theme(legend.position="bottom", legend.text = element_text(size=legend_text_size))+
  theme(axis.text.x = element_text(angle = angle, vjust = 0.5, size=x_text_size))+
  #geom_text(aes(label=n), position=position_dodge(width=0.9), vjust=-0.25, size=num_size)+  # add numbers over bars
  geom_text(label = with(data, paste(n, paste0("(", prop*100, "%", ")"))),  position=position_dodge(width=0.9), vjust=-1, size=num_size)+
  #geom_text(label = with(gender_geo_data, paste(num, paste0('(', Percent, ')'))), vjust=-1)
  ggtitle(title)+
  theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
    guides(fill = guide_legend(nrow = legend_rows))
 return(g)
  
}


side_by_side_barplot3=function(data, angle=0, num_size=3, x_text_size=10, legend_text_size=10, title, legend_rows=1, fill_var="genders_group", custom_colors=Null)
{
  y_limit=max(data$n)*1.1
  g=ggplot(data, aes(x=races, y=prop, fill=!!sym(fill_var))) +geom_bar(position = "dodge", stat="identity")+
 # ylim(c(0,y_limit))+
  ylab("prop")+xlab("")+
  theme(legend.position="bottom", legend.text = element_text(size=legend_text_size))+
  theme(axis.text.x = element_text(angle = angle, vjust = 0.5, size=x_text_size))+
  #geom_text(aes(label=n), position=position_dodge(width=0.9), vjust=-0.25, size=num_size)+  # add numbers over bars
  #geom_text(label = with(data, paste(n, paste0("(", prop*100, "%", ")"))),  position=position_dodge(width=0.9), vjust=-1, size=num_size)+
    geom_text(label = with(data, paste(paste0(prop*100, "%", "(", n, ")"))),  position=position_dodge(width=0.9), vjust=-1, size=num_size)+
  #geom_text(label = with(gender_geo_data, paste(num, paste0('(', Percent, ')'))), vjust=-1)
  ggtitle(title)+
  theme(plot.title = element_text(hjust = 0.5, size=15))+  #center the title
    guides(fill = guide_legend(nrow = legend_rows))
  
  if (!is.null(custom_colors)) {
    g <- g + scale_fill_manual(values = custom_colors)
  }
 return(g)
  
}

```



## Home 

[Home](2024_0701_survey.html)



```{r, message=F, warning=F, results=F, eval=F}
#Dentist_Survey=multiplesheets(file.path(root, "..\\2024\\202407\\state_survey\\Dentist Survey.xlsx"))
Dentist_Survey=multiplesheets("C:\\Shengtong\\Research\\AllCollaboration\\2024\\202407\\state_survey\\Dentist Survey.xlsx")
Dentist_in_WI=Dentist_Survey$`Dentist Survey` %>% filter(`direct care as a dentist in Wisconsin`=="Yes")
#save(Dentist_in_WI, file="C:\\Shengtong\\Research\\AllCollaboration\\2024\\202407\\Dentist_in_WI.RData")
```


* select individuals who respond Yes to `direct care as a dentist in Wisconsin`



```{r, message=F, warning=F}
root <- rprojroot::find_rstudio_root_file()
load(file.path(root,"..\\2024\\202407\\Dentist_in_WI.RData"))

variables=colnames(Dentist_in_WI)
data.frame(questions=variables)%>%
datatable(extensions = 'Buttons',
          caption = "",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
dim(Dentist_in_WI)
```

* in total 2295 responses and 40 questions 




```{r, message=F, warning=F}
variables_of_interest=variables[-c(6,7,19:37)]
dentist_in_WI_of_interest=Dentist_in_WI[,-c(6,7,19:37)]
num_non_missing=apply(dentist_in_WI_of_interest,2, function(x) sum(is.na(x)==F) )
data.frame(variable=variables_of_interest, non_missing=num_non_missing)%>%
datatable(extensions = 'Buttons',
          caption = " Interesting variables with non-missing numbers ",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


date_of_birth=dentist_in_WI_of_interest$`Date of Birth`
year_of_birth=str_sub(date_of_birth, nchar(date_of_birth)-3, nchar(date_of_birth))
ages=2024-as.numeric(year_of_birth)

dentist_in_WI_of_interest1=dentist_in_WI_of_interest %>% mutate(ages=ages)

```







```{r, message=F, warning=F, results=F}
wisconsin_urban_rural_zip=multiplesheets("C:\\Shengtong\\Research\\OralPublicHealth\\Dental_Emergency_visit\\Wisconsin-Urban-Rural-zip.xlsx")
```


* [Wisconsin state urban rural code](https://marq-my.sharepoint.com/:x:/g/personal/shengtong_han_marquette_edu/ETU5WgJJl9BIoNsBBNhPqocBR3DcuAN3q1H65LThX3eeuQ?e=Ozruo2)



```{r, message=F, warning=F}
region_code=unique(wisconsin_urban_rural_zip$`Table 1`$`2014 ZCTA-based WURC Code`)
all_code=wisconsin_urban_rural_zip$`Table 1`$`2014 ZCTA-based WURC Code`
all_code[which(all_code=="R2/R1")]="R2"   # rename regions 
all_code[which(all_code=="Urban/R1")]="Urban"
all_code[which(all_code=="Metro W-O-W/R1")]="Metro W-O-W"
all_code[which(all_code=="R3/R1")]="R3"
all_code[which(all_code=="R3/R2/R1")]="R3"
all_code[which(all_code=="Urban/R2")]="Urban"
all_code[which(all_code=="R1/Urban")]="R1"
wisconsin_urban_rural_zip_data=wisconsin_urban_rural_zip$`Table 1` %>% mutate(new_region_code=all_code)
region_code_update=unique(all_code)
```


```{r, message=F, warning=F, eval=T}
region_code_zip=sapply(region_code_update, function(x) wisconsin_urban_rural_zip_data %>% filter(new_region_code==x) %>% select(`ZCTA/\r\nZIPCode`)) # extract zip codes 



dentist_zip=unique(dentist_in_WI_of_interest1 %>% select(`5-digit Zip code` ) %>% pull)
#sum(is.na(Dentist_Survey_zipcode)==T) 893 zip codes are missing 


zip_in_dentist_only=setdiff(dentist_zip, unlist(region_code_zip)) #### zip codes in the survey, but not in Wisconsin urban rural zip data 
#dentist_in_WI_of_interest1 %>% filter(`5-digit Zip code` %in% zip_in_dentist_only)%>% filter(`Gender Identity`=="Man" | `Gender Identity`=="Woman") %>% nrow() # these 886 man/woman in the survey, but missed in wisconsin urban/rural data

data.frame(zip_in_dentist_only)%>%
datatable(extensions = 'Buttons',
          caption = " Zip codes in the survey, but not in Wisconsin zip code list",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



* among  77 zip codes missing, i.e. not in Wisconsin zip code list,  some code (46/77=59.7%) have sub-code like `53574-8881`, but Wisconsin zip code don't have sub-code.  




```{r, message=F, warning=F, eval=F}
region_code_zip=sapply(region_code_update, function(x) wisconsin_urban_rural_zip_data %>% filter(new_region_code==x) %>% select(`ZCTA/\r\nZIPCode`)) # extract zip codes 




dentist_zip_raw=unique(dentist_in_WI_of_interest1 %>% select(`5-digit Zip code` ) %>% pull)
dentist_zip=str_sub(dentist_zip_raw, 1, 5)  # extract the first 5 numbers as zip code 

zip_in_dentist_only=setdiff(dentist_zip, unlist(region_code_zip)) #### zip codes in the survey, but not in Wisconsin urban rural zip data 
Dentist_Survey_zipcode=dentist_in_WI_of_interest1 %>% select(`5-digit Zip code`) %>% pull()


dentist_in_WI_of_interest1 %>% filter(`5-digit Zip code` %in% zip_in_dentist_only)%>% filter(`Gender Identity`=="Man" | `Gender Identity`=="Woman") %>% nrow() # these 886 man/woman in the survey, but missed in wisconsin urban/rural data

data.frame(zip_in_dentist_only)%>%
datatable(extensions = 'Buttons',
          caption = " Zip codes in the survey, but not in Wisconsin zip code list",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))



dentist_zip_in_dentist_only=sapply(zip_in_dentist_only, function(x) Dentist_Survey$`Dentist Survey` %>% filter(`5-digit Zip code` %in% x)%>% filter(`Gender Identity`=="Man" | `Gender Identity`=="Woman") %>% nrow())

```



## Gender Identity


```{r, echo=F, message=F, warning=F}
side_by_side_barplot=function(data, angle=0, num_size=3, x_text_size=10, legend_text_size=10, title, custom_colors=Null)
{
  y_limit=max(data$num)*1.1
  g=ggplot(data, aes(x=geo, y=num, fill=gender)) +geom_bar(position = "dodge", stat="identity")+
  ylim(c(0, y_limit))+
  ylab("n")+xlab("")+
  theme(legend.position="bottom", legend.text = element_text(size=legend_text_size))+
  theme(axis.text.x = element_text(angle = angle, vjust = 0.5, size=x_text_size))+
  #geom_text(aes(label=num), position=position_dodge(width=0.9), vjust=-0.25, size=num_size)+  # add numbers over bars
  geom_text(label = with(gender_geo_data, paste(num, paste0('(', prop*100, "%", ')'))), position=position_dodge(width=0.9), vjust=-1, size=num_size)+
  ggtitle(title)+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title
  
  
  if (!is.null(custom_colors)) {
    g <- g + scale_fill_manual(values = custom_colors)
  }
  
 return(g)
  
}
```








```{r, message=F, warning=F, eval=T}
gender_geo=sapply(region_code_zip, function(x) dentist_in_WI_of_interest1 %>% filter(`5-digit Zip code` %in% x) %>% select(`Gender Identity`))
gender_prop=sapply(gender_geo, function(x) c(sum(x=="Man", na.rm=T), sum(x=="Woman", na.rm=T))) 
gender_geo_data=data.frame(geo=rep(region_code_update,each=2), num=as.vector(gender_prop), gender=rep(c("Man", "Woman"), length(region_code_update))) %>% drop_na()


man_total=sum(gender_geo_data %>% filter(gender=="Man") %>% select(num) %>% pull())
woman_total=sum(gender_geo_data %>% filter(gender=="Woman") %>% select(num) %>% pull())
prop=numeric()
prop[seq(1,11,by=2)]=gender_geo_data$num[seq(1,11,by=2)]/man_total
prop[seq(2,12,by=2)]=gender_geo_data$num[seq(2,12,by=2)]/woman_total
gender_geo_data=gender_geo_data %>% mutate(prop=round(prop,4))

fig=side_by_side_barplot(gender_geo_data, angle=10, num_size = 2.5, x_text_size=12, legend_text_size=12, title="Dentist_Survey", custom_colors= c("Woman" = "red", "Man" = "blue"))
fig


gender_geo_data%>%
datatable(extensions = 'Buttons',
          caption = "Dentist",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
sum(gender_geo_data$num)
```



## specialty distribution 





```{r, message=F, warning=F, eval=T}
specialty=c("General dentistry", "Endodontics", "Orthodontics","Periodontics",  "Prosthodontics", "Pediatric dentistry", "Oral surgery")
specialty_geo=sapply(region_code_zip, function(x) dentist_in_WI_of_interest1 %>% filter(`5-digit Zip code` %in% x) %>% filter(`Dental Specialties Board Certified` %in% specialty) %>% select(`Dental Specialties Board Certified`))
specialty_prop=sapply(specialty_geo, function(x) c(sum(x=="General dentistry"), sum(x=="Endodontics"), sum(x=="Orthodontics"), sum(x=="Periodontics"), sum(x=="Prosthodontics"), sum(x=="Pediatric dentistry"), sum(x=="Oral surgery"))) 
specialty_geo_data=data.frame(geo=rep(region_code_update,each=length(specialty)), num=as.vector(specialty_prop), spect=rep(specialty, length(region_code_update))) %>% drop_na()

figures=list()
pie_chart=list()
for (i in 1:length(region_code_update))
  
{
   figures[[i]]=ggplot(specialty_geo_data %>% filter(geo %in% region_code_update[i]), aes(x=spect, y=num, fill=spect)) +geom_bar(position = "dodge", stat="identity")+
  ylim(c(0, max(specialty_geo_data %>% filter(geo %in% region_code_update[i]) %>% select(num)%>% pull())+10))+
 # facet_grid("geo")+
  ylab("n")+xlab("")+
  theme(legend.position="")+
  theme(axis.text.x = element_text(angle = 60, vjust = 0.5, size=10))+
  geom_text(aes(label=num), position=position_dodge(width=0.9), vjust=-0.25, size=3)+  # add numbers over bars
  ggtitle(region_code_update[i])+
  theme(plot.title = element_text(hjust = 0.5, size=15))  #center the title
  
  pie_data=specialty_geo_data %>% filter(geo %in% region_code_update[i])
  pie_data <- pie_data %>% 
  mutate(per=`num`/sum(`num`)) %>% 
  arrange(desc(spect))
pie_data$label <- scales::percent(pie_data$per)
pie_chart[[i]]=ggplot(data=pie_data)+
  geom_bar(aes(x="", y=per, fill=spect), stat="identity", width = 1)+
  coord_polar("y", start=0)+
  theme_void()+
  geom_text(aes(x=1, y = cumsum(per) - per/2, label=label))
   
   
}
  
ggarrange(figures[[1]], figures[[2]], figures[[3]], figures[[4]], figures[[5]], figures[[6]], ncol=2)






gender_geo_data%>%
datatable(extensions = 'Buttons',
          caption = "",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
sum(gender_geo_data$num)
```





## zip codes 


```{r, message=F, warning=F, results=F}
zip_code_details=multiplesheets("C:\\Shengtong\\Research\\AllCollaboration\\2024\\202407\\state_survey\\ZIP code details.xlsx")

```