---
title: "03/05 2025"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2025-03-05"
---




```{r, echo=F, message=F, warning=F, results=F}
library(rprojroot)
root <- rprojroot::find_rstudio_root_file()
source(file.path(root, "analysis/Rfunctions.R"))
root <- rprojroot::find_rstudio_root_file()
```


```{r, message=F, warning=F, results=F}
MBSE_23=multiplesheets_without_headers((file.path(root, "..\\2025\\202503\\Zainab\\23 Tablet grades seperated by exam.xlsx")))
MBSE_24=multiplesheets_without_headers((file.path(root, "..\\2025\\202503\\Zainab\\OT Research - 24 MBSE.xlsx")))
```

`
Probe only
23 Probe has 28 questions in one line
24 Probe has 4 lines per person 
Columns C - I
1st row for each person is 1 - 7
2nd row per person is 8 - 14
3rd row per person is 15 - 21
4th row per person is 22 - 28
Explorer, sickle, universal, area specific is set up as the 24 probe with 4 lines per person 
Cumulative was not evaluated the same and should not be considered in the analysis
`



## probe 

```{r, message=F, warning=F}
data_23=MBSE_23$`23 Probe`
data_24=MBSE_24$`24 Probe`
```




```{r, message=F, warning=F}
student_names=unique(data_24$...1)
num_rows=sapply(student_names, function(x) (data_24 %>% filter(`...1`==x) %>% nrow()))
sum(num_rows==4)==length(num_rows)  # ensure all students have 4 rows 
```


```{r, message=F, warning=F}
data_23_clean=data_23[,5:32]

data_24_clean <- data_24 %>%
  filter(`...1` %in% student_names) %>%
  arrange(factor(`...1`, levels = student_names)) %>%
  select(3:9) %>%
  as.matrix() %>%
  t() %>%
  as.vector() %>%
  matrix(nrow = length(student_names), byrow = TRUE)  


```



