---
title: "12/16 2025"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2025-12-16"
---

```{r, echo=F, message=F, warning=F, results=F}
library(rprojroot)
root <- rprojroot::find_rstudio_root_file()
source(file.path(root, "analysis/Rfunctions.R"))
root <- rprojroot::find_rstudio_root_file()
path="C:/Shengtong/Research/AllCollaboration"
```






```{r, message=F, warning=F}
 
clean_data=read.csv(paste0(path, "/2025/202512/Sarah/clean_data.csv"),header=T)


```

## sample size determination 



```{r, message=F, warning=F}
sample_size=numeric()
for (i in 1:nrow(clean_data))
  
{
  before=as.numeric(clean_data[i, c(1,3,5,7)])
  after=as.numeric(clean_data[i, c(2,4,6,8)])
  delta=mean(before, na.rm=T)-mean(after, na.rm = T)
  sd=min(sd(before, na.rm=T), sd(after, na.rm=T))
  sample_size[i]=power.t.test(delta=delta, sd=sd, sig.level = 0.05, power=0.9)
}
#round(unlist(sample_size))

names1=paste("Maxillary", paste(rep(c("UR4 buccal", "UR4 lingual", "UR6 mesio-buccal", "UR6 distal-buccal", "UR6 lingual", "UL4 buccal", "UL4 lingual", "UL6 mesio-buccal", "UL6 distal-buccal", "UL6 lingual"), each=3), c("3mm", "6mm", "9mm"), sep="_"), sep="_")

names2=paste("Mandibular", paste(rep(c("LR4 buccal", "LR4 lingual", "LR6 mesio-buccal", "LR6 distal-buccal", "LR6 mesio-lingual", "LR6 distal-lingual", "LL4 buccal", "LL4 lingual", "LL6 mesio-buccal", "LL6 distal-buccal", "LL6 mesio-lingual", "LL6 distal-lingual"), each=3), c("3mm", "6mm", "9mm"), sep="_"), sep="_")

data.frame(variables=c(names1, names2), sample_size=round(unlist(sample_size)))%>%
datatable(extensions = 'Buttons',
          caption = "", 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```

*  two sample t test and  90% power was used.  

