---
title: "02/24 2025"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2025-02-24"
---


```{r, echo=F, message=F, warning=F}
library(rprojroot)
root <- rprojroot::find_rstudio_root_file()
```



```{r, echo=F, message=F, warning=F, results=F}
source(file.path(root, "analysis/Rfunctions.R"))
root <- rprojroot::find_rstudio_root_file()
changeCellColor <- function(row, col){
  c(
    "function(row, data, num, index){",
    sprintf("  if(index == %d){", row-1),
    sprintf("    $('td:eq(' + %d + ')', row)", col),
    "    .css({'background-color': 'orange'});",
    "  }",
    "}"  
  )
}
```



```{r, message=F, warning=F, eval=F}
size_data=multiplesheets((file.path(root, "..\\2025\\202502\\Amal\\Data Submission for Statistical Analysis\\size Amal.xlsx")))
zeta_data=multiplesheets((file.path(root, "..\\2025\\202502\\Amal\\Data Submission for Statistical Analysis\\zeta Amal.xlsx")))
```


```{r, message=F, warning=F}
size_data_annova=data.frame(mcns=paste("MCNr", rep(c(0,1,2,3,4,5), each=3), sep="_"), value=c(3930,
3691,
7615,
2405,
2677,
3018,
3058,
2764,
3080,
2147,
2087,
2280,
6184,
6489,
6779,
1922,
2847,
3784
))

anova_test=aov(value~mcns, data=size_data_annova)
  pvalue=summary(anova_test)[[1]][["Pr(>F)"]][1]
pvalue  
```
* small p value suggests they are not all the same 



```{r, message=F, warning=F}
zeta_data_annova=data.frame(mcns=paste("MCN", rep(c(0,1,2,3,4,5,6,7,8,9,10), each=3), sep="_"), value=c(25,
25,
25,
25.1,
25,
24.9,
25,
25,
25.1,
25,
24.9,
25,
25.1,
25,
24.9,
25,
24.9,
25,
25.1,
25,
24.9,
24.9,
25,
25,
24.9,
25,
25.1,
25,
24.9,
25.1,
25,
25,
24.9
))

anova_test=aov(value~mcns, data=zeta_data_annova)
  pvalue=summary(anova_test)[[1]][["Pr(>F)"]][1]
pvalue  
```

* null hypothesis of being equal is failed to reject due to large p value. 




## Table 8 



```{r, message=F, warning=F}
table8_data_annova=data.frame(Fs=paste("MCN", rep(c("F1", "F2", "F3", "F4", "F5"), each=3), sep="_"), value=c(0.532, 0.685, 0.551, 0.676, 0.663, 0.710, 0.570, 0.339, 0.341, 0.483, 0.418, 0.612, 0.531, 0.620, 0.050
))

anova_test=aov(value~Fs, data=table8_data_annova)
  pvalue=summary(anova_test)[[1]][["Pr(>F)"]][1]
pvalue  
```

* fail to reject null hypothesis of being equal F1=F2=F3=F4=F5.  