---
title: " 01/13 2025"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2025-01-13"
---

```{r, echo=F, message=F, warning=F, results=F}
library(rprojroot)
root <- rprojroot::find_rstudio_root_file()
source(file.path(root, "analysis/Rfunctions.R"))
root <- rprojroot::find_rstudio_root_file()
```



```{r, message=F, warning=F, results=F}
data_raw=multiplesheets((file.path(root, "..\\2025\\202501\\Ardita\\T1, T2, T3, T4, HWCVMS Comparisons copy.xlsx")))
```





## Inter rater reliability 


###  Cohen’s Kappa


```{r, message=F, warning=F}

kappa_pvalue=numeric()
kappa_value=numeric()
for (i in 1:5)
{
sub_data=data_raw[[i+2]]
ratings=sub_data[,2:3] %>% drop_na()
kappa_test=kappa2(ratings, weight = )
kappa_pvalue[i]=kappa_test$p.value
kappa_value[i]=kappa_test$value
}

data.frame(para=names(data_raw)[3:7], kappa_value=round(kappa_value,4), kappa_pvalue=pvalue_adjust(kappa_pvalue)) %>%
datatable(extensions = 'Buttons',
          caption = "", 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

* the last row probably is because of 0 variation of column `CVMS`.  






## Intra-rater reliability 


### Cohen’s Kappa


```{r, message=F, warning=F}

kappa_pvalue=numeric()
kappa_value=numeric()
for (i in 1:2)
{
sub_data=data_raw[[i]]
ratings=sub_data[,2:3] %>% drop_na()
kappa_test=kappa2(ratings)
kappa_pvalue[i]=kappa_test$p.value
kappa_value[i]=kappa_test$value
}

data.frame(Time=names(data_raw)[1:2], kappa_value=round(kappa_value,4), kappa_pvalue=pvalue_adjust(kappa_pvalue)) %>%
datatable(extensions = 'Buttons',
          caption = "", 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```



*  Cohen’s Kappa was used 

* [reference](https://www.andywills.info/rminr/irr.html)



### ICC 


```{r,  message=F, warning=F}

### ICC

icc_pvalue=numeric()
icc_value=numeric()
for (i in 1:2)
{
sub_data=data_raw[[i]]
ratings=sub_data[,2:3] %>% drop_na()
#ratings$`T3 Growth`[ratings$`T3 Growth`=="Pre"]=1
#ratings$`T3 Growth`[ratings$`T3 Growth`=="Peak"]=2
#ratings$`T3 Growth`[ratings$`T3 Growth`=="Post"]=3

#ratings$`T4 Growth`[ratings$`T4 Growth`=="Pre"]=1
#ratings$`T4 Growth`[ratings$`T4 Growth`=="Peak"]=2
#ratings$`T4 Growth`[ratings$`T4 Growth`=="Post"]=3

### input of icc must be numeric numbers 
ratings[,1][ratings[,1]=="Pre"]=1
ratings[,1][ratings[,1]=="Peak"]=2
ratings[,1][ratings[,1]=="Post"]=3

ratings[,2][ratings[,2]=="Pre"]=1
ratings[,2][ratings[,2]=="Peak"]=2
ratings[,2][ratings[,2]=="Post"]=3

ratings <- as.data.frame(ratings)  # Convert list to data frame
ratings <- as.matrix(ratings)      # Convert data frame to matrix
ratings <- apply(ratings, 2, as.numeric)

icc_test=icc(ratings, model ="oneway",  type = "consistency")
icc_pvalue[i]=icc_test$p.value
icc_value[i]=icc_test$value
}


data.frame(para=names(data_raw)[1:2], icc_value=round(icc_value,4), icc_pvalue=pvalue_adjust(icc_pvalue)) %>%
datatable(extensions = 'Buttons',
          caption = "", 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```