---
title: "02/04 2026"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2026-02-04"
---



```{r, echo=F, message=F, warning=F, results=F}
library(rprojroot)
root <- rprojroot::find_rstudio_root_file()
source(file.path(root, "analysis/Rfunctions.R"))
root <- rprojroot::find_rstudio_root_file()
```






```{r, echo=F, message=F, warning=F}
file_path <- "C:/Shengtong/Research/AllCollaboration/2026/202602/Rady/Data analysis 1-30-2026.xlsx"
#all_sheets=multiplesheets("C:/Shengtong/Research/AllCollaboration/2026/202602/Rady/Data analysis 1-30-2026.xlsx")
#save(all_sheets, file="C:/Shengtong/Research/AllCollaboration/2026/202602/Rady/all_sheets.RData")

```
 
 
```{r, message=F, warning=F}
load(file.path(root, "../2026/202602/Rady/all_sheets.RData"))
data=all_sheets$Data
variable_codes=all_sheets$`Coding `
backup=all_sheets$`Combined 9-30-2025 backup`

```



1. [all patients](2026_0201_rady_01.html)

2. [test patients only](2026_0201_rady_02.html)

3. [placebo patients only](2026_0201_rady_03.html)

4. [test vs placebo patients](2026_0201_rady_04.html)