---
title: "response to comments"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
date: "2026-01-28"
---

```{r, echo=F, message=F, warning=F, results=F}
library(rprojroot)
root <- rprojroot::find_rstudio_root_file()
source(file.path(root, "analysis/Rfunctions.R"))
root <- rprojroot::find_rstudio_root_file()
```


```{r, message=F, warning=F, results=F}
precision=read_xlsx((file.path(root, "../2026/202601/Arndt/Precision_FALCON_Smart Glasses.xlsx")))
trueness=read_xlsx((file.path(root, "../2026/202601/Arndt/Trueness_FALCON_Smart Glasses.xlsx")))
```



* [main analysis](https://han16.github.io/Collaborations/2023_1102_Arndt.html)


## linear mixed effect model (LMM)

consider the LLM as 

$$y_{ij}=\beta_0+\beta_1 \times Position_{ij}+\mu_i+\epsilon_{ij}
$$


1. $y_{ij}$ is the outcome variable, $i$ is the patient index, $j$ is the implant position index 

2. $\beta_0$ random intercept for patients 

3. $\beta_1$ fixed effect for implant position 

4. $\mu_i \sim N(0, \sigma^2_{patient})$, random effect for subject $i$. 

5. $\epsilon_{ij} \sim (0, \sigma^2)$




```{r, message=F, warning=F}
data_dCAIS <- trueness %>% filter(Workflow==2)  %>%
  mutate(
    patient = sub("_.*", "", Sample),  # D01, D02, ...
    patient = factor(patient),
    Position = factor(Position)        # treat positions as fixed categories
  )
library(lme4)
library(Matrix)
m_angle <- lmer(
  Angle ~ Position + (1 | patient),
  data = data_dCAIS
)



isSingular(m_angle)        # TRUE/FALSE
summary(m_angle)
VarCorr(m_angle)           # shows variance of random effects

```


```{r, message=F, warning=F}
library(broom.mixed)
library(lmerTest)

outcomes <- c("Angle", "Base3Doffset", "Basedistal", "Basevestibular", "Baseapical",
              "Tip3Doffset", "Tipdistal", "Tipvestibular", "Tipapical", "Apical")

results_list <- lapply(outcomes, function(yvar) {
  # Fit LMM with lmerTest to get p-values
  mod <- lmer(as.formula(paste(yvar, "~ Position + (1 | patient)")), data = data_dCAIS)
  
  # Fixed effects with p-values
  fe <- broom.mixed::tidy(mod, effects = "fixed") %>%
    select(term, estimate, std.error, statistic, p.value) %>%
    mutate(
      estimate = round(estimate, 4),
      std.error = round(std.error, 4),
      statistic = round(statistic, 4),
      p.value = round(p.value, 4),
      outcome = yvar
    )
  
  # Random effects variance
  re <- as.data.frame(lme4::VarCorr(mod)) %>%
    select(grp, var1, vcov) %>%
    rename(Group = grp, RandomEffect = var1, Variance = vcov) %>%
    mutate(
      Variance = round(Variance, 4),
      outcome = yvar
    )
  
  list(fixed = fe, random = re)
})


fixed_table <- do.call(rbind, lapply(results_list, `[[`, "fixed")) %>%
  select(outcome, term, estimate, std.error, statistic, p.value)

fixed_table%>%
datatable(extensions = 'Buttons',
          caption = "fixed effect", 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


random_table <- do.call(rbind, lapply(results_list, `[[`, "random")) %>%
  select(outcome, Group, RandomEffect, Variance)

random_table%>%
datatable(extensions = 'Buttons',
          caption = "random effect", 
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```
